from BaseClasses import Item, ItemClassification

class HitmanItem(Item):
    game: str = "HITMAN World of Assasination"

base_id = 2023011800

item_table= { # id, required entitlement (all), classifier
	"Level - ICA Facility":(1,["ica_facility"], ItemClassification.progression),
	"Level - Paris":(2,["paris"], ItemClassification.progression),
	"Level - Sapienza":(3,["sapienza"], ItemClassification.progression),
	"Level - Marrakesh":(4,["marrakesh"], ItemClassification.progression),
	"Level - Bangkok":(5,["bangkok"], ItemClassification.progression),
	"Level - Colorado":(6,["colorado"], ItemClassification.progression),
	"Level - Hokkaido":(7,["hokkaido"], ItemClassification.progression),
	"Level - Hawkes Bay":(8,["hawkes_bay"], ItemClassification.progression),
	"Level - Miami":(9,["miami"], ItemClassification.progression),
	"Level - Santa Fortuna":(10,["santa_fortuna"], ItemClassification.progression),
	"Level - Mumbai":(11,["mumbai"], ItemClassification.progression),
	"Level - Whittleton Creek":(12,["whittleton_creek"], ItemClassification.progression),
	"Level - Isle of Sgail":(13,["isle_of_sgail"], ItemClassification.progression),
	"Level - New York":(14,["new_york"], ItemClassification.progression),
	"Level - Haven Island":(15,["haven_island"], ItemClassification.progression),
	"Level - Dubai":(16,["dubai"], ItemClassification.progression),
	"Level - Dartmoor":(17,["dartmoor"], ItemClassification.progression),
	"Level - Berlin":(18,["berlin"], ItemClassification.progression),
	"Level - Chongqing":(19,["chongqing"], ItemClassification.progression),
	"Level - Mendoza":(20,["mendoza"], ItemClassification.progression),
	"Level - Carpathian Mountains":(21,["carpathian_mountains"], ItemClassification.progression),
	"Level - Ambrose Island":(22,["ambrose_island"], ItemClassification.progression),
	"Suit - 47's Signature Suit":(23,[], ItemClassification.filler),
	"Suit - Tuxedo":(24,["duplicate","H2_LEGACY"], ItemClassification.filler),
	"Suit - Requiem Suit":(25,["REQUIEM_PACK"], ItemClassification.filler),
	"Suit - Tactical Turtleneck":(26,["H2_LEGACY"], ItemClassification.filler),
	"Suit - Italian Suit":(27,["duplicate","H2_LEGACY"], ItemClassification.filler),
	"Suit - Italian Suit (No Glasses)":(28,["duplicate","H2_LEGACY"], ItemClassification.filler),
	"Suit - Summer Suit":(29,["duplicate","H2_LEGACY"], ItemClassification.filler),
	"Suit - Casual Suit":(30,["duplicate","H2_LEGACY"], ItemClassification.filler),
	"Suit - Recon Gear":(31,["duplicate","H1_GOTY"], ItemClassification.filler),
	"Suit - Tactical Gear":(32,["duplicate","H2_LEGACY"], ItemClassification.filler),
	"Suit - VIP Patient":(33,["H2_LEGACY"], ItemClassification.filler),
	"Suit - Ninja":(34,["duplicate","H2_LEGACY"], ItemClassification.filler),
	"Suit - Absolution Suit":(35,[], ItemClassification.filler),
	"Suit - Blood Money Suit with Gloves":(36,[], ItemClassification.filler),
	"Suit - 47's Signature Suit with Gloves":(37,[], ItemClassification.filler),
	"Suit - Tuxedo with Gloves":(38,["H2_LEGACY"], ItemClassification.filler),
	"Suit - Italian Suit with Gloves":(39,["H2_LEGACY"], ItemClassification.filler),
	"Suit - Summer Suit with Gloves":(40,["H2_LEGACY"], ItemClassification.filler),
	"Suit - Casual Suit with Gloves":(41,["H2_LEGACY"], ItemClassification.filler),
	"Suit - Tactical Gear with Hunter's Hat":(42,["H2_LEGACY"], ItemClassification.filler),
	"Suit - White Yukata":(43,["H2_LEGACY"], ItemClassification.filler),
	"Suit - Terminus":(44,[], ItemClassification.filler),
	"Suit - Winter Suit":(45,[], ItemClassification.filler),
	"Suit - Futo Suit":(46,[], ItemClassification.filler),
	"Suit - Freedom Phantom Suit":(47,[], ItemClassification.filler),
	"Suit - Lynch Suit":(48,[], ItemClassification.filler),
	"Suit - Santa 47":(49,["H2_LEGACY"], ItemClassification.filler),
	"Starting Location - Hokkaido - Tobias Rieper's Suite":(50,["duplicate","hokkaido"], ItemClassification.filler),
	"Starting Location - Hokkaido - Infiltrating Along the Mountain Path":(51,["hokkaido"], ItemClassification.filler),
	"Starting Location - Hokkaido - Undercover in the Operating Theater":(52,["hokkaido"], ItemClassification.filler),
	"Starting Location - Hokkaido - Undercover in the Kitchen":(53,["hokkaido"], ItemClassification.filler),
	"Starting Location - Hokkaido - Spa":(54,["hokkaido"], ItemClassification.filler),
	"Starting Location - Hokkaido - Morgue":(55,["hokkaido"], ItemClassification.filler),
	"Starting Location - Hokkaido - Undercover in the Garden":(56,["hokkaido"], ItemClassification.filler),
	"Starting Location - Hokkaido - Undercover in the Staff Quarters":(57,["hokkaido"], ItemClassification.filler),
	"Starting Location - Hokkaido - Restaurant":(58,["hokkaido"], ItemClassification.filler),
	"Starting Location - Colorado - Undercover in the Farm House":(59,["colorado"], ItemClassification.filler),
	"Starting Location - Colorado - West Bridge":(60,["colorado"], ItemClassification.filler),
	"Starting Location - Colorado - Old Orchard":(61,["colorado"], ItemClassification.filler),
	"Starting Location - Colorado - Water Tower":(62,["colorado"], ItemClassification.filler),
	"Starting Location - Colorado - Undercover in the Garage":(63,["colorado"], ItemClassification.filler),
	"Starting Location - Colorado - Undercover by the Greenhouse":(64,["colorado"], ItemClassification.filler),
	"Starting Location - Colorado - Undercover on the Demolition Range":(65,["colorado"], ItemClassification.filler),
	"Starting Location - Bangkok - 47's Suite":(66,["bangkok"], ItemClassification.filler),
	"Starting Location - Bangkok - Undercover by the Security Hut":(67,["bangkok"], ItemClassification.filler),
	"Starting Location - Bangkok - Undercover at the Himmapan Bar":(68,["bangkok"], ItemClassification.filler),
	"Starting Location - Bangkok - Undercover in the Restaurant Kitchen":(69,["bangkok"], ItemClassification.filler),
	"Starting Location - Bangkok - Undercover in the Linen Room":(70,["bangkok"], ItemClassification.filler),
	"Starting Location - Bangkok - Undercover in the 2nd Floor Hallway":(71,["bangkok"], ItemClassification.filler),
	"Starting Location - Bangkok - Riverside Landing":(72,["duplicate","bangkok"], ItemClassification.filler),
	"Starting Location - Bangkok - Undercover in the Side Garden":(73,["bangkok"], ItemClassification.filler),
	"Starting Location - Marrakesh - Lamp Store Rooftop":(74,["marrakesh"], ItemClassification.filler),
	"Starting Location - Marrakesh - Undercover in the Courtyard Club":(75,["marrakesh"], ItemClassification.filler),
	"Starting Location - Marrakesh - Undercover on the West Bazaar Rooftop":(76,["marrakesh"], ItemClassification.filler),
	"Starting Location - Marrakesh - Undercover at the Snail Stand":(77,["marrakesh"], ItemClassification.filler),
	"Starting Location - Marrakesh - Consulate Parking Garage":(78,["marrakesh"], ItemClassification.filler),
	"Starting Location - Hokkaido - Bar":(79,["unknown","hokkaido"], ItemClassification.filler),
	"Starting Location - Paris - STARTING_LOCATION_PARIS_WATER":(80,["unsued","paris"], ItemClassification.filler),
	"Starting Location - STARTING_LOCATION_MAGNOLIA":(81,["unsued"], ItemClassification.filler),
	"Starting Location - STARTING_LOCATION_BELLFLOWER_LEVEL1":(82,["unsued"], ItemClassification.filler),
	"Starting Location - STARTING_LOCATION_BELLFLOWER_LEVEL2":(83,["unsued"], ItemClassification.filler),
	"Starting Location - STARTING_LOCATION_BELLFLOWER_LEVEL3":(84,["unsued"], ItemClassification.filler),
	"Suit - TOKEN_OUTFIT_NEWZEALAND_HERO_NEWZEALANDSUIT":(85,["duplicate"], ItemClassification.filler),
	"Suit - TOKEN_OUTFIT_MIAMI_HERO_MIAMISUIT":(86,["duplicate"], ItemClassification.filler),
	"Suit - Florida Fit With Gloves":(87,[], ItemClassification.filler),
	"Suit - TOKEN_OUTFIT_COLOMBIA_HERO_COLOMBIASUIT":(88,["duplicate"], ItemClassification.filler),
	"Suit - Casual Tourist With Gloves":(89,[], ItemClassification.filler),
	"Suit - TOKEN_OUTFIT_MUMBAI_HERO_MUMBAISUIT":(90,["duplicate"], ItemClassification.filler),
	"Suit - Imperial Classic With Gloves":(91,[], ItemClassification.filler),
	"Suit - TOKEN_OUTFIT_NORTHAMERICA_HERO_NORTHAMERICASUIT":(92,["duplicate"], ItemClassification.filler),
	"Suit - Subburban Suit With Driving Gloves":(93,[], ItemClassification.filler),
	"Suit - TOKEN_OUTFIT_NORTHSEA_HERO_NORTHSEASUIT":(94,["duplicate"], ItemClassification.filler),
	"Suit - Tuxedo, Mask and Gloves":(95,[], ItemClassification.filler),
	"Suit - The New Yorker":(96,["H2_GREEDY","duplicate"], ItemClassification.filler),
	"Suit - The Tropical Islander":(97,["H2_STINGRAY"], ItemClassification.filler),
	"Suit - Midnight Black Suit":(98,["H2_COLLECTORS_OR_EXECUTIVE"], ItemClassification.filler),
	"Suit - Black Winter Suit":(99,[], ItemClassification.filler),
	"Suit - The Undying Look":(100,[], ItemClassification.filler),
	"Suit - Casual Undercover":(101,[], ItemClassification.filler),
	"Suit - Classic All-Black Suit":(102,[], ItemClassification.filler),
	"Suit - Blue Flamingo Suit":(103,[], ItemClassification.filler),
	"Suit - Phantom Suit":(104,[], ItemClassification.filler),
	"Suit - Snow Festival Suit":(105,["H2_LEGACY"], ItemClassification.filler),
	"Suit - Winter Sports Suit":(106,["H2_WINTER_SPORTS"], ItemClassification.filler),
	"Suit - Clown Suit":(107,["H1_GOTY"], ItemClassification.filler),
	"Suit - Smart Casual Suit":(108,["H2_SMART_CASUAL"], ItemClassification.filler),
	"Suit - The Tropical Suit":(109,["H2_STINGRAY"], ItemClassification.filler),
	"Suit - Summer Suave Suit":(110,[], ItemClassification.filler),
	"Suit - Tactical Wetsuit":(111,[], ItemClassification.filler),
	"Suit - The Cashmerian":(112,[], ItemClassification.filler),
	"Suit - Raven Suit":(113,["H1_GOTY"], ItemClassification.filler),
	"Suit - Cowboy Suit":(114,["H1_GOTY"], ItemClassification.filler),
	"Suit - TOKEN_OUTFIT_WELCOME_SUIT":(115,["unknown"], ItemClassification.filler),
	"Suit - The New Yorker with Gloves":(116,["H2_GREEDY"], ItemClassification.filler),
	"Suit - The Greek Fire Suit":(117,[], ItemClassification.filler),
	"Suit - The Club Boom DJ Suit":(118,["H3_ET_TOMORROWLAND"], ItemClassification.filler),
	"Starting Location - Marrakesh - STARTING_LOCATION_MARRAKESH_DARK_ROOFTOP":(119,["unsued","marrakesh"], ItemClassification.filler),
	"Starting Location - Marrakesh - Undercover in the Consulate":(120,["marrakesh"], ItemClassification.filler),
	"Starting Location - Marrakesh - Undercover in Zaydan's Compound":(121,["marrakesh"], ItemClassification.filler),
	"Starting Location - Marrakesh - School Alley":(122,["marrakesh"], ItemClassification.filler),
	"Starting Location - Paris - Undercover at IAGO Auction":(123,["paris"], ItemClassification.filler),
	"Starting Location - Paris - Undercover in Locker Room":(124,["paris"], ItemClassification.filler),
	"Starting Location - Paris - Undercover in Kitchen":(125,["paris"], ItemClassification.filler),
	"Starting Location - Paris - Undercover in Dressing Area":(126,["paris"], ItemClassification.filler),
	"Starting Location - Paris - Pile-Driver Barge":(127,["paris"], ItemClassification.filler),
	"Starting Location - Paris - Undercover in AV Center":(128,["paris"], ItemClassification.filler),
	"Starting Location - Paris - Attic":(129,["paris"], ItemClassification.filler),
	"Starting Location - Paris - Palace Garden":(130,["paris"], ItemClassification.filler),
	"Starting Location - Sapienza - Undercover in Field Lab":(131,["sapienza"], ItemClassification.filler),
	"Starting Location - Sapienza - Undercover as Security Staff":(132,["sapienza"], ItemClassification.filler),
	"Starting Location - Sapienza - Undercover in Mansion Garden":(133,["sapienza"], ItemClassification.filler),
	"Starting Location - Sapienza - Undercover in Mansion Kitchen":(134,["sapienza"], ItemClassification.filler),
	"Starting Location - Sapienza - Via Valle del Sole 9":(135,["unknown","sapienza"], ItemClassification.filler),
	"Starting Location - Sapienza - Main Square Tower":(136,["sapienza"], ItemClassification.filler),
	"Starting Location - Sapienza - Church Morgue":(137,["sapienza"], ItemClassification.filler),
	"Starting Location - Sapienza - Harbor":(138,["sapienza"], ItemClassification.filler),
	"Starting Location - Sapienza - Sapienza Ruins":(139,["sapienza"], ItemClassification.filler),
	"Starting Location - Sapienza - ICA Safe House":(140,["sapienza"], ItemClassification.filler),
	"Hidden Stash - Hokkaido - Operating Theater Restroom":(141,["hokkaido"], ItemClassification.filler),
	"Hidden Stash - Hokkaido - Restaurant Restroom":(142,["hokkaido"], ItemClassification.filler),
	"Agency Pickup - Hokkaido - Mountain Path":(143,["hokkaido"], ItemClassification.filler),
	"Agency Pickup - Hokkaido - Kitchen Food Storage":(144,["hokkaido"], ItemClassification.filler),
	"Agency Pickup - Hokkaido - Garage":(145,["hokkaido"], ItemClassification.filler),
	"Agency Pickup - Hokkaido - Morgue Storage":(146,["hokkaido"], ItemClassification.filler),
	"Hidden Stash - Hokkaido - Staff Wardrobe":(147,["hokkaido"], ItemClassification.filler),
	"Agency Pickup - Colorado - Red Barn":(148,["colorado"], ItemClassification.filler),
	"Agency Pickup - Colorado - Water Tower":(149,["colorado"], ItemClassification.filler),
	"Agency Pickup - Colorado - West Bridge":(150,["colorado"], ItemClassification.filler),
	"Hidden Stash - Colorado - Hay Shed":(151,["colorado"], ItemClassification.filler),
	"Hidden Stash - Colorado - Courtyard Shed":(152,["colorado"], ItemClassification.filler),
	"Hidden Stash - Colorado - Ground Floor Laundry Room":(153,["colorado"], ItemClassification.filler),
	"Hidden Stash - Colorado - Orchard Road":(154,["colorado"], ItemClassification.filler),
	"Hidden Stash - Colorado - Truck Loading Area":(155,["colorado"], ItemClassification.filler),
	"Agency Pickup - Bangkok - 47's Suite":(156,["duplicate","bangkok"], ItemClassification.filler),
	"Agency Pickup - Bangkok - Storage Room":(157,["bangkok"], ItemClassification.filler),
	"Agency Pickup - Bangkok - Garden Shed":(158,["bangkok"], ItemClassification.filler),
	"Agency Pickup - Bangkok - AGENCYPICKUP_BANGKOK_TIGER_MEDITATION":(159,["unknown","bangkok"], ItemClassification.filler),
	"Agency Pickup - Bangkok - North Wing Basement":(160,["unknown","bangkok"], ItemClassification.filler),
	"Agency Pickup - Bangkok - South Wing Basement":(161,["bangkok"], ItemClassification.filler),
	"Agency Pickup - Bangkok - Penthouse":(162,["bangkok"], ItemClassification.filler),
	"Agency Pickup - Bangkok - Recording Studio":(163,["bangkok"], ItemClassification.filler),
	"Hidden Stash - Bangkok - 1st Floor South Wing Balcony":(164,["bangkok"], ItemClassification.filler),
	"Hidden Stash - Bangkok - Ground Floor Restaurant Restroom":(165,["bangkok"], ItemClassification.filler),
	"Hidden Stash - Bangkok - Room 102 Bathroom":(166,["bangkok"], ItemClassification.filler),
	"Agency Pickup - Marrakesh - West Bazaar Rooftops":(167,["marrakesh"], ItemClassification.filler),
	"Agency Pickup - Marrakesh - Old Headmaster's Terrace":(168,["marrakesh"], ItemClassification.filler),
	"Agency Pickup - Marrakesh - Lamp Shop Alley":(169,["duplicate","marrakesh"], ItemClassification.filler),
	"Hidden Stash - Marrakesh - Carpet Shop":(170,["marrakesh"], ItemClassification.filler),
	"Hidden Stash - Marrakesh - Shisha Café Restroom":(171,["marrakesh"], ItemClassification.filler),
	"Hidden Stash - Marrakesh - Mechanic Shop":(172,["marrakesh"], ItemClassification.filler),
	"Agency Pickup - Marrakesh - Consulate Parking Garage":(173,["marrakesh"], ItemClassification.filler),
	"Agency Pickup - Marrakesh - School Gate":(174,["marrakesh"], ItemClassification.filler),
	"Hidden Stash - Marrakesh - Consulate Top Floor":(175,["marrakesh"], ItemClassification.filler),
	"Agency Pickup - Paris - Basement Stairwell":(176,["duplicate","paris"], ItemClassification.filler),
	"Hidden Stash - Paris - AGENCYPICKUP_PARIS_OFFICE_CURTAINS":(177,["unknown","paris"], ItemClassification.filler),
	"Agency Pickup - Paris - Shed":(178,["paris"], ItemClassification.filler),
	"Agency Pickup - Paris - Empty Attic Room":(179,["paris"], ItemClassification.filler),
	"Hidden Stash - Paris - Top Floor Bathroom":(180,["paris"], ItemClassification.filler),
	"Hidden Stash - Paris - Pantry":(181,["paris"], ItemClassification.filler),
	"Hidden Stash - Paris - First Floor Apartments":(182,["paris"], ItemClassification.filler),
	"Agency Pickup - Paris - Logistics Trailer":(183,["paris"], ItemClassification.filler),
	"Agency Pickup - Sapienza - Ether Field Lab":(184,["sapienza"], ItemClassification.filler),
	"Hidden Stash - Sapienza - Mansion Pantry":(185,["sapienza"], ItemClassification.filler),
	"Hidden Stash - Sapienza - Mansion Garage":(186,["sapienza"], ItemClassification.filler),
	"Agency Pickup - Sapienza - Via Valle del Sole 9":(187,["unknown","sapienza"], ItemClassification.filler),
	"Agency Pickup - Sapienza - ICA Safe House":(188,["duplicate","sapienza"], ItemClassification.filler),
	"Agency Pickup - Sapienza - Café Basement":(189,["sapienza"], ItemClassification.filler),
	"Hidden Stash - Sapienza - Confessional Booth":(190,["sapienza"], ItemClassification.filler),
	"Agency Pickup - Sapienza - Sapienza Ruins":(191,["sapienza"], ItemClassification.filler),
	"Agency Pickup - Sapienza - Sewers":(192,["sapienza"], ItemClassification.filler),
	"Melee - Fiber Wire":(193,[], ItemClassification.filler),
	"Melee - Fiber  Wire Classic":(194,[], ItemClassification.filler),
	"Melee - Earphones":(195,[], ItemClassification.filler),
	"Melee - IO Elite S2VP Earphones":(196,["H2_SMART_CASUAL"], ItemClassification.filler),
	"Melee - The Straitjacket Belt":(197,["H3_DELUXE_PACK"], ItemClassification.filler),
	"Melee - Quickdraw":(198,["H2_WINTER_SPORTS"], ItemClassification.filler),
	"Melee - Fishing Line":(199,[], ItemClassification.filler),
	"Melee - Measuring Tape":(200,[], ItemClassification.filler),
	"Melee - Combat Knife":(201,["H2_LEGACY"], ItemClassification.filler),
	"Melee - Antique Carved Knife":(202,[], ItemClassification.filler),
	"Melee - Hobby Knife":(203,[], ItemClassification.filler),
	"Tool - ICA Titanium Crowbar":(204,[], ItemClassification.filler),
	"Melee - Piton":(205,["H2_WINTER_SPORTS"], ItemClassification.filler),
	"Melee - Walking Cane":(206,[], ItemClassification.filler),
	"Melee - The Devil's Cane":(207,["H3_SINS_GREED"], ItemClassification.filler),
	"Melee - Shuriken":(208,["H2_LEGACY"], ItemClassification.filler),
	"Melee - Bat Shuriken":(209,[], ItemClassification.filler),
	"Melee - The Club Boom 12\" Vinyl Sampler":(210,["H3_ET_TOMORROWLAND"], ItemClassification.filler),
	"Melee - Concealable Knife":(211,["H2_LEGACY"], ItemClassification.filler),
	"Melee - HF Championship Bat":(212,["H2_LEGACY"], ItemClassification.filler),
	"Melee - The Purple Streak Baseball Bat":(213,[], ItemClassification.filler),
	"Melee - Nne Obara's Machete":(214,["H2_LEGACY"], ItemClassification.filler),
	"Melee - Kukri Machette":(215,[], ItemClassification.filler),
	"Melee - Jarl's Pirate Saber":(216,["H2_STINGRAY"], ItemClassification.filler),
	"Melee - The Proud Swashbuckler":(217,["H3_SINS_PRIDE"], ItemClassification.filler),
	"Melee - Okinawan Tonfa":(218,["H2_LEGACY"], ItemClassification.filler),
	"Melee - Feather Duster":(219,[], ItemClassification.filler),
	"Melee - Masamune":(220,["H2_LEGACY"], ItemClassification.filler),
	"Melee - White Katana":(221,["H3_DELUXE_PACK"], ItemClassification.filler),
	"Melee - Concealable Baton":(222,["H2_LEGACY"], ItemClassification.filler),
	"Melee - Janbiya":(223,["H2_LEGACY"], ItemClassification.filler),
	"Melee - Eiffel Tower Souvenir":(224,["not_implemented"], ItemClassification.filler),
	"Melee - Crystal Ball":(225,["H2_LEGACY"], ItemClassification.filler),
	"Melee - Burj Al-Ghazali Snowglobe":(226,[], ItemClassification.filler),
	"Melee - Claw Hammer":(227,[], ItemClassification.filler),
	"Pistol - HWK21":(228,["H2_LEGACY"], ItemClassification.filler),
	"Shotgun - Enram HV":(229,["H2_LEGACY"], ItemClassification.filler),
	"Assault Rifle - TAC-4 AR Desert":(230,["H2_LEGACY"], ItemClassification.filler),
	"Pistol - ICA19":(231,[], ItemClassification.useful),
	"Pistol - ICA19 Black Lilly":(232,["H2_EXECUTIVE"], ItemClassification.filler),
	"Assault Rifle - TAC-4 AR Auto":(233,["H2_LEGACY"], ItemClassification.filler),
	"SMG - TAC-SMG":(234,["H2_LEGACY"], ItemClassification.useful),
	"Assault Rifle - TAC-4 S/A Jungle":(235,["H2_LEGACY"], ItemClassification.filler),
	"Pistol - ICA19 Chrome":(236,["H1_REQUIEM_PACK"], ItemClassification.filler),
	"Pistol - ICA19 Silverballer":(237,["H2_LEGACY"], ItemClassification.filler),
	"Pistol - HWK21 Pale Homemade Silencer":(238,[], ItemClassification.filler),
	"Pistol - Custom 5mm":(239,["H2_LEGACY"], ItemClassification.filler),
	"Pistol - ICA19 F/A":(240,["H2_LEGACY"], ItemClassification.filler),
	"Pistol - HWK21 Covert":(241,["H2_LEGACY"], ItemClassification.filler),
	"Pistol - ICA19 Shortballer":(242,[], ItemClassification.filler),
	"SMG - TAC-SMG S":(243,["H2_LEGACY"], ItemClassification.filler),
	"Assault Rifle - TAC-4 AR Stealth":(244,["H2_LEGACY"], ItemClassification.filler),
	"Shotgun - Enram HV CM":(245,["H2_LEGACY"], ItemClassification.filler),
	"SMG - TAC-SMG Covert":(246,[], ItemClassification.filler),
	"Sniper - Jaeger 7 Lancer":(247,["H2_LEGACY"], ItemClassification.filler),
	"Assault Rifle - RS-15":(248,["H2_LEGACY"], ItemClassification.filler),
	"Assault Rifle - TAC-4 S/A":(249,["H2_LEGACY"], ItemClassification.filler),
	"Sniper - Sieger 300":(250,["H2_LEGACY"], ItemClassification.filler),
	"Sniper - Siger 300 Viper":(251,[], ItemClassification.filler),
	"Shotgun - ENRAM HV Covert":(252,["H2_LEGACY"], ItemClassification.filler),
	"Sniper - Jaeger 7 Tiger":(253,["H2_LEGACY"], ItemClassification.filler),
	"Pistol - Krugermeier 2-2":(254,["H2_LEGACY"], ItemClassification.filler),
	"Pistol - Krugermeier 2-2 Silver":(255,[], ItemClassification.filler),
	"Pistol - Krugermeier 2-2 Dark":(256,[], ItemClassification.filler),
	"Assault Rifle - Sieger AR552 Tactical":(257,[], ItemClassification.filler),
	"Pistol - Striker V3":(258,[], ItemClassification.filler),
	"Sniper - Jaeger 7":(259,["H2_LEGACY"], ItemClassification.filler),
	"Sniper - Jaeger 7 MKII":(260,[], ItemClassification.filler),
	"Explosive - The Pale Duck":(261,["REQUIEM_PACK"], ItemClassification.filler),
	"Distraction - Coin":(262,[], ItemClassification.useful),
	"Distraction - Classic Coin":(263,[], ItemClassification.filler),
	"Explosive - ICA Proximity Explosive":(264,["H2_LEGACY"], ItemClassification.filler),
	"Explosive - The Serpent's Bite":(265,["H3_SINS_LUST"], ItemClassification.filler),
	"Explosive - The Roar Flash Grenade":(266,["H3_SINS_WRATH"], ItemClassification.filler),
	"Poision - Modern Lethal Syringe":(267,["H2_LEGACY"], ItemClassification.useful),
	"Poision - Emetic Poison Vial  MK III":(268,[], ItemClassification.filler),
	"Poision - \"Bubble Queen\"Gum Pack":(269,["H3_SINS_GLUTTONLY"], ItemClassification.filler),
	"Poision - Sedative Poision Vial MK III":(270,[], ItemClassification.filler),
	"Tool - Lockpick":(271,["H2_LEGACY"], ItemClassification.useful),
	"Tool - Lockpick MK II":(272,[], ItemClassification.filler),
	"Tool - Lockpick MK III":(273,[], ItemClassification.filler),
	"Tool - Classic Lockpick":(274,[], ItemClassification.filler),
	"Tool - Bone Lockpick":(275,[], ItemClassification.filler),
	"Tool - Handyman Wrench":(276,[], ItemClassification.filler),
	"Tool - Professional Screwdriver":(277,[], ItemClassification.filler),
	"Distraction - ICA Remote Audio Distraction":(278,["H2_LEGACY"], ItemClassification.filler),
	"Distraction - \"Mixtape 47\"":(279,["H2_LEGACY"], ItemClassification.filler),
	"Explosive - ICA Remote Explosive":(280,["H2_LEGACY"], ItemClassification.useful),
	"Explosive - ICA Remote Explosive MK III":(281,[], ItemClassification.filler),
	"Explosive - Proximity Explosive Duck":(282,["H2_LEGACY"], ItemClassification.filler),
	"Explosive - Remote Explosive Classic Rubber Duck":(283,[], ItemClassification.filler),
	"Explosive - Remove Explosive Devil Rubber Duck":(284,[], ItemClassification.filler),
	"Explosive - The Iconator":(285,["H2_LEGACY"], ItemClassification.filler),
	"Explosive - ICA Proximity Explosive MK III":(286,[], ItemClassification.filler),
	"Explosive - Proximity Semtex Demo Block MK III":(287,[], ItemClassification.filler),
	"Explosive - Remote Semetex Demo Block MK III":(288,[], ItemClassification.filler),
	"Explosive - Napolen Blownaparte":(289,["H2_LEGACY"], ItemClassification.filler),
	"Explosive - Lil' Flashy":(290,["H2_LEGACY"], ItemClassification.filler),
	"Explosive - Explosive Xmas Gift":(291,["H2_LEGACY"], ItemClassification.filler),
	"Explosive - Explosive Pen":(292,[], ItemClassification.filler),
	"Explosive - The Ancestral Fountain Pen":(293,["LOCATION_GOLDEN"], ItemClassification.filler),
	"Explosive - Remote Explosive Duck":(294,["H2_LEGACY"], ItemClassification.filler),
	"Explosive - Proximity Explosive Duck MK III":(295,[], ItemClassification.filler),
	"Explosive - Sunset Rubber Duck":(296,[], ItemClassification.filler),
	"Explosive - Proximity CX Demo Block":(297,["H2_LEGACY"], ItemClassification.filler),
	"Explosive - Remote CX Demo Block":(298,["H2_LEGACY"], ItemClassification.filler),
	"Explosive - Remote Breaching Charge":(299,["H2_LEGACY"], ItemClassification.filler),
	"Explosive - ICA Explosive Phone":(300,["H2_LEGACY"], ItemClassification.filler),
	"Explosive - Explosive Compound":(301,["H2_LEGACY"], ItemClassification.filler),
	"Explosive - Explosive Golf Ball":(302,[], ItemClassification.filler),
	"Distraction - The Big One":(303,["H2_LEGACY"], ItemClassification.filler),
	"Tool - Remote EMP Charge":(304,[], ItemClassification.filler),
	"Distraction - Gold Coin":(305,[], ItemClassification.filler),
	"Melee - Blueberry Muffin":(306,[], ItemClassification.filler),
	"Poision - Emetic Poison Vial":(307,["H2_LEGACY"], ItemClassification.useful),
	"Poision - Sedative Poision Vial":(308,["H2_LEGACY"], ItemClassification.useful),
	"Poision - Lethal Poison Vial MK III":(309,[], ItemClassification.filler),
	"Poision - Lethal Poison Vial":(310,["H2_LEGACY"], ItemClassification.useful),
	"Poision - Antique Emetic Syringe":(311,["H2_LEGACY"], ItemClassification.filler),
	"Poision - ICA Pen Syringe Emetic":(312,[], ItemClassification.filler),
	"Poision - Guru's Pen Syringe Emetic":(313,["H3_DELUXE_PACK"], ItemClassification.filler),
	"Poision - Modern Sedative Syringe":(314,["H2_LEGACY"], ItemClassification.useful),
	"Poision - Antique Lethal Syringe":(315,["H2_LEGACY"], ItemClassification.filler),
	"Poision - Modern Emetic Syringe":(316,["H2_LEGACY"], ItemClassification.useful),
	"Tool - Disposable Scrambler":(317,["H2_LEGACY"], ItemClassification.filler),
	"Melee - Fish":(318,[], ItemClassification.filler),
	"Melee - Violin":(319,[], ItemClassification.filler),
	"Melee - Broadsword":(320,[], ItemClassification.filler),
	"Melee - Ornate Scimitar":(321,[], ItemClassification.filler),
	"Melee - Mace":(322,[], ItemClassification.filler),
	"Explosive - Explosive Baseball":(323,[], ItemClassification.filler),
	"Melee - Small Goldbar":(324,["H2_GREEDY"], ItemClassification.filler),
	"Explosive - Magnesium Pouch":(325,[], ItemClassification.filler),
	"Explosive - Shaman Powder":(326,[], ItemClassification.filler),
	"Tool - ICA Proximity Taser":(327,[], ItemClassification.filler),
	"Tool - ICA Remote Taser":(328,[], ItemClassification.filler),
	"Tool - ICA Remote Micro Taser":(329,[], ItemClassification.filler),
	"Tool - Remote Emetic Gas Device":(330,["H2_STINGRAY"], ItemClassification.filler),
	"Tool - ICA Flash Phone":(331,["H2_SMART_CASUAL"], ItemClassification.filler),
	"Explosive - ICA Proximity Concussion Device":(332,[], ItemClassification.filler),
	"Explosive - ICA Proximity Concussion Device MK III":(333,[], ItemClassification.filler),
	"Explosive - ICA Remote Concussion Device":(334,[], ItemClassification.filler),
	"Explosive - Remote Concussion Rubber Duck":(335,[], ItemClassification.filler),
	"Explosive - Goldbrick Proximity Mine":(336,["H3_SINS_SLOTH"], ItemClassification.filler),
	"Explosive - Remote Concussion Collectors Duck":(337,["H2_COLLECTORS"], ItemClassification.filler),
	"Explosive - Concussion Grenade":(338,[], ItemClassification.filler),
	"Explosive - Nitroglycerin":(339,[], ItemClassification.filler),
	"Explosive - Molotov Cocktail":(340,[], ItemClassification.filler),
	"Tool - Emetic Grenade":(341,[], ItemClassification.filler),
	"Tool - Emetic Gas Grenade":(342,[], ItemClassification.useful),
	"Tool - Guru's Emetic Grenade":(343,["H3_DELUXE_PACK"], ItemClassification.filler),
	"Explosive - Flash Grenade":(344,[], ItemClassification.filler),
	"Explosive - Flash Grenade MK III":(345,[], ItemClassification.filler),
	"Explosive - Fragmentation Grenade":(346,[], ItemClassification.filler),
	"Explosive - The Red Light Flash Grenade":(347,["H3_ET_TOMORROWLAND"], ItemClassification.filler),
	"Explosive - ICA Proximity Micro Explosive":(348,[], ItemClassification.filler),
	"Explosive - ICA Tripwire Mine":(349,[], ItemClassification.filler),
	"Explosive - ICA Micro Remote Explosive":(350,[], ItemClassification.filler),
	"Explosive - ICA Remote Flash Device":(351,["H2_GREEDY"], ItemClassification.filler),
	"Explosive - Proximity CX Demo Block MK II":(352,[], ItemClassification.filler),
	"Explosive - Remote CX Demo Block MK II":(353,[], ItemClassification.filler),
	"Explosive - ICA Remote Explosive MK II":(354,[], ItemClassification.filler),
	"Explosive - ICA Proximity Explosive MK II":(355,[], ItemClassification.filler),
	"Explosive - Proximity Explosive Rubber Duck MK II":(356,[], ItemClassification.filler),
	"Explosive - Remote Explosive Rubber Duck MK II":(357,[], ItemClassification.filler),
	"Poision - Emetic Syringe Mk II":(358,[], ItemClassification.filler),
	"Poision - Lethal Syringe Mk II":(359,[], ItemClassification.filler),
	"Poision - Lethal Syringe Mk III":(360,[], ItemClassification.filler),
	"Distraction - ICA Remote Audio Distraction MKII":(361,[], ItemClassification.filler),
	"Distraction - ICA Remote Audio Distraction MKIII":(362,[], ItemClassification.filler),
	"Tool - Electronic Key Hacker":(363,[], ItemClassification.useful),
	"Tool - Electronic Key Hacker MK III":(364,[], ItemClassification.filler),
	"Explosive - Breaching Charge MK II":(365,[], ItemClassification.filler),
	"Explosive - Breaching Charge MK III":(366,[], ItemClassification.filler),
	"Distraction - ICA Remote Micro Audio Distraction":(367,[], ItemClassification.filler),
	"Sniper - Jaeger 7 Tuatara":(368,["H2_STINGRAY"], ItemClassification.filler),
	"Sniper - Jaeger 7 Green Eye":(369,["H3_SINS_ENVY"], ItemClassification.filler),
	"Sniper - Druzhina 34 ICA Arctic":(370,[], ItemClassification.filler),
	"Sniper - Druzhina 34 DTI":(371,[], ItemClassification.filler),
	"Sniper - Sieger 300 Tactical":(372,[], ItemClassification.filler),
	"Sniper - Druzhina 34":(373,[], ItemClassification.filler),
	"Sniper - The Golden Dragon":(374,["H3_DELUXE_PACK"], ItemClassification.filler),
	"Sniper - The Majestic":(375,["H3_SINS_PRIDE"], ItemClassification.filler),
	"Assault Rifle - Shashka A33 H":(376,[], ItemClassification.filler),
	"Assault Rifle - The Shashka Beast":(377,["H3_SINS_WRATH"], ItemClassification.filler),
	"Assault Rifle - Shashka A33 Gold":(378,[], ItemClassification.filler),
	"Sniper - Bartoli Woodsman Hunting Rifle":(379,[], ItemClassification.filler),
	"Assault Rifle - TAC-4 AR MKII":(380,[], ItemClassification.filler),
	"Shotgun - Bartoli 12G Short H":(381,[], ItemClassification.filler),
	"Shotgun - Bartoli Hunting Shotgun Deluxe":(382,["H3_DELUXE_PACK"], ItemClassification.filler),
	"Shotgun - ICA Tactical Shotgun":(383,[], ItemClassification.filler),
	"Shotgun - Sawed-Off Bartoli 12G":(384,["H2_GREEDY"], ItemClassification.filler),
	"Shotgun - The Maximalist Shotgun":(385,["H3_SINS_GLUTTONLY"], ItemClassification.filler),
	"Shotgun - ICA Tactical Shotgun Covert":(386,[], ItemClassification.filler),
	"Shotgun - ICA Tactical White Shotgun Covert":(387,[], ItemClassification.filler),
	"Pistol - \"Rude Ruby\"":(388,[], ItemClassification.filler),
	"SMG - SMG Raptor Rude Ruby Covert":(389,[], ItemClassification.filler),
	"Sniper - The White Ruby Rude 300 Sniper Rifle":(390,[], ItemClassification.filler),
	"Melee - The Iridescent Katana":(391,[], ItemClassification.filler),
	"Pistol - Kalmer 1 - Tranquilizer":(392,[], ItemClassification.useful),
	"Pistol - Sieker 1":(393,["H2_STINGRAY"], ItemClassification.useful),
	"Pistol - The Serpent's Tounge":(394,["H3_SINS_LUST"], ItemClassification.filler),
	"Pistol - Kalmer 2 - Tranquilizer":(395,[], ItemClassification.filler),
	"Pistol - The Taunton Dart Gun":(396,["H3_DELUXE_PACK"], ItemClassification.filler),
	"Pistol - FIREARMS_PISTOL_DARTGUN":(397,["unknown"], ItemClassification.filler),
	"Pistol - ICA19 Silverballer MK II":(398,[], ItemClassification.filler),
	"Pistol - ICA19 Classicballer":(399,[], ItemClassification.filler),
	"Pistol - ICA19 White Trinity":(400,["H3_TRINITY"], ItemClassification.filler),
	"Pistol - ICA19 Black Trinity":(401,["H3_TRINITY"], ItemClassification.filler),
	"Pistol - ICA19 White Trinity":(402,["H3_TRINITY"], ItemClassification.filler),
	"Pistol - ICA19 Goldballer":(403,[], ItemClassification.filler),
	"Pistol - Concept 5":(404,[], ItemClassification.filler),
	"Pistol - HWK21 MK II":(405,[], ItemClassification.filler),
	"SMG - DAK X2 Covert Special":(406,[], ItemClassification.filler),
	"SMG - Slapdash SMG":(407,["H3_SINS_SLOTH"], ItemClassification.filler),
	"SMG - TAC-SMAG MKII":(408,[], ItemClassification.filler),
	"SMG - DAK Black Covert":(409,[], ItemClassification.filler),
	"SMG - DAK Gold Covert":(410,["H3_DELUXE_PACK"], ItemClassification.filler),
	"SMG - ICA SMG Raptor Covert":(411,[], ItemClassification.filler),
	"SMG - Malitia-Issued HX-10 SMG":(412,[], ItemClassification.filler),
	"SMG - Brine-Damaged SMG":(413,[], ItemClassification.filler),
	"Shotgun - Enram HV Covert MKII":(414,[], ItemClassification.filler),
	"Pistol - \"El Matador\"":(415,[], ItemClassification.filler),
	"Poision - Sedative Pills":(416,[], ItemClassification.filler),
	"Poision - Emetic Pills":(417,[], ItemClassification.filler),
	"Poision - Lethal Pills":(418,[], ItemClassification.filler),
	"Poision - Lethal Pills MK III":(419,[], ItemClassification.filler),
	"Sniper - Jaeger 7 Covert":(420,[], ItemClassification.filler),
	"Sniper - Sieger 300 Advanced":(421,["H2_LEGACY"], ItemClassification.filler),
	"Pistol - ICA19 F/A Stealth":(422,["H2_LEGACY"], ItemClassification.filler),
	"Pistol - ICA19 F/A Stealth \"Ducky\" Edition":(423,[], ItemClassification.filler),
	"Pistol - The Floral Baller":(424,[], ItemClassification.filler),
	"Pistol - ICA19 Iceballer":(425,["H2_LEGACY"], ItemClassification.filler),
	"Pistol - ICA DTI Stealth":(426,[], ItemClassification.filler),
	"Pistol - Striker":(427,["H1_GOTY"], ItemClassification.filler),
	"Pistol - Custom 5mm DTI":(428,[], ItemClassification.filler),
	"Melee - A New Bat":(429,["H1_GOTY"], ItemClassification.filler),
	"Melee - Meaty Bone":(430,[], ItemClassification.filler),
	"Melee - Sacrificial Knife":(431,[], ItemClassification.filler),
	"Melee - The Black Almond's Dagger":(432,["H2_STINGRAY"], ItemClassification.filler),
	"Melee - Kukri Knife":(433,[], ItemClassification.filler),
	"Melee - The Cat's Claw":(434,["H3_SINS_ENVY"], ItemClassification.filler),
	"Melee - Tanto":(435,[], ItemClassification.filler),
	"Melee - Ice Pick":(436,["H2_LEGACY"], ItemClassification.filler),
	"Melee - Ice Axe":(437,[], ItemClassification.filler),
	"Melee - ICA combat axe":(438,[], ItemClassification.filler),
	"Melee - Butcher's Saw":(439,[], ItemClassification.filler),
	"Melee - Meat Hook":(440,[], ItemClassification.filler),
	"Melee - Hook":(441,[], ItemClassification.filler),
	"Melee - Snowball":(442,["H2_WINTER_SPORTS"], ItemClassification.filler),
	"Melee - Banana":(443,[], ItemClassification.filler),
	"Sniper - Sieger 300 Ghost":(444,["H1_GOTY"], ItemClassification.useful),
	"Sniper - Sieger 300 Arctic":(445,["H3_DELUXE_PACK"], ItemClassification.filler),
	"Sniper - Hackl Leviathan Sniper Rifle Covert":(446,[], ItemClassification.filler),
	"Sniper - Hackl Sniper Riffle Covert \"Ducky\" Edition":(447,[], ItemClassification.filler),
	"Pistol - The Ducky Gun":(448,[], ItemClassification.filler),
	"Sniper - ICA Bartoli Woodsman Hunting Rifle Covert":(449,[], ItemClassification.filler),
	"Agency Pickup - Hawkes Bay - Beach Shack":(450,["hawkes_bay"], ItemClassification.filler),
	"Hidden Stash - Hawkes Bay - Garbage Container":(451,["hawkes_bay"], ItemClassification.filler),
	"Agency Pickup - Miami - Pit Building Locker Room":(452,["miami"], ItemClassification.filler),
	"Agency Pickup - Miami - Bayside Center Car Park":(453,["duplicate","miami"], ItemClassification.filler),
	"Agency Pickup - Miami - Kronstadt Storage Area":(454,["miami"], ItemClassification.filler),
	"Agency Pickup - Miami - Thwack Paddock":(455,["miami"], ItemClassification.filler),
	"Agency Pickup - Miami - Backstage Truck":(456,["miami"], ItemClassification.filler),
	"Agency Pickup - Miami - Parkside Food Stands":(457,["miami"], ItemClassification.filler),
	"Agency Pickup - Miami - Boat Rental Hut":(458,["miami"], ItemClassification.filler),
	"Hidden Stash - Miami - Kronstadt Reception":(459,["miami"], ItemClassification.filler),
	"Hidden Stash - Miami - Podium Storage":(460,["miami"], ItemClassification.filler),
	"Hidden Stash - Miami - Stands Toilet":(461,["miami"], ItemClassification.filler),
	"Agency Pickup - Santa Fortuna - Village Contruction Building":(462,["santa_fortuna"], ItemClassification.filler),
	"Agency Pickup - Santa Fortuna - Coca Fields":(463,["santa_fortuna"], ItemClassification.filler),
	"Agency Pickup - Santa Fortuna - Construction Site":(464,["santa_fortuna"], ItemClassification.filler),
	"Agency Pickup - Santa Fortuna - Wine cellar":(465,["santa_fortuna"], ItemClassification.filler),
	"Hidden Stash - Santa Fortuna - Hostel":(466,["santa_fortuna"], ItemClassification.filler),
	"Hidden Stash - Santa Fortuna - Jungle":(467,["santa_fortuna"], ItemClassification.filler),
	"Hidden Stash - Santa Fortuna - Caves":(468,["santa_fortuna"], ItemClassification.filler),
	"Hidden Stash - Santa Fortuna - Fishing village":(469,["santa_fortuna"], ItemClassification.filler),
	"Agency Pickup - Isle of Sgail - Cistern":(470,["isle_of_sgail"], ItemClassification.filler),
	"Agency Pickup - Isle of Sgail - Morgue":(471,["isle_of_sgail"], ItemClassification.filler),
	"Agency Pickup - Isle of Sgail - Chapel":(472,["isle_of_sgail"], ItemClassification.filler),
	"Agency Pickup - Isle of Sgail - Hyperborean Showrooms":(473,["isle_of_sgail"], ItemClassification.filler),
	"Agency Pickup - Isle of Sgail - Gallery Stairwell":(474,["isle_of_sgail"], ItemClassification.filler),
	"Agency Pickup - Isle of Sgail - Gatehouse":(475,["isle_of_sgail"], ItemClassification.filler),
	"Agency Pickup - Isle of Sgail - Warehouse":(476,["isle_of_sgail"], ItemClassification.filler),
	"Agency Pickup - Isle of Sgail - Kitchen":(477,["isle_of_sgail"], ItemClassification.filler),
	"Agency Pickup - Mumbai - Mumbai Laundry":(478,["mumbai"], ItemClassification.filler),
	"Agency Pickup - Mumbai - Construction site":(479,["mumbai"], ItemClassification.filler),
	"Agency Pickup - Mumbai - Rooftop North":(480,["mumbai"], ItemClassification.filler),
	"Agency Pickup - Mumbai - Rooftop South":(481,["mumbai"], ItemClassification.filler),
	"Agency Pickup - Mumbai - Train yard":(482,["mumbai"], ItemClassification.filler),
	"Agency Pickup - Mumbai - The Hill":(483,["mumbai"], ItemClassification.filler),
	"Agency Pickup - Mumbai - Train Tracks":(484,["mumbai"], ItemClassification.filler),
	"Agency Pickup - Mumbai - Carpark":(485,["mumbai"], ItemClassification.filler),
	"Hidden Stash - Mumbai - Channel":(486,["mumbai"], ItemClassification.filler),
	"Hidden Stash - Mumbai - Homeless Tent":(487,["mumbai"], ItemClassification.filler),
	"Hidden Stash - Mumbai - Balcony Pot":(488,["mumbai"], ItemClassification.filler),
	"Hidden Stash - Mumbai - Old Tyre":(489,["mumbai"], ItemClassification.filler),
	"Hidden Stash - Mumbai - Washing Stalls":(490,["mumbai"], ItemClassification.filler),
	"Hidden Stash - Mumbai - Beach":(491,["mumbai"], ItemClassification.filler),
	"Hidden Stash - Mumbai - Shoeshop":(492,["mumbai"], ItemClassification.filler),
	"Hidden Stash - Mumbai - Slum Apartment":(493,["mumbai"], ItemClassification.filler),
	"Hidden Stash - Mumbai - Meat Market":(494,["mumbai"], ItemClassification.filler),
	"Hidden Stash - Mumbai - Streets on the Hill":(495,["mumbai"], ItemClassification.filler),
	"Hidden Stash - Mumbai - Pottery Market":(496,["mumbai"], ItemClassification.filler),
	"Hidden Stash - Mumbai - Rangan Tower":(497,["mumbai"], ItemClassification.filler),
	"Agency Pickup - Whittleton Creek - Bench":(498,["whittleton_creek"], ItemClassification.filler),
	"Agency Pickup - Whittleton Creek - Park Shed":(499,["whittleton_creek"], ItemClassification.filler),
	"Agency Pickup - Whittleton Creek - Hansons Basement":(500,["whittleton_creek"], ItemClassification.filler),
	"Agency Pickup - Whittleton Creek - Treehouse":(501,["whittleton_creek"], ItemClassification.filler),
	"Agency Pickup - Whittleton Creek - Cassidys Attic":(502,["whittleton_creek"], ItemClassification.filler),
	"Hidden Stash - Whittleton Creek - R. Cross Driveway":(503,["whittleton_creek"], ItemClassification.filler),
	"Hidden Stash - Whittleton Creek - Park":(504,["whittleton_creek"], ItemClassification.filler),
	"Hidden Stash - Whittleton Creek - Lewinskys House":(505,["whittleton_creek"], ItemClassification.filler),
	"Hidden Stash - Whittleton Creek - Creek Shed":(506,["whittleton_creek"], ItemClassification.filler),
	"Hidden Stash - Whittleton Creek - Helens Garage":(507,["whittleton_creek"], ItemClassification.filler),
	"Hidden Stash - Whittleton Creek - Battys Garden":(508,["whittleton_creek"], ItemClassification.filler),
	"Hidden Stash - Whittleton Creek - House For Sale":(509,["whittleton_creek"], ItemClassification.filler),
	"Hidden Stash - Whittleton Creek - Janus Kitchen":(510,["whittleton_creek"], ItemClassification.filler),
	"Starting Location - Sapienza - Portico":(511,["duplicate","sapienza"], ItemClassification.filler),
	"Starting Location - Bangkok - Hotel Front Terrace":(512,["unknown","bangkok"], ItemClassification.filler),
	"Starting Location - Colorado - Sniper Tower":(513,["unknown","colorado"], ItemClassification.filler),
	"Starting Location - Hokkaido - Infiltrating below the Helipad":(514,["hokkaido"], ItemClassification.filler),
	"Starting Location - Hokkaido - STARTING_LOCATION_HOKKAIDO_MAMUSHI":(515,["unsued","hokkaido"], ItemClassification.filler),
	"Explosive - RFID Triggered Explosive":(516,[], ItemClassification.filler),
	"Distraction - ICA Commendable Performance Coin":(517,[], ItemClassification.filler),
	"Distraction - ICA Superior Performance Coin":(518,[], ItemClassification.filler),
	"Distraction - ICA Outstanding Performance Coin":(519,[], ItemClassification.filler),
	"Distraction - ICA Commendable Service Coin":(520,[], ItemClassification.filler),
	"Distraction - ICA Outstanding Service Coin":(521,[], ItemClassification.filler),
	"Distraction - ICA Superior Service Coin":(522,[], ItemClassification.filler),
	"Distraction - Greedy Little Coin":(523,["H3_SINS_GREED"], ItemClassification.filler),
	"Distraction - Red-Tie Kiwi":(524,[], ItemClassification.filler),
	"Starting Location - Hawkes Bay - Boat":(525,["duplicate","hawkes_bay"], ItemClassification.filler),
	"Starting Location - Hawkes Bay - Beach":(526,["hawkes_bay"], ItemClassification.filler),
	"Starting Location - Hawkes Bay - STARTING_LOCATION_NEWZEALAND_HUT":(527,["unsued","hawkes_bay"], ItemClassification.filler),
	"Starting Location - Hawkes Bay - Office":(528,["hawkes_bay"], ItemClassification.filler),
	"Starting Location - Hawkes Bay - STARTING_LOCATION_NEWZEALAND_BED":(529,["unsued","hawkes_bay"], ItemClassification.filler),
	"Suit - The Jack-O'-Lantern Suit":(530,[], ItemClassification.filler),
	"Starting Location - Miami - Event Entrance":(531,["duplicate","miami"], ItemClassification.filler),
	"Starting Location - Miami - Dolphin Fountain":(532,["miami"], ItemClassification.filler),
	"Starting Location - Miami - Kronstadt Bayside Center":(533,["miami"], ItemClassification.filler),
	"Starting Location - Miami - Medical Area":(534,["miami"], ItemClassification.filler),
	"Starting Location - Miami - Stands":(535,["miami"], ItemClassification.filler),
	"Starting Location - Miami - STARTING_LOCATION_MIAMI_SAMBUCA_EXPO":(536,["unsued","miami"], ItemClassification.filler),
	"Starting Location - Miami - Marina":(537,["miami"], ItemClassification.filler),
	"Starting Location - Miami - Food Stand":(538,["miami"], ItemClassification.filler),
	"Starting Location - Miami - Podium":(539,["miami"], ItemClassification.filler),
	"Starting Location - Miami - Kowoon Pit":(540,["miami"], ItemClassification.filler),
	"Starting Location - Miami - Drivers' Lounge":(541,["miami"], ItemClassification.filler),
	"Starting Location - Miami - Overpass":(542,["miami"], ItemClassification.filler),
	"Starting Location - Santa Fortuna - Coca Fields":(543,["santa_fortuna"], ItemClassification.filler),
	"Starting Location - Santa Fortuna - Construction Site":(544,["santa_fortuna"], ItemClassification.filler),
	"Starting Location - Santa Fortuna - Submarine Cave":(545,["santa_fortuna"], ItemClassification.filler),
	"Starting Location - Santa Fortuna - Village Hostel":(546,["santa_fortuna"], ItemClassification.filler),
	"Starting Location - Santa Fortuna - Shaman's Hut":(547,["santa_fortuna"], ItemClassification.filler),
	"Starting Location - Santa Fortuna - Mansion Basement":(548,["santa_fortuna"], ItemClassification.filler),
	"Starting Location - Santa Fortuna - Village Bus Stop":(549,["duplicate","santa_fortuna"], ItemClassification.filler),
	"Starting Location - Santa Fortuna - Steel Bridge":(550,["unkown","santa_fortuna"], ItemClassification.filler),
	"Starting Location - Santa Fortuna - Village Bar":(551,["santa_fortuna"], ItemClassification.filler),
	"Starting Location - Santa Fortuna - STARTING_LOCATION_COLOMBIA_CALLUNA_COCAFIELD":(552,["unsued","santa_fortuna"], ItemClassification.filler),
	"Starting Location - Santa Fortuna - STARTING_LOCATION_COLOMBIA_OUTBREAK_FISHING_VILLAGE":(553,["unsued","santa_fortuna"], ItemClassification.filler),
	"Starting Location - Santa Fortuna - STARTING_LOCATION_COLOMBIA_OUTBREAK_VILLAGE":(554,["unsued","santa_fortuna"], ItemClassification.filler),
	"Starting Location - Santa Fortuna - STARTING_LOCATION_COLOMBIA_OUTBREAK_COCAFIELDS":(555,["unsued","santa_fortuna"], ItemClassification.filler),
	"Starting Location - Santa Fortuna - STARTING_LOCATION_COLOMBIA_OUTBREAK_CAVES":(556,["unsued","santa_fortuna"], ItemClassification.filler),
	"Starting Location - Mumbai - Main street":(557,["duplicate","mumbai"], ItemClassification.filler),
	"Starting Location - Mumbai - Outside Chawl":(558,["unkown","mumbai"], ItemClassification.filler),
	"Starting Location - Mumbai - Train":(559,["mumbai"], ItemClassification.filler),
	"Starting Location - Mumbai - Boat":(560,["mumbai"], ItemClassification.filler),
	"Starting Location - Mumbai - Taxi":(561,["mumbai"], ItemClassification.filler),
	"Starting Location - Mumbai - Skywalk":(562,["mumbai"], ItemClassification.filler),
	"Starting Location - Mumbai - Chawls":(563,["mumbai"], ItemClassification.filler),
	"Starting Location - Mumbai - Laundry":(564,["mumbai"], ItemClassification.filler),
	"Starting Location - Mumbai - Train yard":(565,["mumbai"], ItemClassification.filler),
	"Starting Location - Mumbai - Slums":(566,["mumbai"], ItemClassification.filler),
	"Starting Location - Mumbai - Photoshoot":(567,["mumbai"], ItemClassification.filler),
	"Starting Location - Mumbai - Barge":(568,["mumbai"], ItemClassification.filler),
	"Starting Location - Mumbai - Metal Forge":(569,["mumbai"], ItemClassification.filler),
	"Starting Location - Mumbai - Hill":(570,["mumbai"], ItemClassification.filler),
	"Starting Location - Whittleton Creek - Whittleton Creek":(571,["duplicate","whittleton_creek"], ItemClassification.filler),
	"Starting Location - Whittleton Creek - Garbage Removal":(572,["whittleton_creek"], ItemClassification.filler),
	"Starting Location - Whittleton Creek - Construction Area":(573,["whittleton_creek"], ItemClassification.filler),
	"Starting Location - Whittleton Creek - BBQ Party":(574,["whittleton_creek"], ItemClassification.filler),
	"Starting Location - Whittleton Creek - Suburb Sign":(575,["whittleton_creek"], ItemClassification.filler),
	"Starting Location - Whittleton Creek - Fumigation":(576,["whittleton_creek"], ItemClassification.filler),
	"Starting Location - Whittleton Creek - STARTING_LOCATION_NORTHAMERICA_SKUNK_OUTBREAK_HELICOPTER":(577,["unsued","whittleton_creek"], ItemClassification.filler),
	"Suit - The Arkian Tuxedo":(578,[], ItemClassification.filler),
	"Starting Location - Isle of Sgail - Harbor":(579,["duplicate","isle_of_sgail"], ItemClassification.filler),
	"Starting Location - Isle of Sgail - Keep":(580,["isle_of_sgail"], ItemClassification.filler),
	"Starting Location - Isle of Sgail - Chapel":(581,["isle_of_sgail"], ItemClassification.filler),
	"Starting Location - Isle of Sgail - Kitchens":(582,["isle_of_sgail"], ItemClassification.filler),
	"Starting Location - Isle of Sgail - Reception Area":(583,["isle_of_sgail"], ItemClassification.filler),
	"Starting Location - Isle of Sgail - Gallery":(584,["isle_of_sgail"], ItemClassification.filler),
	"Starting Location - Isle of Sgail - Architects' Lounge":(585,["isle_of_sgail"], ItemClassification.filler),
	"Starting Location - Isle of Sgail - Warehouse":(586,["isle_of_sgail"], ItemClassification.filler),
	"Starting Location - Isle of Sgail - STARTING_LOCATION_THE_ISLAND_MAGPIE_LOTUS":(587,["unsued","isle_of_sgail"], ItemClassification.filler),
	"Suitcase - ICA Briefcase":(588,[], ItemClassification.useful),
	"Suitcase - Toolbox":(589,[], ItemClassification.filler),
	"Suitcase - ICA Executive Briefcase MK II":(590,[], ItemClassification.filler),
	"Suitcase - Artic Toolbox":(591,["H2_WINTER_SPORTS"], ItemClassification.filler),
	"Suitcase - Black Leather Briefcase":(592,[], ItemClassification.filler),
	"Suitcase - ICA Briefcase MK III":(593,[], ItemClassification.filler),
	"Suitcase - Aluminum Travel Briefcase":(594,[], ItemClassification.filler),
	"Suitcase - Aluminum Travel Briefcase (H3)":(595,[], ItemClassification.filler),
	"Suitcase - ICA Executive Briefcase":(596,["H2_EXECUTIVE"], ItemClassification.filler),
	"Suitcase - Orange Pinstripe Briefcase":(597,[], ItemClassification.filler),
	"Suitcase - Golden Briefcase":(598,["H3_DELUXE_PACK"], ItemClassification.filler),
	"Suitcase - Hunters Breifcase":(599,["H3_DELUXE_PACK"], ItemClassification.filler),
	"Suitcase - Chinese Briefase":(600,["H3_DELUXE_PACK"], ItemClassification.filler),
	"Suitcase - Premiere White Briefcase":(601,["H3_TRINITY"], ItemClassification.filler),
	"Suitcase - Crimson Red Briefcase":(602,["H3_TRINITY"], ItemClassification.filler),
	"Suitcase - Ultimate Black Briefcase":(603,["H3_TRINITY"], ItemClassification.filler),
	"Suitcase - The Club Boom 12\" Flightcase":(604,["H3_ET_TOMORROWLAND"], ItemClassification.filler),
	"Suitcase - Siger 300 Sniper Case":(605,[], ItemClassification.filler),
	"Starting Location - STARTING_LOCATION_MANTIS_OUTBREAK_ROOF":(606,["unsued"], ItemClassification.filler),
	"Starting Location - New York - Bank Entrance":(607,["duplicate","new_york"], ItemClassification.filler),
	"Starting Location - New York - Investment Floor":(608,["new_york"], ItemClassification.filler),
	"Starting Location - New York - First Floor Mezzanine":(609,["new_york"], ItemClassification.filler),
	"Starting Location - New York - Deposit Box Room":(610,["new_york"], ItemClassification.filler),
	"Starting Location - New York - Garage":(611,["new_york"], ItemClassification.filler),
	"Starting Location - New York - STARTING_LOCATION_GREEDY_RACCOON_DANDELION_GARAGE_ENTRANCE":(612,["unsued","new_york"], ItemClassification.filler),
	"Starting Location - New York - Audit Hall":(613,["new_york"], ItemClassification.filler),
	"Agency Pickup - New York - Vault's Loading Bay":(614,["new_york"], ItemClassification.filler),
	"Agency Pickup - New York - First Floor Janitor Room":(615,["new_york"], ItemClassification.filler),
	"Hidden Stash - New York - Deposit Box":(616,["new_york"], ItemClassification.filler),
	"Hidden Stash - New York - Second Floor Bathroom":(617,["new_york"], ItemClassification.filler),
	"Agency Pickup - New York - Executive Floor":(618,["new_york"], ItemClassification.filler),
	"Hidden Stash - New York - Waiting Area Bathroom":(619,["new_york"], ItemClassification.filler),
	"Starting Location - Haven Island - Resort Pier":(620,["haven_island"], ItemClassification.filler),
	"Starting Location - Haven Island - Shark Hut":(621,["duplicate","haven_island"], ItemClassification.filler),
	"Starting Location - Haven Island - Resort Pool Area":(622,["haven_island"], ItemClassification.filler),
	"Starting Location - Haven Island - Resort Gym":(623,["haven_island"], ItemClassification.filler),
	"Starting Location - Haven Island - Restaurant's Kitchen":(624,["haven_island"], ItemClassification.filler),
	"Starting Location - Haven Island - Private Villa Pier":(625,["haven_island"], ItemClassification.filler),
	"Hidden Stash - Haven Island - Buried In Sand":(626,["haven_island"], ItemClassification.filler),
	"Hidden Stash - Haven Island - Laundry Room":(627,["haven_island"], ItemClassification.filler),
	"Hidden Stash - Haven Island - Restaurant Storage Room":(628,["haven_island"], ItemClassification.filler),
	"Agency Pickup - Haven Island - Shark Hut":(629,["haven_island"], ItemClassification.filler),
	"Agency Pickup - Haven Island - Villa Beach Storage Area":(630,["haven_island"], ItemClassification.filler),
	"Agency Pickup - Haven Island - Security Hut":(631,["haven_island"], ItemClassification.filler),
	"Hidden Stash - Haven Island - Changing Room":(632,["haven_island"], ItemClassification.filler),
	"Hidden Stash - Haven Island - Villa Bathroom":(633,["haven_island"], ItemClassification.filler),
	"Hidden Stash - Haven Island - Underground Storage Room":(634,["haven_island"], ItemClassification.filler),
	"Suit - The Buccaneer":(635,["H2_STINGRAY"], ItemClassification.filler),
	"Starting Location - STARTING_LOCATION_OPULENT_ARCTICTHYME_PIRATE":(636,["unsued"], ItemClassification.filler),
	"Suit - The Devil's Own":(637,["H3_DELUXE_PACK"], ItemClassification.filler),
	"Suit - Formal Hunting Attire":(638,["H3_DELUXE_PACK"], ItemClassification.filler),
	"Suit - The Black Dragon":(639,["H3_DELUXE_PACK"], ItemClassification.filler),
	"Suit - Guru Suit":(640,["H3_DELUXE_PACK"], ItemClassification.filler),
	"Suit - The Yellow Rabbit":(641,[], ItemClassification.filler),
	"Suit - The White Shadow":(642,["H3_DELUXE_PACK"], ItemClassification.filler),
	"Suit - The Butcher":(643,[], ItemClassification.filler),
	"Suit - The Big, Bad Wolf Suit":(644,[], ItemClassification.filler),
	"Suit - The Strait Jacket":(645,["H3_DELUXE_PACK"], ItemClassification.filler),
	"Suit - The Raver":(646,[], ItemClassification.filler),
	"Suit - TOKEN_OUTFIT_HERO_EASTER_RAVER_BUNNY_SUIT":(647,["unknown"], ItemClassification.filler),
	"Suit - The Ruby Rude Track Suit":(648,[], ItemClassification.filler),
	"Suit - The Neon Ninja Suit":(649,[], ItemClassification.filler),
	"Suit - The Lucky Ducky Suit":(650,[], ItemClassification.filler),
	"Suit - The Sandman Suit":(651,[], ItemClassification.filler),
	"Suit - Super Fan":(652,[], ItemClassification.filler),
	"Suit - Plague Doctor":(653,[], ItemClassification.filler),
	"Suit - Summer Sightseeing Suit With Gloves":(654,[], ItemClassification.filler),
	"Suit - Agent 17's Signature Suit":(655,[], ItemClassification.filler),
	"Suit - The Codename 47 Suit":(656,[], ItemClassification.filler),
	"Suit - The Cozy Christmas Suit":(657,[], ItemClassification.filler),
	"Suit - The Rapacious Suit":(658,["H3_SINS_GREED"], ItemClassification.filler),
	"Suit - The Narcissus Suit":(659,["H3_SINS_PRIDE"], ItemClassification.filler),
	"Suit - The Lotophage Suit":(660,["H3_SINS_SLOTH"], ItemClassification.filler),
	"Suit - The Scarlet Suit":(661,["H3_SINS_LUST"], ItemClassification.filler),
	"Suit - The Profligacy Suit":(662,["H3_SINS_GLUTTONLY"], ItemClassification.filler),
	"Suit - The Temper Suit":(663,["H3_SINS_WRATH"], ItemClassification.filler),
	"Suit - The Odium Suit":(664,["H3_SINS_ENVY"], ItemClassification.filler),
	"Suit - Premiere White Suit":(665,["H3_TRINITY"], ItemClassification.filler),
	"Suit - Crimson Red Suit":(666,["H3_TRINITY"], ItemClassification.filler),
	"Suit - Ultimate Black Suit":(667,["H3_TRINITY"], ItemClassification.filler),
	"Suit - The Blue Streak Suit":(668,[], ItemClassification.filler),
	"Suit - White Sunset Suit":(669,[], ItemClassification.filler),
	"Suit - The Green Streak Suit":(670,[], ItemClassification.filler),
	"Suit - The Black Streak Suit":(671,[], ItemClassification.filler),
	"Suit - The Purple Streak Suit":(672,[], ItemClassification.filler),
	"Suit - Solstice Suit":(673,["unknown"], ItemClassification.filler),
	"Suit - Ashen Suit With Gloves":(674,[], ItemClassification.filler),
	"Suit - The Public Enemy Suit":(675,[], ItemClassification.filler),
	"Suit - Classic Cut Long Coat Suit With Gloves":(676,[], ItemClassification.filler),
	"Suit - Number Six With Gloves":(677,[], ItemClassification.filler),
	"Suit - Rave On Suit":(678,[], ItemClassification.filler),
	"Suit - Polar Survival Suit":(679,["H2_LEGACY"], ItemClassification.filler),
	"Suit - Neon City Suit With Gloves":(680,[], ItemClassification.filler),
	"Suit - Black & White Tuxedo Set With Gloves":(681,[], ItemClassification.filler),
	"Suit - Subject 47":(682,[], ItemClassification.filler),
	"Suit - TOKEN_OUTFIT_HERO_GECKO_SUIT":(683,["unknown"], ItemClassification.filler),
	"Starting Location - Dubai - Burj Al-Ghazali Exterior":(684,["duplicate","dubai"], ItemClassification.filler),
	"Starting Location - Dubai - STARTING_LOCATION_GOLDEN_GECKO_OUTSIDE_DEFAULT_COMMENTARY":(685,["H3_EXPANSION","dubai"], ItemClassification.filler),
	"Starting Location - Dubai - Atrium Lobby":(686,["dubai"], ItemClassification.useful),
	"Starting Location - Dubai - Meeting Room":(687,["dubai"], ItemClassification.filler),
	"Starting Location - Dubai - Art Installation":(688,["dubai"], ItemClassification.filler),
	"Starting Location - Dubai - Guard Room":(689,["dubai"], ItemClassification.filler),
	"Starting Location - Dubai - Penthouse":(690,["dubai"], ItemClassification.filler),
	"Starting Location - Dubai - STARTING_LOCATION_GOLDEN_ANGELICA_GOLDBAR":(691,["unsued","dubai"], ItemClassification.filler),
	"Starting Location - Dubai - STARTING_LOCATION_GOLDEN_GIBSON_INSIDE_DEFAULT":(692,["unsued","dubai"], ItemClassification.filler),
	"Agency Pickup - Dubai - Maintenance Room":(693,["dubai"], ItemClassification.filler),
	"Agency Pickup - Dubai - Penthouse Supply Room":(694,["dubai"], ItemClassification.filler),
	"Agency Pickup - Dubai - Art Backstage Balcony":(695,["dubai"], ItemClassification.filler),
	"Agency Pickup - Dubai - Penthouse Ventilation Area":(696,["dubai"], ItemClassification.filler),
	"Hidden Stash - Dubai - Kitchen":(697,["dubai"], ItemClassification.filler),
	"Hidden Stash - Dubai - Laundry Room":(698,["dubai"], ItemClassification.filler),
	"Hidden Stash - Dubai - Atrium Toilet":(699,["dubai"], ItemClassification.filler),
	"Suit - TOKEN_OUTFIT_ANCESTRAL_HERO_ANCESTRALSUIT":(700,["unknown"], ItemClassification.filler),
	"Suit - TOKEN_OUTFIT_ANCESTRAL_HERO_SMOOTHSNAKESUIT":(701,["unknown"], ItemClassification.filler),
	"Starting Location - Dartmoor - Main Road":(702,["duplicate","dartmoor"], ItemClassification.filler),
	"Starting Location - Dartmoor - Directors Commentary - Mission Introduction":(703,["H3_EXPANSION","dartmoor"], ItemClassification.filler),
	"Starting Location - Dartmoor - Main Road (Skipped)":(704,["dartmoor"], ItemClassification.filler),
	"Starting Location - Dartmoor - Behind Mansion":(705,["dartmoor"], ItemClassification.filler),
	"Starting Location - Dartmoor - Behind Mansion (Skipped)":(706,["dartmoor"], ItemClassification.filler),
	"Starting Location - Dartmoor - Garden":(707,["dartmoor"], ItemClassification.filler),
	"Starting Location - Dartmoor - Library":(708,["dartmoor"], ItemClassification.filler),
	"Starting Location - Dartmoor - Staff Room":(709,["dartmoor"], ItemClassification.filler),
	"Starting Location - Dartmoor - Zachery's Bedroom":(710,["dartmoor"], ItemClassification.filler),
	"Starting Location - Dartmoor - STARTING_LOCATION_ANCESTRAL_FERN_BEHINDMANSION_HUNTINGSUIT_B":(711,["unsued","dartmoor"], ItemClassification.filler),
	"Starting Location - Dartmoor - STARTING_LOCATION_ANCESTRAL_SMOOTHSNAKE_FRONTMANSION_SUIT":(712,["unsued","dartmoor"], ItemClassification.filler),
	"Starting Location - Dartmoor - STARTING_LOCATION_ANCESTRAL_SMOOTHSNAKE_FRONTMANSION_SUIT_B":(713,["unsued","dartmoor"], ItemClassification.filler),
	"Starting Location - STARTING_LOCATION_HOLLYHOCK_DEFAULT":(714,["unsued"], ItemClassification.filler),
	"Hidden Stash - Dartmoor - Deliveries":(715,["dartmoor"], ItemClassification.filler),
	"Hidden Stash - Dartmoor - Library":(716,["dartmoor"], ItemClassification.filler),
	"Agency Pickup - Dartmoor - Graveyard":(717,["dartmoor"], ItemClassification.filler),
	"Agency Pickup - Dartmoor - Changing room":(718,["dartmoor"], ItemClassification.filler),
	"Hidden Stash - Dartmoor - Greenhouse":(719,["dartmoor"], ItemClassification.filler),
	"Agency Pickup - Dartmoor - Hallway":(720,["dartmoor"], ItemClassification.filler),
	"Agency Pickup - Dartmoor - Bathroom":(721,["dartmoor"], ItemClassification.filler),
	"Hidden Stash - Dartmoor - Laundry Room":(722,["dartmoor"], ItemClassification.filler),
	"Suit - TOKEN_OUTFIT_EDGY_HERO_EDGYSUIT":(723,["unknown"], ItemClassification.filler),
	"Starting Location - Berlin - Bus Stop":(724,["duplicate","berlin"], ItemClassification.filler),
	"Starting Location - Berlin - Directors Commentary - Mission Introduction":(725,["H3_EXPANSION","berlin"], ItemClassification.filler),
	"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_DEFAULT_CONTRACTCREATION":(726,["unsued","berlin"], ItemClassification.filler),
	"Starting Location - Berlin - Radio Tower":(727,["berlin"], ItemClassification.filler),
	"Starting Location - Berlin - Biker Hangout":(728,["berlin"], ItemClassification.filler),
	"Starting Location - Berlin - Projection Bar":(729,["berlin"], ItemClassification.filler),
	"Starting Location - Berlin - DJ Booth":(730,["berlin"], ItemClassification.filler),
	"Starting Location - Berlin - Chill Out":(731,["berlin"], ItemClassification.filler),
	"Starting Location - Berlin - Club Entrance":(732,["berlin"], ItemClassification.useful),
	"Starting Location - Berlin - STARTING_LOCATION_EDGY_RADLER_CLUB_ENTRANCE":(733,["unsued","berlin"], ItemClassification.filler),
	"Starting Location - Berlin - STARTING_LOCATION_EDGY_TOMORROWLAND_CLUB_ENTRANCE":(734,["unsued","berlin"], ItemClassification.filler),
	"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_NIGHTPHLOX_B1_BAR":(735,["unsued","berlin"], ItemClassification.filler),
	"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_NIGHTPHLOX_CLUB_ENTRANCE":(736,["unsued","berlin"], ItemClassification.filler),
	"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_NIGHTPHLOX_CHILLOUT_AREA":(737,["unsued","berlin"], ItemClassification.filler),
	"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_NIGHTPHLOX_DJ_BOOTH":(738,["unsued","berlin"], ItemClassification.filler),
	"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_GRASSSNAKE_FORRESTEDGE":(739,["unsued","berlin"], ItemClassification.filler),
	"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_GRASSSNAKE_EVENTAREA":(740,["unsued","berlin"], ItemClassification.filler),
	"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_CORNFLOWER_LEVEL1":(741,["unsued","berlin"], ItemClassification.filler),
	"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_CORNFLOWER_LEVEL2":(742,["unsued","berlin"], ItemClassification.filler),
	"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_CORNFLOWER_LEVEL3":(743,["unsued","berlin"], ItemClassification.filler),
	"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_AMBROSIA":(744,["unsued","berlin"], ItemClassification.filler),
	"Agency Pickup - Berlin - Entrance Staff Room":(745,["berlin"], ItemClassification.filler),
	"Agency Pickup - Berlin - Chill-Out Stff Trailer":(746,["berlin"], ItemClassification.filler),
	"Agency Pickup - Berlin - Overpass":(747,["berlin"], ItemClassification.filler),
	"Agency Pickup - Berlin - Basement Boiler Room":(748,["berlin"], ItemClassification.filler),
	"Agency Pickup - Berlin - Skylight Access":(749,["berlin"], ItemClassification.filler),
	"Hidden Stash - Berlin - Projection Bar":(750,["berlin"], ItemClassification.filler),
	"Hidden Stash - Berlin - Basement Toilet":(751,["berlin"], ItemClassification.filler),
	"Hidden Stash - Berlin - Biker Garage":(752,["berlin"], ItemClassification.filler),
	"Suit - TOKEN_OUTFIT_WET_HERO_WETSUIT":(753,["unknown"], ItemClassification.filler),
	"Agency Pickup - Chongqing - Facility Maintenance Tunnel":(754,["chongqing"], ItemClassification.filler),
	"Agency Pickup - Chongqing - Arcade":(755,["chongqing"], ItemClassification.filler),
	"Agency Pickup - Chongqing - Corridor":(756,["chongqing"], ItemClassification.filler),
	"Agency Pickup - Chongqing - Side Alley":(757,["chongqing"], ItemClassification.filler),
	"Agency Pickup - Chongqing - Apartment":(758,["chongqing"], ItemClassification.filler),
	"Hidden Stash - Chongqing - The Laundry":(759,["chongqing"], ItemClassification.filler),
	"Hidden Stash - Chongqing - Facility Rooftop":(760,["chongqing"], ItemClassification.filler),
	"Hidden Stash - Chongqing - Facility Ventilation Room":(761,["chongqing"], ItemClassification.filler),
	"Hidden Stash - Chongqing - Facility Server Supply Room":(762,["chongqing"], ItemClassification.filler),
	"Hidden Stash - Chongqing - Restaurant Back Stairwell":(763,["chongqing"], ItemClassification.filler),
	"Starting Location - Chongqing - Train Station":(764,["duplicate","chongqing"], ItemClassification.filler),
	"Starting Location - Chongqing - Directors Commentary - Mission Introduction":(765,["H3_EXPANSION","chongqing"], ItemClassification.filler),
	"Starting Location - Chongqing - Restaurant Kitchen":(766,["chongqing"], ItemClassification.filler),
	"Starting Location - Chongqing - Facility Rooftop":(767,["chongqing"], ItemClassification.filler),
	"Starting Location - Chongqing - River-side Walkway":(768,["chongqing"], ItemClassification.useful),
	"Starting Location - Chongqing - Balcony":(769,["chongqing"], ItemClassification.filler),
	"Starting Location - Chongqing - The Block":(770,["chongqing"], ItemClassification.filler),
	"Starting Location - Chongqing - Facility Locker Room":(771,["chongqing"], ItemClassification.filler),
	"Starting Location - Chongqing - STARTING_LOCATION_WET_LAMBIC_DEFAULT":(772,["unsued","chongqing"], ItemClassification.filler),
	"Suit - TOKEN_OUTFIT_ELEGANT_HERO_LLAMASUIT":(773,["unknown"], ItemClassification.filler),
	"Starting Location - Mendoza - Winery Viewpoint":(774,["duplicate","mendoza"], ItemClassification.filler),
	"Starting Location - Mendoza - STARTING_LOCATION_ELEGANT_NODIANA_DEFAULT_SUIT":(775,["unsued","mendoza"], ItemClassification.filler),
	"Starting Location - Mendoza - Directors Commentary - Mission Introduction":(776,["H3_EXPANSION","mendoza"], ItemClassification.filler),
	"Starting Location - Mendoza - Parking Lot":(777,["mendoza"], ItemClassification.filler),
	"Starting Location - Mendoza - STARTING_LOCATION_ELEGANT_LLAMA_JACARANDA_DOCKS":(778,["unsued","mendoza"], ItemClassification.filler),
	"Starting Location - Mendoza - STARTING_LOCATION_ELEGANT_LLAMA_FRANGIPANI_PARKING":(779,["unsued","mendoza"], ItemClassification.filler),
	"Hidden Stash - Mendoza - Boathouse":(780,["mendoza"], ItemClassification.filler),
	"Hidden Stash - Mendoza - Worker's Bathroom":(781,["mendoza"], ItemClassification.filler),
	"Starting Location - Mendoza - Tasting Room":(782,["mendoza"], ItemClassification.filler),
	"Agency Pickup - Mendoza - Barrel Room":(783,["mendoza"], ItemClassification.filler),
	"Hidden Stash - Mendoza - Shrine":(784,["mendoza"], ItemClassification.filler),
	"Hidden Stash - Mendoza - Cinema":(785,["mendoza"], ItemClassification.filler),
	"Starting Location - Mendoza - Shrine":(786,["mendoza"], ItemClassification.filler),
	"Agency Pickup - Mendoza - Steel Tanks":(787,["mendoza"], ItemClassification.filler),
	"Starting Location - Mendoza - Sniper Spot":(788,["mendoza"], ItemClassification.filler),
	"Agency Pickup - Mendoza - Villa Attic":(789,["mendoza"], ItemClassification.filler),
	"Starting Location - Mendoza - Vineyard":(790,["mendoza"], ItemClassification.filler),
	"Starting Location - Mendoza - Dining Area":(791,["mendoza"], ItemClassification.filler),
	"Agency Pickup - Mendoza - Grapefield Shed":(792,["mendoza"], ItemClassification.filler),
	"Hidden Stash - Mendoza - Dance Floor":(793,["mendoza"], ItemClassification.filler),
	"Hidden Stash - Mendoza - Villa Basement":(794,["mendoza"], ItemClassification.filler),
	"Suit - TOKEN_OUTFIT_TRAPPED_WOLVERINE_SUIT":(795,["unused"], ItemClassification.filler),
	"Starting Location - Carpathian Mountains - Reflection":(796,["duplicate","carpathian_mountains"], ItemClassification.filler),
	"Starting Location - Carpathian Mountains - Laboratory":(797,["carpathian_mountains"], ItemClassification.useful),
	"Starting Location - Carpathian Mountains - Outdoors":(798,["carpathian_mountains"], ItemClassification.filler),
	"Suit - Guerilla Wetsuit":(799,[], ItemClassification.filler),
	"Starting Location - Ambrose Island - Western Beach":(800,["duplicate","ambrose_island"], ItemClassification.filler),
	"Starting Location - Ambrose Island - Shrine":(801,["ambrose_island"], ItemClassification.filler),
	"Starting Location - Ambrose Island - Central Social Hub":(802,["ambrose_island"], ItemClassification.filler),
	"Starting Location - Ambrose Island - Stilt Village":(803,["ambrose_island"], ItemClassification.filler),
	"Starting Location - Ambrose Island - Militia Camp":(804,["ambrose_island"], ItemClassification.filler),
	"Starting Location - Ambrose Island - Pirate Camp":(805,["ambrose_island"], ItemClassification.filler),
	"Hidden Stash - Ambrose Island - Shrine":(806,["ambrose_island"], ItemClassification.filler),
	"Hidden Stash - Ambrose Island - Big Tree":(807,["ambrose_island"], ItemClassification.filler),
	"Hidden Stash - Ambrose Island - Farah's Place":(808,["ambrose_island"], ItemClassification.filler),
	"Agency Pickup - Ambrose Island - Colonial Ruins":(809,["ambrose_island"], ItemClassification.filler),
	"Agency Pickup - Ambrose Island - Green Container":(810,["ambrose_island"], ItemClassification.filler),
	"Agency Pickup - Ambrose Island - Boat Cradle":(811,["ambrose_island"], ItemClassification.filler),
	"Agency Pickup - Ambrose Island - Food Storage":(812,["ambrose_island"], ItemClassification.filler),
	"Pistol - The Ornamental Pistol":(813,["LOCATION_GOLDEN"], ItemClassification.filler),
	"Shotgun - The Ornamental Shotgun":(814,["LOCATION_GOLDEN"], ItemClassification.filler),
	"Assault Rifle - The Ornamental Assault Rifle":(815,["LOCATION_GOLDEN"], ItemClassification.filler),
	"SMG - The Ornamental SMG":(816,["LOCATION_GOLDEN"], ItemClassification.filler),
	"Sniper - The Ornamental Sniper Rifle":(817,["LOCATION_GOLDEN"], ItemClassification.filler),
	"Melee - The Ornamental Katana":(818,["LOCATION_GOLDEN"], ItemClassification.filler),
	"Suit - The Golden Contender Suit":(819,["LOCATION_GOLDEN"], ItemClassification.filler),
	"Pistol - The Scrap Gun":(820,["H3_VANITY_MAKESHIFTSCRAP"], ItemClassification.filler),
	"Shotgun - The Makeshift Scrap Shotgun":(821,["H3_VANITY_MAKESHIFTSCRAP"], ItemClassification.filler),
	"Assault Rifle - The Makeshift Scrap Assault Rifle":(822,["H3_VANITY_MAKESHIFTSCRAP"], ItemClassification.filler),
	"SMG - The Scrap SMG":(823,["H3_VANITY_MAKESHIFTSCRAP"], ItemClassification.filler),
	"Sniper - The Scrappy Sniper Rifle":(824,["H3_VANITY_MAKESHIFTSCRAP"], ItemClassification.filler),
	"Melee - The Makeshift Katana":(825,["H3_VANITY_MAKESHIFTSCRAP"], ItemClassification.filler),
	"Suit - The Scrap Poncho Suit":(826,["H3_VANITY_MAKESHIFTSCRAP"], ItemClassification.filler),
	"Pistol - The Concrete Bunny Pistol":(827,["H3_VANITY_CONCRETEART"], ItemClassification.filler),
	"Shotgun - The Concrete Shotgun":(828,["H3_VANITY_CONCRETEART"], ItemClassification.filler),
	"Assault Rifle - The Concrete Assault Rifle":(829,["H3_VANITY_CONCRETEART"], ItemClassification.filler),
	"SMG - The Shark SMG":(830,["H3_VANITY_CONCRETEART"], ItemClassification.filler),
	"Sniper - The Concrete Sniper Rifle":(831,["H3_VANITY_CONCRETEART"], ItemClassification.filler),
	"Melee - The Concrete Bat":(832,["H3_VANITY_CONCRETEART"], ItemClassification.filler),
	"Suit - The Graffiti Hoody Suit":(833,["H3_VANITY_CONCRETEART"], ItemClassification.filler),
	"Suit - The Master Freelancer Suit":(834,[], ItemClassification.filler),
	"Suit - The Gauze Suit":(835,[], ItemClassification.filler),
	"Suit - The Black Bruiser Suit":(836,[], ItemClassification.filler),
	"Suit - The Sniper Challange Suit":(837,[], ItemClassification.filler),
	"Suit - Trendy Tourist Suit":(838,[], ItemClassification.filler),
	"Pistol - The Ancestral Pistol":(839,["LOCATION_GOLDEN"], ItemClassification.filler),
	"Shotgun - The Ancestral Shotgun":(840,["LOCATION_GOLDEN"], ItemClassification.filler),
	"Assault Rifle - The Ancestral Assault Rifle":(841,["LOCATION_GOLDEN"], ItemClassification.filler),
	"Sniper - The Ancestral Sniper Rifle":(842,["LOCATION_GOLDEN"], ItemClassification.filler),
	"Melee - The Ancestral Knife":(843,["LOCATION_GOLDEN"], ItemClassification.filler),
	"Explosive - PROP_DEVICE_REMOTE_EXPLOSIVE_ANCESTRAL":(844,["unknown"], ItemClassification.filler),
	"Suit - The Ancestral Hunter Suit":(845,["LOCATION_GOLDEN"], ItemClassification.filler),
	"Suit - The Ephemeral Suit":(846,[], ItemClassification.filler),
	"Suit - The Ephemeral Suit with Eye Patch":(847,["H3_ET_SAMBUCA"], ItemClassification.filler),
	"Poision - Blue Easter Egg":(848,[], ItemClassification.filler),
	"Melee - Durian":(849,[], ItemClassification.filler),
	"Melee - Unicorn Horn":(850,[], ItemClassification.filler),
	"Melee - Pinot Noir":(851,[], ItemClassification.filler),
	"Explosive - ICA Impact Explosive":(852,[], ItemClassification.filler),
	"Melee - Burial Dagger":(853,[], ItemClassification.filler),
	"Shotgun - Golden Sawed-Off Bartoli 12G":(854,[], ItemClassification.filler),
	"Explosive - Kronstadt Explosive Pen":(855,["H3_ET_SAMBUCA"], ItemClassification.filler),
	"Explosive - Kronstadt Mini Flash Robo XOI-2900":(856,["H3_ET_SAMBUCA"], ItemClassification.filler),
	"Melee - Kronstadt IOI-1998X Surround Earphones":(857,["H3_ET_SAMBUCA"], ItemClassification.filler),
	"Explosive - The Purple Streak Explosive Duck":(858,[], ItemClassification.filler),
	"Suit - The Disruptor MMA Suit":(859,[], ItemClassification.filler),
	"Suit - The Disruptor Fur Coat":(860,["H3_ET_PENICILLIN"], ItemClassification.filler),
	"Melee - The Disruptor Resistance Band":(861,["H3_ET_PENICILLIN"], ItemClassification.filler),
	"Melee - The Disruptor Kettlebell":(862,["H3_ET_PENICILLIN"], ItemClassification.filler),
	"Melee - The Disruptor Cane":(863,["H3_ET_PENICILLIN"], ItemClassification.filler),
	"Tool - ICA Proximity Micro Taser":(864,[], ItemClassification.filler),
	"Tool - Oil Canister":(865,[], ItemClassification.filler),
	"Suitcase - The Purple Streak ICA Briefcase":(866,[], ItemClassification.filler),
	"Tool - RFID Triggered Taser":(867,[], ItemClassification.filler),
	"Tool - Proximity EMP Charge":(868,[], ItemClassification.filler),
	"Explosive - Proximity Lucky Cat Figurine":(869,[], ItemClassification.filler),
	"Pistol - The Purple Streak ICA19 Classic Baller":(870,[], ItemClassification.filler),
	"SMG - The Splitter SMG":(871,["H3_ET_LAMBIC"], ItemClassification.filler),
	"Melee - The Splitter Kukri Knife ":(872,["H3_ET_LAMBIC"], ItemClassification.filler),
	"Melee - The \“Good Quark Vol. 3\” VHS Tape":(873,["H3_ET_LAMBIC"], ItemClassification.filler),
	"Suit - The Splitter Boxer Suit":(874,["H3_ET_LAMBIC"], ItemClassification.filler),
	"Suit - The Purple Streak Boxer Suit":(875,[], ItemClassification.filler),
	"Suit - The Splitter Suit":(876,[], ItemClassification.filler),
	"Suit - The Krampus Little Helper Suit":(877,[], ItemClassification.filler),
	"Distraction - The Purple Streak Coin":(878,[], ItemClassification.filler),
	"Suit - The Egg Hunt Suit":(879,[], ItemClassification.filler),
	"Pistol - The Cherry Blossom Baller":(880,[], ItemClassification.filler),
	"Melee - The Sapienza FA-Sanguine Boot":(881,[], ItemClassification.filler),
	"Tool - The Golden Wrench":(882,["H3_SIGNATURE_PACK"], ItemClassification.filler),
	"Explosive - The Dino Duck":(883,["H3_QUACK_PACK"], ItemClassification.filler),
	"Poision - Red Mushroom":(884,["H3_SIGNATURE_PACK"], ItemClassification.filler),
	"Suit - The Fire 47 Suit":(885,["H3_SIGNATURE_PACK"], ItemClassification.filler),
	"Suit - The Cerise Suit":(886,["H3_SIGNATURE_PACK"], ItemClassification.filler),
	"Suit - The Mansion Suit":(887,["H3_QUACK_PACK"], ItemClassification.filler),
	"Explosive - The Neon Duck":(888,[], ItemClassification.filler),
	"Explosive - The IOI Showcase Duck":(889,[], ItemClassification.filler),
	"Suit - The Purple Streak Swimwear Suit":(890,[], ItemClassification.filler),
	"Suit - The Pastel Suit":(891,[], ItemClassification.filler),
	"Melee - The Purple Streak Fiber Wire":(892,[], ItemClassification.filler),
	"Suit - The Banker King of Cards Suit":(893,["H3_ET_FRENCHMARTINI"], ItemClassification.filler),
	"Suit - The Banker Suit":(894,[], ItemClassification.filler),
	"Distraction - The \"Casino Monarchique\" Chip (100.000)":(895,[], ItemClassification.filler),
	"Melee - The Banker Rope":(896,["H3_ET_FRENCHMARTINI"], ItemClassification.filler),
	"Distraction - The \"Casino Monarchique\" Chip (1.000.000)":(897,["H3_ET_FRENCHMARTINI"], ItemClassification.filler),
	"Pistol - The Banker Silenced Pistol":(898,["H3_ET_FRENCHMARTINI"], ItemClassification.filler),
	"Explosive - The Party Cracker":(899,[], ItemClassification.filler),
	"Melee - Cocktail Shaker":(900,[], ItemClassification.filler) 
}

item_table["Contract Piece"] = (1000,"contract_mode",ItemClassification.progression)