from BaseClasses import Item, ItemClassification

class HitmanItem(Item):
    game: str = "HITMAN World of Assasination"

base_id = 2023011800

item_table= { # id, requirement, classifier
"Pistol - The Taunton Dart Gun":(244,"DELUXE", ItemClassification.filler),
"SMG - DAK Gold Covert":(262,"DELUXE", ItemClassification.filler),
"Sniper - The Golden Dragon":(263,"DELUXE", ItemClassification.filler),
"Sniper - Siger 300 Arctic":(277,"DELUXE", ItemClassification.filler),
"Shotgun - Bartoli Hunting Shotgun Deluxe":(278,"DELUXE", ItemClassification.filler),
"Suitcase - Chinese Briefase":(281,"DELUXE", ItemClassification.filler),
"Suitcase - Golden Briefcase":(283,"DELUXE", ItemClassification.filler),
"Suitcase - Hunters Breifcase":(284,"DELUXE", ItemClassification.filler),
"Poision - Guru's Pen Syringe Emetic":(362,"DELUXE", ItemClassification.filler),
"Tool - Guru's Emetic Grenade":(377,"DELUXE", ItemClassification.filler),
"Melee - White Katana":(411,"DELUXE", ItemClassification.filler),
"Melee - The Straitjacket Belt":(413,"DELUXE", ItemClassification.filler),
"Suit - The Strait Jacket":(701,"DELUXE", ItemClassification.filler),
"Suit - The Black Dragon":(708,"DELUXE", ItemClassification.filler),
"Suit - Guru Suit":(722,"DELUXE", ItemClassification.filler),
"Suit - Formal Hunting Attire":(725,"DELUXE", ItemClassification.filler),
"Suit - The White Shadow":(743,"DELUXE", ItemClassification.filler),
"Suit - The Devil's Own":(719,"DELUXE", ItemClassification.filler),
"Agency Pickup - Bangkok - 47's Suite":(9,"duplicate", ItemClassification.filler),
"Agency Pickup - Marrakesh - Lamp Shop Alley":(77,"duplicate", ItemClassification.filler),
"Agency Pickup - Miami - Bayside Center Car Park":(89,"duplicate", ItemClassification.filler),
"Agency Pickup - Paris - Basement Stairwell":(130,"duplicate", ItemClassification.filler),
"Agency Pickup - Sapienza - ICA Safe House":(144,"duplicate", ItemClassification.filler),
"Starting Location - Dartmoor - Main Road":(480,"duplicate", ItemClassification.filler),
"Starting Location - Bangkok - Riverside Landing":(494,"duplicate", ItemClassification.filler),
"Starting Location - Santa Fortuna - Village Bus Stop":(510,"duplicate", ItemClassification.filler),
"Starting Location - Berlin - Bus Stop":(531,"duplicate", ItemClassification.filler),
"Starting Location - Mendoza - Winery Viewpoint":(545,"duplicate", ItemClassification.filler),
"Starting Location - Dubai - Burj Al-Ghazali Exterior":(558,"duplicate", ItemClassification.filler),
"Starting Location - New York - Bank Entrance":(566,"duplicate", ItemClassification.filler),
"Starting Location - Hokkaido - Tobias Rieper's Suite":(571,"duplicate", ItemClassification.filler),
"Starting Location - Miami - Event Entrance":(597,"duplicate", ItemClassification.filler),
"Starting Location - Mumbai - Main street":(612,"duplicate", ItemClassification.filler),
"Starting Location - Hawkes Bay - Boat":(620,"duplicate", ItemClassification.filler),
"Starting Location - Whittleton Creek - Whittleton Creek":(624,"duplicate", ItemClassification.filler),
"Starting Location - Haven Island - Shark Hut":(631,"duplicate", ItemClassification.filler),
"Starting Location - Ambrose Island - Western Beach":(646,"duplicate", ItemClassification.filler),
"Starting Location - Sapienza - Portico":(656,"duplicate", ItemClassification.filler),
"Starting Location - Isle of Sgail - Harbor":(666,"duplicate", ItemClassification.filler),
"Starting Location - Carpathian Mountains - Reflection":(672,"duplicate", ItemClassification.filler),
"Starting Location - Chongqing - Train Station":(677,"duplicate", ItemClassification.filler),
"Pistol - ICA19 Black Lilly":(196,"EXECUTIVE", ItemClassification.filler),
"Suitcase - ICA Executive Briefcase":(287,"EXECUTIVE", ItemClassification.filler),
"Suit - Midnight Black Suit":(762,"COLLECTORS_OR_EXECUTIVE", ItemClassification.filler),
"Level - ICA Facility":(826,"ica_facility", ItemClassification.progression),
"Agency Pickup - Bangkok - Garden Shed":(10,"bangkok", ItemClassification.filler),
"Agency Pickup - Bangkok - Storage Room":(11,"bangkok", ItemClassification.filler),
"Hidden Stash - Bangkok - 1st Floor South Wing Balcony":(12,"bangkok", ItemClassification.filler),
"Agency Pickup - Bangkok - South Wing Basement":(14,"bangkok", ItemClassification.filler),
"Hidden Stash - Bangkok - Room 102 Bathroom":(15,"bangkok", ItemClassification.filler),
"Agency Pickup - Bangkok - Penthouse":(17,"bangkok", ItemClassification.filler),
"Hidden Stash - Bangkok - Ground Floor Restaurant Restroom":(18,"bangkok", ItemClassification.filler),
"Agency Pickup - Bangkok - Recording Studio":(19,"bangkok", ItemClassification.filler),
"Hidden Stash - Colorado - Ground Floor Laundry Room":(28,"colorado", ItemClassification.filler),
"Hidden Stash - Colorado - Orchard Road":(29,"colorado", ItemClassification.filler),
"Hidden Stash - Colorado - Truck Loading Area":(30,"colorado", ItemClassification.filler),
"Agency Pickup - Colorado - Red Barn":(31,"colorado", ItemClassification.filler),
"Hidden Stash - Colorado - Courtyard Shed":(32,"colorado", ItemClassification.filler),
"Hidden Stash - Colorado - Hay Shed":(33,"colorado", ItemClassification.filler),
"Agency Pickup - Colorado - Water Tower":(34,"colorado", ItemClassification.filler),
"Agency Pickup - Colorado - West Bridge":(35,"colorado", ItemClassification.filler),
"Agency Pickup - Hokkaido - Garage":(67,"hokkaido", ItemClassification.filler),
"Agency Pickup - Hokkaido - Kitchen Food Storage":(68,"hokkaido", ItemClassification.filler),
"Agency Pickup - Hokkaido - Morgue Storage":(69,"hokkaido", ItemClassification.filler),
"Agency Pickup - Hokkaido - Mountain Path":(70,"hokkaido", ItemClassification.filler),
"Hidden Stash - Hokkaido - Operating Theater Restroom":(71,"hokkaido", ItemClassification.filler),
"Hidden Stash - Hokkaido - Restaurant Restroom":(72,"hokkaido", ItemClassification.filler),
"Hidden Stash - Hokkaido - Staff Wardrobe":(73,"hokkaido", ItemClassification.filler),
"Hidden Stash - Marrakesh - Carpet Shop":(74,"marrakesh", ItemClassification.filler),
"Hidden Stash - Marrakesh - Shisha Café Restroom":(75,"marrakesh", ItemClassification.filler),
"Agency Pickup - Marrakesh - Old Headmaster's Terrace":(76,"marrakesh", ItemClassification.filler),
"Hidden Stash - Marrakesh - Mechanic Shop":(78,"marrakesh", ItemClassification.filler),
"Agency Pickup - Marrakesh - West Bazaar Rooftops":(79,"marrakesh", ItemClassification.filler),
"Agency Pickup - Marrakesh - Consulate Parking Garage":(80,"marrakesh", ItemClassification.filler),
"Hidden Stash - Marrakesh - Consulate Top Floor":(81,"marrakesh", ItemClassification.filler),
"Agency Pickup - Marrakesh - School Gate":(82,"marrakesh", ItemClassification.filler),
"Agency Pickup - Paris - Empty Attic Room":(128,"paris", ItemClassification.filler),
"Agency Pickup - Paris - Shed":(129,"paris", ItemClassification.filler),
"Agency Pickup - Paris - Logistics Trailer":(132,"paris", ItemClassification.filler),
"Hidden Stash - Paris - First Floor Apartments":(133,"paris", ItemClassification.filler),
"Hidden Stash - Paris - Pantry":(134,"paris", ItemClassification.filler),
"Hidden Stash - Paris - Top Floor Bathroom":(135,"paris", ItemClassification.filler),
"Agency Pickup - Sapienza - Café Basement":(145,"sapienza", ItemClassification.filler),
"Hidden Stash - Sapienza - Confessional Booth":(146,"sapienza", ItemClassification.filler),
"Agency Pickup - Sapienza - Ether Field Lab":(147,"sapienza", ItemClassification.filler),
"Hidden Stash - Sapienza - Mansion Pantry":(148,"sapienza", ItemClassification.filler),
"Hidden Stash - Sapienza - Mansion Garage":(149,"sapienza", ItemClassification.filler),
"Agency Pickup - Sapienza - Sapienza Ruins":(150,"sapienza", ItemClassification.filler),
"Agency Pickup - Sapienza - Sewers":(151,"sapienza", ItemClassification.filler),
"Starting Location - Bangkok - Undercover at the Himmapan Bar":(489,"bangkok", ItemClassification.filler),
"Starting Location - Bangkok - Undercover in the Side Garden":(490,"bangkok", ItemClassification.filler),
"Starting Location - Bangkok - Undercover by the Security Hut":(491,"bangkok", ItemClassification.filler),
"Starting Location - Bangkok - 47's Suite":(492,"bangkok", ItemClassification.filler),
"Starting Location - Bangkok - Undercover in the 2nd Floor Hallway":(493,"bangkok", ItemClassification.filler),
"Starting Location - Bangkok - Undercover in the Linen Room":(495,"bangkok", ItemClassification.filler),
"Starting Location - Bangkok - Undercover in the Restaurant Kitchen":(496,"bangkok", ItemClassification.filler),
"Starting Location - Colorado - Undercover in the Garage":(515,"colorado", ItemClassification.filler),
"Starting Location - Colorado - Undercover on the Demolition Range":(516,"colorado", ItemClassification.filler),
"Starting Location - Colorado - Undercover by the Greenhouse":(517,"colorado", ItemClassification.filler),
"Starting Location - Colorado - Undercover in the Farm House":(518,"colorado", ItemClassification.filler),
"Starting Location - Colorado - Old Orchard":(519,"colorado", ItemClassification.filler),
"Starting Location - Colorado - Water Tower":(521,"colorado", ItemClassification.filler),
"Starting Location - Colorado - West Bridge":(522,"colorado", ItemClassification.filler),
"Starting Location - Hokkaido - Infiltrating below the Helipad":(569,"hokkaido", ItemClassification.filler),
"Starting Location - Hokkaido - Undercover in the Garden":(572,"hokkaido", ItemClassification.filler),
"Starting Location - Hokkaido - Undercover in the Kitchen":(573,"hokkaido", ItemClassification.filler),
"Starting Location - Hokkaido - Morgue":(574,"hokkaido", ItemClassification.filler),
"Starting Location - Hokkaido - Infiltrating Along the Mountain Path":(575,"hokkaido", ItemClassification.filler),
"Starting Location - Hokkaido - Undercover in the Operating Theater":(576,"hokkaido", ItemClassification.filler),
"Starting Location - Hokkaido - Restaurant":(577,"hokkaido", ItemClassification.filler),
"Starting Location - Hokkaido - Undercover in the Staff Quarters":(578,"hokkaido", ItemClassification.filler),
"Starting Location - Hokkaido - Spa":(579,"hokkaido", ItemClassification.filler),
"Starting Location - Marrakesh - Lamp Store Rooftop":(584,"marrakesh", ItemClassification.filler),
"Starting Location - Marrakesh - Undercover in the Courtyard Club":(585,"marrakesh", ItemClassification.filler),
"Starting Location - Marrakesh - Undercover at the Snail Stand":(586,"marrakesh", ItemClassification.filler),
"Starting Location - Marrakesh - Undercover on the West Bazaar Rooftop":(587,"marrakesh", ItemClassification.filler),
"Starting Location - Marrakesh - Consulate Parking Garage":(588,"marrakesh", ItemClassification.filler),
"Starting Location - Marrakesh - Undercover in the Consulate":(589,"marrakesh", ItemClassification.filler),
"Starting Location - Marrakesh - School Alley":(590,"marrakesh", ItemClassification.filler),
"Starting Location - Marrakesh - Undercover in Zaydan's Compound":(591,"marrakesh", ItemClassification.filler),
"Starting Location - Paris - Palace Garden":(637,"paris", ItemClassification.filler),
"Starting Location - Paris - Attic":(638,"paris", ItemClassification.filler),
"Starting Location - Paris - Undercover at IAGO Auction":(639,"paris", ItemClassification.filler),
"Starting Location - Paris - Undercover in AV Center":(640,"paris", ItemClassification.filler),
"Starting Location - Paris - Undercover in Kitchen":(641,"paris", ItemClassification.filler),
"Starting Location - Paris - Undercover in Dressing Area":(642,"paris", ItemClassification.filler),
"Starting Location - Paris - Undercover in Locker Room":(643,"paris", ItemClassification.filler),
"Starting Location - Paris - Pile-Driver Barge":(644,"paris", ItemClassification.filler),
"Starting Location - Sapienza - ICA Safe House":(653,"sapienza", ItemClassification.filler),
"Starting Location - Sapienza - Main Square Tower":(654,"sapienza", ItemClassification.filler),
"Starting Location - Sapienza - Church Morgue":(655,"sapienza", ItemClassification.filler),
"Starting Location - Sapienza - Harbor":(657,"sapienza", ItemClassification.filler),
"Starting Location - Sapienza - Undercover in Field Lab":(658,"sapienza", ItemClassification.filler),
"Starting Location - Sapienza - Undercover as Security Staff":(659,"sapienza", ItemClassification.filler),
"Starting Location - Sapienza - Undercover in Mansion Garden":(660,"sapienza", ItemClassification.filler),
"Starting Location - Sapienza - Undercover in Mansion Kitchen":(661,"sapienza", ItemClassification.filler),
"Starting Location - Sapienza - Sapienza Ruins":(662,"sapienza", ItemClassification.filler),
"Level - Bangkok":(807,"bangkok", ItemClassification.progression),
"Level - Colorado":(809,"colorado", ItemClassification.progression),
"Level - Hokkaido":(814,"hokkaido", ItemClassification.progression),
"Level - Marrakesh":(815,"marrakesh", ItemClassification.progression),
"Level - Paris":(820,"paris", ItemClassification.progression),
"Level - Sapienza":(822,"sapienza", ItemClassification.progression),
"Agency Pickup - Bangkok - North Wing Basement":(13,"h1,unknown", ItemClassification.filler),
"Agency Pickup - Sapienza - Via Valle del Sole 9":(143,"h1,unknown", ItemClassification.filler),
"Starting Location - Bangkok - Hotel Front Terrace":(497,"h1,unknown", ItemClassification.filler),
"Starting Location - Colorado - Sniper Tower":(520,"h1,unknown", ItemClassification.filler),
"Starting Location - Hokkaido - Bar":(568,"h1,unknown", ItemClassification.filler),
"Starting Location - Sapienza - Via Valle del Sole 9":(652,"h1,unknown", ItemClassification.filler),
"Suit - Cowboy Suit":(748,"H1_GOTY_UNLOCKABLES", ItemClassification.filler),
"Suit - Raven Suit":(759,"H1_GOTY_UNLOCKABLES", ItemClassification.filler),
"Suit - Clown Suit":(771,"H1_GOTY_UNLOCKABLES", ItemClassification.filler),
"Pistol - Striker":(255,"H1_GOTY_UNLOCKABLES,LEGACY", ItemClassification.filler),
"Sniper - Siger 300 Ghost":(275,"H1_GOTY_UNLOCKABLES,LEGACY", ItemClassification.useful),
"Melee - A New Bat":(378,"H1_GOTY_UNLOCKABLES,LEGACY", ItemClassification.filler),
"Suit - Requiem Suit":(756,"H1_REQUIEM_UNLACKABLE", ItemClassification.filler),
"Pistol - ICA19 Chrome":(194,"H1_REQUIEM_UNLACKABLE", ItemClassification.filler),
"Explosive - The Pale Duck":(359,"H1_REQUIEM_UNLACKABLE", ItemClassification.filler),
"Agency Pickup - Santa Fortuna - Coca Fields":(20,"santa_fortuna", ItemClassification.filler),
"Agency Pickup - Santa Fortuna - Construction Site":(21,"santa_fortuna", ItemClassification.filler),
"Agency Pickup - Santa Fortuna - Wine cellar":(22,"santa_fortuna", ItemClassification.filler),
"Agency Pickup - Santa Fortuna - Village Contruction Building":(23,"santa_fortuna", ItemClassification.filler),
"Hidden Stash - Santa Fortuna - Caves":(24,"santa_fortuna", ItemClassification.filler),
"Hidden Stash - Santa Fortuna - Fishing village":(25,"santa_fortuna", ItemClassification.filler),
"Hidden Stash - Santa Fortuna - Hostel":(26,"santa_fortuna", ItemClassification.filler),
"Hidden Stash - Santa Fortuna - Jungle":(27,"santa_fortuna", ItemClassification.filler),
"Agency Pickup - Miami - Boat Rental Hut":(83,"miami", ItemClassification.filler),
"Agency Pickup - Miami - Parkside Food Stands":(84,"miami", ItemClassification.filler),
"Agency Pickup - Miami - Pit Building Locker Room":(85,"miami", ItemClassification.filler),
"Agency Pickup - Miami - Kronstadt Storage Area":(86,"miami", ItemClassification.filler),
"Agency Pickup - Miami - Thwack Paddock":(87,"miami", ItemClassification.filler),
"Agency Pickup - Miami - Backstage Truck":(88,"miami", ItemClassification.filler),
"Hidden Stash - Miami - Kronstadt Reception":(90,"miami", ItemClassification.filler),
"Hidden Stash - Miami - Podium Storage":(91,"miami", ItemClassification.filler),
"Hidden Stash - Miami - Stands Toilet":(92,"miami", ItemClassification.filler),
"Agency Pickup - Mumbai - Construction site":(93,"mumbai", ItemClassification.filler),
"Agency Pickup - Mumbai - Rooftop South":(94,"mumbai", ItemClassification.filler),
"Agency Pickup - Mumbai - Carpark":(95,"mumbai", ItemClassification.filler),
"Agency Pickup - Mumbai - The Hill":(96,"mumbai", ItemClassification.filler),
"Agency Pickup - Mumbai - Mumbai Laundry":(97,"mumbai", ItemClassification.filler),
"Agency Pickup - Mumbai - Rooftop North":(98,"mumbai", ItemClassification.filler),
"Agency Pickup - Mumbai - Train Tracks":(99,"mumbai", ItemClassification.filler),
"Agency Pickup - Mumbai - Train yard":(100,"mumbai", ItemClassification.filler),
"Hidden Stash - Mumbai - Rangan Tower":(101,"mumbai", ItemClassification.filler),
"Hidden Stash - Mumbai - Slum Apartment":(102,"mumbai", ItemClassification.filler),
"Hidden Stash - Mumbai - Beach":(103,"mumbai", ItemClassification.filler),
"Hidden Stash - Mumbai - Washing Stalls":(104,"mumbai", ItemClassification.filler),
"Hidden Stash - Mumbai - Streets on the Hill":(105,"mumbai", ItemClassification.filler),
"Hidden Stash - Mumbai - Balcony Pot":(106,"mumbai", ItemClassification.filler),
"Hidden Stash - Mumbai - Meat Market":(107,"mumbai", ItemClassification.filler),
"Hidden Stash - Mumbai - Homeless Tent":(108,"mumbai", ItemClassification.filler),
"Hidden Stash - Mumbai - Pottery Market":(109,"mumbai", ItemClassification.filler),
"Hidden Stash - Mumbai - Channel":(110,"mumbai", ItemClassification.filler),
"Hidden Stash - Mumbai - Shoeshop":(111,"mumbai", ItemClassification.filler),
"Hidden Stash - Mumbai - Old Tyre":(112,"mumbai", ItemClassification.filler),
"Agency Pickup - Hawkes Bay - Beach Shack":(113,"hawkes_bay", ItemClassification.filler),
"Hidden Stash - Hawkes Bay - Garbage Container":(114,"hawkes_bay", ItemClassification.filler),
"Agency Pickup - Whittleton Creek - Bench":(115,"whittleton_creek", ItemClassification.filler),
"Agency Pickup - Whittleton Creek - Cassidys Attic":(116,"whittleton_creek", ItemClassification.filler),
"Agency Pickup - Whittleton Creek - Park Shed":(117,"whittleton_creek", ItemClassification.filler),
"Agency Pickup - Whittleton Creek - Treehouse":(118,"whittleton_creek", ItemClassification.filler),
"Agency Pickup - Whittleton Creek - Hansons Basement":(119,"whittleton_creek", ItemClassification.filler),
"Hidden Stash - Whittleton Creek - Battys Garden":(120,"whittleton_creek", ItemClassification.filler),
"Hidden Stash - Whittleton Creek - Creek Shed":(121,"whittleton_creek", ItemClassification.filler),
"Hidden Stash - Whittleton Creek - R. Cross Driveway":(122,"whittleton_creek", ItemClassification.filler),
"Hidden Stash - Whittleton Creek - Helens Garage":(123,"whittleton_creek", ItemClassification.filler),
"Hidden Stash - Whittleton Creek - House For Sale":(124,"whittleton_creek", ItemClassification.filler),
"Hidden Stash - Whittleton Creek - Janus Kitchen":(125,"whittleton_creek", ItemClassification.filler),
"Hidden Stash - Whittleton Creek - Park":(126,"whittleton_creek", ItemClassification.filler),
"Hidden Stash - Whittleton Creek - Lewinskys House":(127,"whittleton_creek", ItemClassification.filler),
"Agency Pickup - Isle of Sgail - Chapel":(161,"isle_of_sgail", ItemClassification.filler),
"Agency Pickup - Isle of Sgail - Cistern":(162,"isle_of_sgail", ItemClassification.filler),
"Agency Pickup - Isle of Sgail - Morgue":(163,"isle_of_sgail", ItemClassification.filler),
"Agency Pickup - Isle of Sgail - Hyperborean Showrooms":(164,"isle_of_sgail", ItemClassification.filler),
"Agency Pickup - Isle of Sgail - Warehouse":(165,"isle_of_sgail", ItemClassification.filler),
"Agency Pickup - Isle of Sgail - Kitchen":(166,"isle_of_sgail", ItemClassification.filler),
"Agency Pickup - Isle of Sgail - Gallery Stairwell":(167,"isle_of_sgail", ItemClassification.filler),
"Agency Pickup - Isle of Sgail - Gatehouse":(168,"isle_of_sgail", ItemClassification.filler),
"Starting Location - Santa Fortuna - Coca Fields":(503,"santa_fortuna", ItemClassification.filler),
"Starting Location - Santa Fortuna - Construction Site":(504,"santa_fortuna", ItemClassification.filler),
"Starting Location - Santa Fortuna - Village Hostel":(505,"santa_fortuna", ItemClassification.filler),
"Starting Location - Santa Fortuna - Shaman's Hut":(506,"santa_fortuna", ItemClassification.filler),
"Starting Location - Santa Fortuna - Mansion Basement":(507,"santa_fortuna", ItemClassification.filler),
"Starting Location - Santa Fortuna - Submarine Cave":(508,"santa_fortuna", ItemClassification.filler),
"Starting Location - Santa Fortuna - Village Bar":(509,"santa_fortuna", ItemClassification.filler),
"Starting Location - Miami - Kronstadt Bayside Center":(592,"miami", ItemClassification.filler),
"Starting Location - Miami - Dolphin Fountain":(593,"miami", ItemClassification.filler),
"Starting Location - Miami - Food Stand":(594,"miami", ItemClassification.filler),
"Starting Location - Miami - Kowoon Pit":(595,"miami", ItemClassification.filler),
"Starting Location - Miami - Overpass":(596,"miami", ItemClassification.filler),
"Starting Location - Miami - Marina":(598,"miami", ItemClassification.filler),
"Starting Location - Miami - Medical Area":(599,"miami", ItemClassification.filler),
"Starting Location - Miami - Podium":(600,"miami", ItemClassification.filler),
"Starting Location - Miami - Stands":(601,"miami", ItemClassification.filler),
"Starting Location - Miami - Drivers' Lounge":(602,"miami", ItemClassification.filler),
"Starting Location - Mumbai - Photoshoot":(605,"mumbai", ItemClassification.filler),
"Starting Location - Mumbai - Barge":(606,"mumbai", ItemClassification.filler),
"Starting Location - Mumbai - Boat":(607,"mumbai", ItemClassification.filler),
"Starting Location - Mumbai - Metal Forge":(608,"mumbai", ItemClassification.filler),
"Starting Location - Mumbai - Hill":(609,"mumbai", ItemClassification.filler),
"Starting Location - Mumbai - Chawls":(610,"mumbai", ItemClassification.filler),
"Starting Location - Mumbai - Laundry":(611,"mumbai", ItemClassification.filler),
"Starting Location - Mumbai - Skywalk":(613,"mumbai", ItemClassification.filler),
"Starting Location - Mumbai - Slums":(614,"mumbai", ItemClassification.filler),
"Starting Location - Mumbai - Taxi":(615,"mumbai", ItemClassification.filler),
"Starting Location - Mumbai - Train":(616,"mumbai", ItemClassification.filler),
"Starting Location - Mumbai - Train yard":(617,"mumbai", ItemClassification.filler),
"Starting Location - Hawkes Bay - Beach":(618,"hawkes_bay", ItemClassification.filler),
"Starting Location - Hawkes Bay - Office":(622,"hawkes_bay", ItemClassification.filler),
"Starting Location - Whittleton Creek - BBQ Party":(623,"whittleton_creek", ItemClassification.filler),
"Starting Location - Whittleton Creek - Construction Area":(625,"whittleton_creek", ItemClassification.filler),
"Starting Location - Whittleton Creek - Fumigation":(626,"whittleton_creek", ItemClassification.filler),
"Starting Location - Whittleton Creek - Garbage Removal":(627,"whittleton_creek", ItemClassification.filler),
"Starting Location - Whittleton Creek - Suburb Sign":(628,"whittleton_creek", ItemClassification.filler),
"Starting Location - Isle of Sgail - Gallery":(663,"isle_of_sgail", ItemClassification.filler),
"Starting Location - Isle of Sgail - Architects' Lounge":(664,"isle_of_sgail", ItemClassification.filler),
"Starting Location - Isle of Sgail - Chapel":(665,"isle_of_sgail", ItemClassification.filler),
"Starting Location - Isle of Sgail - Keep":(667,"isle_of_sgail", ItemClassification.filler),
"Starting Location - Isle of Sgail - Kitchens":(669,"isle_of_sgail", ItemClassification.filler),
"Starting Location - Isle of Sgail - Warehouse":(670,"isle_of_sgail", ItemClassification.filler),
"Starting Location - Isle of Sgail - Reception Area":(671,"isle_of_sgail", ItemClassification.filler),
"Level - Santa Fortuna":(808,"santa_fortuna", ItemClassification.progression),
"Level - Miami":(816,"miami", ItemClassification.progression),
"Level - Mumbai":(817,"mumbai", ItemClassification.progression),
"Level - Hawkes Bay":(818,"hawkes_bay", ItemClassification.progression),
"Level - Whittleton Creek":(819,"whittleton_creek", ItemClassification.progression),
"Level - Isle of Sgail":(824,"isle_of_sgail", ItemClassification.progression),
"Starting Location - Santa Fortuna - Steel Bridge":(501,"h2,unkown", ItemClassification.filler),
"Starting Location - Mumbai - Outside Chawl":(604,"h2,unkown", ItemClassification.filler),
"Agency Pickup - New York - Executive Floor":(61,"new_york", ItemClassification.filler),
"Agency Pickup - New York - First Floor Janitor Room":(62,"new_york", ItemClassification.filler),
"Agency Pickup - New York - Vault's Loading Bay":(63,"new_york", ItemClassification.filler),
"Hidden Stash - New York - Waiting Area Bathroom":(64,"new_york", ItemClassification.filler),
"Hidden Stash - New York - Second Floor Bathroom":(65,"new_york", ItemClassification.filler),
"Hidden Stash - New York - Deposit Box":(66,"new_york", ItemClassification.filler),
"Agency Pickup - Haven Island - Shark Hut":(152,"haven_island", ItemClassification.filler),
"Agency Pickup - Haven Island - Security Hut":(153,"haven_island", ItemClassification.filler),
"Agency Pickup - Haven Island - Villa Beach Storage Area":(154,"haven_island", ItemClassification.filler),
"Hidden Stash - Haven Island - Buried In Sand":(155,"haven_island", ItemClassification.filler),
"Hidden Stash - Haven Island - Laundry Room":(156,"haven_island", ItemClassification.filler),
"Hidden Stash - Haven Island - Changing Room":(157,"haven_island", ItemClassification.filler),
"Hidden Stash - Haven Island - Restaurant Storage Room":(158,"haven_island", ItemClassification.filler),
"Hidden Stash - Haven Island - Underground Storage Room":(159,"haven_island", ItemClassification.filler),
"Hidden Stash - Haven Island - Villa Bathroom":(160,"haven_island", ItemClassification.filler),
"Starting Location - New York - Audit Hall":(561,"new_york", ItemClassification.filler),
"Starting Location - New York - Deposit Box Room":(563,"new_york", ItemClassification.filler),
"Starting Location - New York - Garage":(564,"new_york", ItemClassification.filler),
"Starting Location - New York - Investment Floor":(565,"new_york", ItemClassification.filler),
"Starting Location - New York - First Floor Mezzanine":(567,"new_york", ItemClassification.filler),
"Starting Location - Haven Island - Resort Gym":(632,"haven_island", ItemClassification.filler),
"Starting Location - Haven Island - Restaurant's Kitchen":(633,"haven_island", ItemClassification.filler),
"Starting Location - Haven Island - Resort Pier":(634,"haven_island", ItemClassification.filler),
"Starting Location - Haven Island - Resort Pool Area":(635,"haven_island", ItemClassification.filler),
"Starting Location - Haven Island - Private Villa Pier":(636,"haven_island", ItemClassification.filler),
"Level - New York":(813,"new_york", ItemClassification.progression),
"Level - Haven Island":(823,"haven_island", ItemClassification.progression),
"Suit - TOKEN_OUTFIT_GREEDY_HERO_GREEDYSUIT":(699,"H2_RACCOON_STINGRAY,unknown", ItemClassification.filler),
"Pistol - Sieker 1":(246,"H2_RACCOON_STINGRAY", ItemClassification.useful),
"Sniper - Jaeger 7 Tuatara":(270,"H2_RACCOON_STINGRAY", ItemClassification.filler),
"Melee - Jarl's Pirate Saber":(425,"H2_RACCOON_STINGRAY", ItemClassification.filler),
"Melee - The Black Almond's Dagger":(442,"H2_RACCOON_STINGRAY", ItemClassification.filler),
"Melee - Small Goldbar":(462,"H2_RACCOON_STINGRAY", ItemClassification.filler),
"Suit - The New Yorker with Gloves":(688,"H2_RACCOON_STINGRAY", ItemClassification.filler),
"Suit - The Buccaneer":(732,"H2_RACCOON_STINGRAY", ItemClassification.filler),
"Suit - The Tropical Islander":(770,"H2_RACCOON_STINGRAY", ItemClassification.filler),
"Suit - The Tropical Suit":(798,"H2_RACCOON_STINGRAY", ItemClassification.filler),
"Shotgun - Sawed-Off Bartoli 12G":(213,"H2_RACCOON_STINGRAY", ItemClassification.filler),
"Tool - Remote Emetic Gas Device":(331,"H2_RACCOON_STINGRAY", ItemClassification.filler),
"Explosive - ICA Remote Flash Device":(329,"H2_RACCOON_STINGRAY", ItemClassification.filler),
"Agency Pickup - Dartmoor - Changing room":(1,"dartmoor", ItemClassification.filler),
"Agency Pickup - Dartmoor - Graveyard":(2,"dartmoor", ItemClassification.filler),
"Agency Pickup - Dartmoor - Hallway":(3,"dartmoor", ItemClassification.filler),
"Agency Pickup - Dartmoor - Bathroom":(4,"dartmoor", ItemClassification.filler),
"Hidden Stash - Dartmoor - Deliveries":(5,"dartmoor", ItemClassification.filler),
"Hidden Stash - Dartmoor - Greenhouse":(6,"dartmoor", ItemClassification.filler),
"Hidden Stash - Dartmoor - Laundry Room":(7,"dartmoor", ItemClassification.filler),
"Hidden Stash - Dartmoor - Library":(8,"dartmoor", ItemClassification.filler),
"Agency Pickup - Berlin - Overpass":(36,"berlin", ItemClassification.filler),
"Agency Pickup - Berlin - Basement Boiler Room":(37,"berlin", ItemClassification.filler),
"Agency Pickup - Berlin - Chill-Out Stff Trailer":(38,"berlin", ItemClassification.filler),
"Agency Pickup - Berlin - Entrance Staff Room":(39,"berlin", ItemClassification.filler),
"Agency Pickup - Berlin - Skylight Access":(40,"berlin", ItemClassification.filler),
"Hidden Stash - Berlin - Projection Bar":(41,"berlin", ItemClassification.filler),
"Hidden Stash - Berlin - Basement Toilet":(42,"berlin", ItemClassification.filler),
"Hidden Stash - Berlin - Biker Garage":(43,"berlin", ItemClassification.filler),
"Agency Pickup - Mendoza - Barrel Room":(44,"mendoza", ItemClassification.filler),
"Agency Pickup - Mendoza - Grapefield Shed":(45,"mendoza", ItemClassification.filler),
"Agency Pickup - Mendoza - Steel Tanks":(46,"mendoza", ItemClassification.filler),
"Agency Pickup - Mendoza - Villa Attic":(47,"mendoza", ItemClassification.filler),
"Hidden Stash - Mendoza - Boathouse":(48,"mendoza", ItemClassification.filler),
"Hidden Stash - Mendoza - Cinema":(49,"mendoza", ItemClassification.filler),
"Hidden Stash - Mendoza - Dance Floor":(50,"mendoza", ItemClassification.filler),
"Hidden Stash - Mendoza - Shrine":(51,"mendoza", ItemClassification.filler),
"Hidden Stash - Mendoza - Villa Basement":(52,"mendoza", ItemClassification.filler),
"Hidden Stash - Mendoza - Worker's Bathroom":(53,"mendoza", ItemClassification.filler),
"Agency Pickup - Dubai - Art Backstage Balcony":(54,"dubai", ItemClassification.filler),
"Agency Pickup - Dubai - Maintenance Room":(55,"dubai", ItemClassification.filler),
"Agency Pickup - Dubai - Penthouse Ventilation Area":(56,"dubai", ItemClassification.filler),
"Agency Pickup - Dubai - Penthouse Supply Room":(57,"dubai", ItemClassification.filler),
"Hidden Stash - Dubai - Atrium Toilet":(58,"dubai", ItemClassification.filler),
"Hidden Stash - Dubai - Kitchen":(59,"dubai", ItemClassification.filler),
"Hidden Stash - Dubai - Laundry Room":(60,"dubai", ItemClassification.filler),
"Agency Pickup - Ambrose Island - Boat Cradle":(136,"ambrose_island", ItemClassification.filler),
"Agency Pickup - Ambrose Island - Food Storage":(137,"ambrose_island", ItemClassification.filler),
"Agency Pickup - Ambrose Island - Green Container":(138,"ambrose_island", ItemClassification.filler),
"Agency Pickup - Ambrose Island - Colonial Ruins":(139,"ambrose_island", ItemClassification.filler),
"Hidden Stash - Ambrose Island - Big Tree":(140,"ambrose_island", ItemClassification.filler),
"Hidden Stash - Ambrose Island - Shrine":(141,"ambrose_island", ItemClassification.filler),
"Hidden Stash - Ambrose Island - Farah's Place":(142,"ambrose_island", ItemClassification.filler),
"Agency Pickup - Chongqing - Side Alley":(169,"chongqing", ItemClassification.filler),
"Agency Pickup - Chongqing - Apartment":(170,"chongqing", ItemClassification.filler),
"Agency Pickup - Chongqing - Corridor":(171,"chongqing", ItemClassification.filler),
"Agency Pickup - Chongqing - Facility Maintenance Tunnel":(172,"chongqing", ItemClassification.filler),
"Agency Pickup - Chongqing - Arcade":(173,"chongqing", ItemClassification.filler),
"Hidden Stash - Chongqing - Facility Server Supply Room":(174,"chongqing", ItemClassification.filler),
"Hidden Stash - Chongqing - Facility Rooftop":(175,"chongqing", ItemClassification.filler),
"Hidden Stash - Chongqing - Facility Ventilation Room":(176,"chongqing", ItemClassification.filler),
"Hidden Stash - Chongqing - The Laundry":(177,"chongqing", ItemClassification.filler),
"Hidden Stash - Chongqing - Restaurant Back Stairwell":(178,"chongqing", ItemClassification.filler),
"Starting Location - Dartmoor - Behind Mansion":(478,"dartmoor", ItemClassification.filler),
"Starting Location - Dartmoor - Behind Mansion (Skipped)":(479,"dartmoor", ItemClassification.filler),
"Starting Location - Dartmoor - Main Road (Skipped)":(481,"dartmoor", ItemClassification.filler),
"Starting Location - Dartmoor - Garden":(482,"dartmoor", ItemClassification.filler),
"Starting Location - Dartmoor - Library":(483,"dartmoor", ItemClassification.filler),
"Starting Location - Dartmoor - Staff Room":(484,"dartmoor", ItemClassification.filler),
"Starting Location - Dartmoor - Zachery's Bedroom":(485,"dartmoor", ItemClassification.filler),
"Starting Location - Berlin - Projection Bar":(524,"berlin", ItemClassification.filler),
"Starting Location - Berlin - Biker Hangout":(525,"berlin", ItemClassification.filler),
"Starting Location - Berlin - Chill Out":(526,"berlin", ItemClassification.filler),
"Starting Location - Berlin - Club Entrance":(527,"berlin", ItemClassification.useful),
"Starting Location - Berlin - DJ Booth":(533,"berlin", ItemClassification.filler),
"Starting Location - Berlin - Radio Tower":(534,"berlin", ItemClassification.filler),
"Starting Location - Mendoza - Dining Area":(543,"mendoza", ItemClassification.filler),
"Starting Location - Mendoza - Vineyard":(544,"mendoza", ItemClassification.filler),
"Starting Location - Mendoza - Parking Lot":(548,"mendoza", ItemClassification.filler),
"Starting Location - Mendoza - Shrine":(549,"mendoza", ItemClassification.filler),
"Starting Location - Mendoza - Sniper Spot":(550,"mendoza", ItemClassification.filler),
"Starting Location - Mendoza - Tasting Room":(551,"mendoza", ItemClassification.filler),
"Starting Location - Dubai - Art Installation":(554,"dubai", ItemClassification.filler),
"Starting Location - Dubai - Guard Room":(555,"dubai", ItemClassification.filler),
"Starting Location - Dubai - Atrium Lobby":(556,"dubai", ItemClassification.useful),
"Starting Location - Dubai - Meeting Room":(557,"dubai", ItemClassification.filler),
"Starting Location - Dubai - Penthouse":(559,"dubai", ItemClassification.filler),
"Starting Location - Ambrose Island - Militia Camp":(647,"ambrose_island", ItemClassification.filler),
"Starting Location - Ambrose Island - Pirate Camp":(648,"ambrose_island", ItemClassification.filler),
"Starting Location - Ambrose Island - Shrine":(649,"ambrose_island", ItemClassification.filler),
"Starting Location - Ambrose Island - Central Social Hub":(650,"ambrose_island", ItemClassification.filler),
"Starting Location - Ambrose Island - Stilt Village":(651,"ambrose_island", ItemClassification.filler),
"Starting Location - Carpathian Mountains - Outdoors":(673,"carpathian_mountains", ItemClassification.filler),
"Starting Location - Carpathian Mountains - Laboratory":(674,"carpathian_mountains", ItemClassification.useful),
"Starting Location - Chongqing - The Block":(676,"chongqing", ItemClassification.filler),
"Starting Location - Chongqing - Facility Locker Room":(678,"chongqing", ItemClassification.filler),
"Starting Location - Chongqing - Restaurant Kitchen":(679,"chongqing", ItemClassification.filler),
"Starting Location - Chongqing - Facility Rooftop":(680,"chongqing", ItemClassification.filler),
"Starting Location - Chongqing - Balcony":(681,"chongqing", ItemClassification.filler),
"Starting Location - Chongqing - River-side Walkway":(682,"chongqing", ItemClassification.useful),
"Level - Dartmoor":(806,"dartmoor", ItemClassification.progression),
"Level - Berlin":(810,"berlin", ItemClassification.progression),
"Level - Mendoza":(811,"mendoza", ItemClassification.progression),
"Level - Dubai":(812,"dubai", ItemClassification.progression),
"Level - Ambrose Island":(821,"ambrose_island", ItemClassification.progression),
"Level - Chongqing":(825,"chongqing", ItemClassification.progression),
"Level - Carpathian Mountains":(827,"carpathian_mountains", ItemClassification.progression),
"Melee - PROP_MELEE_VHS_LAMBIC":(830,"H3_ET_LAMBIC", ItemClassification.filler),
"Melee - PROP_MELEE_KUKRI_KNIFE_LAMBIC":(831,"H3_ET_LAMBIC", ItemClassification.filler),
"SMG - FIREARMS_HERO_SMG_HX_10_LAMBIC":(832,"H3_ET_LAMBIC", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_LAMBIC_KICKBOXER_REWARD":(829,"H3_ET_LAMBIC  ", ItemClassification.filler),
"Melee - PROP_MELEE_CANE_PENICILLIN":(833,"H3_ET_PENICILLIN", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_REWARD_HERO_PEN_COAT_SUIT":(836,"H3_ET_PENICILLIN", ItemClassification.filler),
"Melee - PROP_MELEE_STRENGTHBAND_PENICILLIN":(835,"H3_ET_PENICILLIN   ", ItemClassification.filler),
"Melee - PROP_MELEE_KETTLEBELL_PENICILLIN":(834,"H3_ET_PENICILLIN     ", ItemClassification.filler),
"Explosive - PROP_EXPLOSIVE_PEN_SAMBUCA":(839,"H3_ET_SAMBUCA", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_REWARD_HERO_SB_PATCH_SUIT":(840,"H3_ET_SAMBUCA", ItemClassification.filler),
"Melee - PROP_MELEE_BLACK_PHONE_CORD_SAMBUCA":(837,"H3_ET_SAMBUCA     ", ItemClassification.filler),
"Explosive - PROP_GADGET_ROBOT_FLASH_SAMBUCA":(838,"H3_ET_SAMBUCA       ", ItemClassification.filler),
"Explosive - PROP_EXPLOSIVE_GRENADE_FLASH_TOMORROWLAND":(874,"H3_ET_TOMORROWLAND", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_TOMORROWLAND_DJSUIT_REWARD":(876,"H3_ET_TOMORROWLAND", ItemClassification.filler),
"Suitcase - PROP_CONTAINER_SUITCASE_DJ_BAG":(873,"H3_ET_TOMORROWLAND   ", ItemClassification.filler),
"Starting Location - Mendoza - STARTING_LOCATION_ELEGANT_LLAMA_DEFAULT_COMMENTARY":(868,"H3_EXPANSION,commentary", ItemClassification.filler),
"Starting Location - Chongqing - STARTING_LOCATION_WET_RAT_DEFAULT_COMMENTARY":(869,"H3_EXPANSION,commentary", ItemClassification.filler),
"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_DEFAULT_COMMENTARY":(870,"H3_EXPANSION,commentary", ItemClassification.filler),
"Starting Location - Dartmoor - STARTING_LOCATION_ANCESTRAL_BULLDOG_DEFAULT_COMMENTARY_SUIT":(871,"H3_EXPANSION,commentary", ItemClassification.filler),
"Starting Location - Dubai - STARTING_LOCATION_GOLDEN_GECKO_OUTSIDE_DEFAULT_COMMENTARY":(872,"H3_EXPANSION,commentary", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_HERO_CONCRETEART":(847,"H3_VANITY_CONCRETEART", ItemClassification.filler),
"Melee - PROP_MELEE_BASEBALLBAT_CONCRETEART":(848,"H3_VANITY_CONCRETEART", ItemClassification.filler),
"Sniper - FIREARMS_HERO_SNIPER_CONCRETEART":(849,"H3_VANITY_CONCRETEART", ItemClassification.filler),
"SMG - FIREARMS_HERO_SMG_TAC_SMG_CONCRETEART":(850,"H3_VANITY_CONCRETEART", ItemClassification.filler),
"Assault Rifle - FIREARMS_HERO_RIFLE_CONCRETEART":(851,"H3_VANITY_CONCRETEART", ItemClassification.filler),
"Shotgun - FIREARMS_HERO_SHOTGUN_CONCRETEART":(852,"H3_VANITY_CONCRETEART", ItemClassification.filler),
"Pistol - FIREARMS_HERO_PISTOL_CONCRETEART":(853,"H3_VANITY_CONCRETEART", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_HERO_MAKESHIFT":(854,"H3_VANITY_MAKESHIFTSCRAP", ItemClassification.filler),
"Sniper - FIREARMS_HERO_SNIPER_MAKESHIFT":(856,"H3_VANITY_MAKESHIFTSCRAP", ItemClassification.filler),
"SMG - FIREARMS_HERO_SMG_TAC_SMG_MAKESHIFT":(857,"H3_VANITY_MAKESHIFTSCRAP", ItemClassification.filler),
"Assault Rifle - FIREARMS_HERO_RIFLE_MAKESHIFT":(858,"H3_VANITY_MAKESHIFTSCRAP", ItemClassification.filler),
"Shotgun - FIREARMS_HERO_SHOTGUN_MAKESHIFT":(859,"H3_VANITY_MAKESHIFTSCRAP", ItemClassification.filler),
"Pistol - FIREARMS_HERO_PISTOL_MAKESHIFT":(860,"H3_VANITY_MAKESHIFTSCRAP", ItemClassification.filler),
"Melee - PROP_MELEE_KATANA_MAKESHIFT":(855,"H3_VANITY_MAKESHIFTSCRAP  ", ItemClassification.filler),
"Pistol - Custom 5mm":(182,"LEGACY", ItemClassification.filler),
"Pistol - HWK21":(185,"LEGACY", ItemClassification.filler),
"Pistol - ICA19 Iceballer":(186,"LEGACY", ItemClassification.filler),
"Pistol - Krugermeier 2-2":(187,"LEGACY", ItemClassification.filler),
"Pistol - HWK21 Covert":(190,"LEGACY", ItemClassification.filler),
"Pistol - ICA19 F/A":(197,"LEGACY", ItemClassification.filler),
"Pistol - ICA19 F/A Stealth":(198,"LEGACY", ItemClassification.filler),
"Pistol - ICA19 Silverballer":(200,"LEGACY", ItemClassification.filler),
"Assault Rifle - TAC-4 AR Desert":(202,"LEGACY", ItemClassification.filler),
"Assault Rifle - RS-15":(203,"LEGACY", ItemClassification.filler),
"Assault Rifle - TAC-4 AR Stealth":(204,"LEGACY", ItemClassification.filler),
"Assault Rifle - TAC-4 AR Auto":(205,"LEGACY", ItemClassification.filler),
"Assault Rifle - TAC-4 S/A Jungle":(206,"LEGACY", ItemClassification.filler),
"Assault Rifle - TAC-4 S/A":(207,"LEGACY", ItemClassification.filler),
"Shotgun - Enram HV":(217,"LEGACY", ItemClassification.filler),
"Shotgun - ENRAM HV CM":(218,"LEGACY", ItemClassification.filler),
"Shotgun - ENRAM HV Covert":(219,"LEGACY", ItemClassification.filler),
"SMG - TAC-SMG":(224,"LEGACY", ItemClassification.useful),
"SMG - TAC-SMG S":(227,"LEGACY", ItemClassification.filler),
"Sniper - Jaeger 7 Lancer":(229,"LEGACY", ItemClassification.filler),
"Sniper - Jaeger 7 Tiger":(230,"LEGACY", ItemClassification.filler),
"Sniper - Jaeger 7":(231,"LEGACY", ItemClassification.filler),
"Sniper - Sieger 300":(233,"LEGACY", ItemClassification.filler),
"Sniper - Sieger 300 Advanced":(234,"LEGACY", ItemClassification.filler),
"Explosive - The Iconator":(297,"LEGACY", ItemClassification.filler),
"Explosive - Explosive Xmas Gift":(302,"LEGACY", ItemClassification.filler),
"Explosive - Proximity CX Demo Block":(303,"LEGACY", ItemClassification.filler),
"Explosive - Remote CX Demo Block":(304,"LEGACY", ItemClassification.filler),
"Explosive - ICA Proximity Explosive":(312,"LEGACY", ItemClassification.filler),
"Distraction - ICA Remote Audio Distraction":(315,"LEGACY", ItemClassification.filler),
"Explosive - Remote Breaching Charge":(316,"LEGACY", ItemClassification.filler),
"Explosive - ICA Remote Explosive":(319,"LEGACY", ItemClassification.useful),
"Distraction - \"Mixtape 47\"":(322,"LEGACY", ItemClassification.filler),
"Explosive - ICA Explosive Phone":(323,"LEGACY", ItemClassification.filler),
"Explosive - Proximity Explosive Duck":(339,"LEGACY", ItemClassification.filler),
"Explosive - Remote Explosive Duck":(341,"LEGACY", ItemClassification.filler),
"Explosive - Lil' Flashy":(349,"LEGACY", ItemClassification.filler),
"Explosive - Napolen Blownaparte":(350,"LEGACY", ItemClassification.filler),
"Distraction - The Big One":(360,"LEGACY", ItemClassification.filler),
"Explosive - Explosive Compound":(364,"LEGACY", ItemClassification.filler),
"Poision - Antique Emetic Syringe":(380,"LEGACY", ItemClassification.filler),
"Poision - Antique Lethal Syringe":(381,"LEGACY", ItemClassification.filler),
"Melee - Janbiya":(392,"LEGACY", ItemClassification.filler),
"Melee - Combat Knife":(394,"LEGACY", ItemClassification.filler),
"Melee - Crystal Ball":(395,"LEGACY", ItemClassification.filler),
"Melee - Concealable Baton":(400,"LEGACY", ItemClassification.filler),
"Melee - Concealable Knife":(404,"LEGACY", ItemClassification.filler),
"Melee - Ice Pick":(407,"LEGACY", ItemClassification.filler),
"Melee - HF Championship Bat":(408,"LEGACY", ItemClassification.filler),
"Melee - Masamune":(409,"LEGACY", ItemClassification.filler),
"Melee - Nne Obara's Machete":(416,"LEGACY", ItemClassification.filler),
"Melee - Earphones":(423,"LEGACY", ItemClassification.filler),
"Melee - Shuriken":(432,"LEGACY", ItemClassification.filler),
"Poision - Modern Emetic Syringe":(435,"LEGACY", ItemClassification.useful),
"Poision - Modern Lethal Syringe":(437,"LEGACY", ItemClassification.useful),
"Poision - Modern Sedative Syringe":(440,"LEGACY", ItemClassification.useful),
"Poision - Lethal Poison Vial":(452,"LEGACY", ItemClassification.useful),
"Poision - Sedative Poision Vial":(454,"LEGACY", ItemClassification.useful),
"Poision - Emetic Poison Vial":(455,"LEGACY", ItemClassification.useful),
"Tool - Disposable Scrambler":(461,"LEGACY", ItemClassification.filler),
"Tool - Lockpick":(466,"LEGACY", ItemClassification.useful),
"Suit - Tactical Gear":(691,"LEGACY", ItemClassification.filler),
"Suit - Tactical Turtleneck":(700,"LEGACY", ItemClassification.filler),
"Suit - Casual Suit with Gloves":(702,"LEGACY", ItemClassification.filler),
"Suit - Tactical Gear with Hunter's Hat":(709,"LEGACY", ItemClassification.filler),
"Suit - White Yukata":(724,"LEGACY", ItemClassification.filler),
"Suit - Summer Suit with Gloves":(729,"LEGACY", ItemClassification.filler),
"Suit - Tuxedo with Gloves":(731,"LEGACY", ItemClassification.filler),
"Suit - Santa 47":(737,"LEGACY", ItemClassification.filler),
"Suit - Italian Suit with Gloves":(738,"LEGACY", ItemClassification.filler),
"Suit - VIP Patient":(750,"LEGACY", ItemClassification.filler),
"Suit - Polar Survival Suit":(779,"LEGACY", ItemClassification.filler),
"Suit - Snow Festival Suit":(794,"LEGACY", ItemClassification.filler),
"Suit - The Cashmerian":(797,"LEGACY", ItemClassification.filler),
"Assault Rifle - The Ancestral Assault Rifle":(844,"LOCATION_GOLDEN", ItemClassification.filler),
"Pistol - The Ancestral Pistol":(846,"LOCATION_GOLDEN", ItemClassification.filler),
"Melee - The Ornamental Katana":(862,"LOCATION_GOLDEN", ItemClassification.filler),
"Sniper - The Ornamental Sniper Rifle":(863,"LOCATION_GOLDEN", ItemClassification.filler),
"Assault Rifle - The Ornamental Assault Rifle":(865,"LOCATION_GOLDEN", ItemClassification.filler),
"Shotgun - The Ornamental Shotgun":(866,"LOCATION_GOLDEN", ItemClassification.filler),
"Pistol - The Ornamental Pistol":(867,"LOCATION_GOLDEN", ItemClassification.filler),
"Explosive - The Ancestral Fountain Pen":(875,"LOCATION_GOLDEN", ItemClassification.filler),
"Suit - The Ancestral Hunter Suit":(841,"LOCATION_GOLDEN  ", ItemClassification.filler),
"Sniper - The Ancestral Sniper Rifle":(843,"LOCATION_GOLDEN  ", ItemClassification.filler),
"Suit - The Golden Contender Suit":(861,"LOCATION_GOLDEN  ", ItemClassification.filler),
"Melee - The Ancestral Knife":(842,"LOCATION_GOLDEN     ", ItemClassification.filler),
"SMG - The Ornamental SMG":(864,"LOCATION_GOLDEN     ", ItemClassification.filler),
"Shotgun - The Ancestral Shotgun":(845,"LOCATION_GOLDEN,DELUXE", ItemClassification.filler),
"Assault Rifle - The Shashka Beast":(209,"SINS", ItemClassification.filler),
"SMG - Slapdash SMG":(222,"SINS", ItemClassification.filler),
"Pistol - The Serpent's Tounge":(242,"SINS", ItemClassification.filler),
"Sniper - Jaeger 7 Green Eye":(271,"SINS", ItemClassification.filler),
"Sniper - The Majestic":(273,"SINS", ItemClassification.filler),
"Explosive - Goldbrick Proximity Mine":(298,"SINS", ItemClassification.filler),
"Explosive - The Roar Flash Grenade":(353,"SINS", ItemClassification.filler),
"Explosive - The Serpent's Bite":(356,"SINS", ItemClassification.filler),
"Melee - The Devil's Cane":(391,"SINS", ItemClassification.filler),
"Melee - The Cat's Claw":(396,"SINS", ItemClassification.filler),
"Melee - The Proud Swashbuckler":(427,"SINS", ItemClassification.filler),
"Distraction - Greedy Little Coin":(465,"SINS", ItemClassification.filler),
"Suit - The Odium Suit":(715,"SINS", ItemClassification.filler),
"Suit - The Scarlet Suit":(727,"SINS", ItemClassification.filler),
"Suit - The Narcissus Suit":(734,"SINS", ItemClassification.filler),
"Suit - The Lotophage Suit":(739,"SINS", ItemClassification.filler),
"Suit - The Tempter Suit":(745,"SINS", ItemClassification.filler),
"Melee - IO Elite S2VP Earphones":(385,"SMART_CASUAL", ItemClassification.filler),
"Suit - Smart Casual Suit":(801,"SMART_CASUAL", ItemClassification.filler),
"Tool - ICA Flash Phone":(330,"SMART_CASUAL,H2_RACCOON_STINGRAY", ItemClassification.filler),
"Melee - Okinawan Tonfa":(422,"LEGACY", ItemClassification.filler),
"Pistol - FIREARMS_PISTOL_BIRTH_BALLER":(236,"TRINITY", ItemClassification.filler),
"Pistol - FIREARMS_PISTOL_DEATH_BALLER":(247,"TRINITY", ItemClassification.filler),
"Pistol - FIREARMS_PISTOL_LIFE_BALLER":(251,"TRINITY", ItemClassification.filler),
"Suitcase - PROP_CONTAINER_SUITCASE_BIRTH":(280,"TRINITY", ItemClassification.filler),
"Suitcase - PROP_CONTAINER_SUITCASE_DEATH":(282,"TRINITY", ItemClassification.filler),
"Suitcase - PROP_CONTAINER_SUITCASE_LIFE":(291,"TRINITY", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_HERO_BIRTH_SUIT":(704,"TRINITY", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_HERO_DEATH_SUIT":(710,"TRINITY", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_HERO_LIFE_SUIT":(726,"TRINITY", ItemClassification.filler),
"Shotgun - The Maximalist Shotgun":(216,"SINS", ItemClassification.filler),
"Pistol - FIREARMS_PISTOL_DARTGUN":(241,"unknown", ItemClassification.filler),
"Explosive - PROP_DEVICE_REMOTE_EXPLOSIVE_ANCESTRAL":(355,"unknown", ItemClassification.filler),
"Melee - Eiffel Tower Souvenir":(399,"unknown", ItemClassification.filler),
"Poision - \"Bubble Queen\"Gum Pack":(450,"SINS", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_ANCESTRAL_HERO_ANCESTRALSUIT":(684,"unknown", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_ANCESTRAL_HERO_SMOOTHSNAKESUIT":(685,"unknown", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_COLOMBIA_HERO_COLOMBIASUIT":(690,"unknown", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_EDGY_HERO_EDGYSUIT":(692,"unknown", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_ELEGANT_HERO_LLAMASUIT":(693,"unknown", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_HERO_EASTER_RAVER_BUNNY_SUIT":(712,"unknown", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_HERO_GECKO_SUIT":(717,"unknown", ItemClassification.filler),
"Suit - The Profligacy Suit":(718,"SINS", ItemClassification.filler),
"Suit - The Rapacious Suit":(720,"unknown", ItemClassification.filler),
"Suit - Solstice Suit":(723,"unknown", ItemClassification.filler),
"Suit - Recon Gear":(749,"unknown", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_MIAMI_HERO_MIAMISUIT":(761,"unknown", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_MUMBAI_HERO_MUMBAISUIT":(764,"unknown", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_NEWZEALAND_HERO_NEWZEALANDSUIT":(765,"unknown", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_NORTHAMERICA_HERO_NORTHAMERICASUIT":(768,"unknown", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_NORTHSEA_HERO_NORTHSEASUIT":(769,"unknown", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_TRAPPED_WOLVERINE_SUIT":(800,"unknown", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_WELCOME_SUIT":(802,"unknown", ItemClassification.filler),
"Suit - TOKEN_OUTFIT_WET_HERO_WETSUIT":(803,"unknown", ItemClassification.filler),
"Agency Pickup - Bangkok - AGENCYPICKUP_BANGKOK_TIGER_MEDITATION":(16,"unknown", ItemClassification.filler),
"Hidden Stash - Paris - AGENCYPICKUP_PARIS_OFFICE_CURTAINS":(131,"unknown", ItemClassification.filler),
"Suit - Casual Suit":(687,"unknown,LEGACY", ItemClassification.filler),
"Suit - Ninja":(751,"unknown,LEGACY", ItemClassification.filler),
"Suit - Summer Suit":(760,"unknown,LEGACY", ItemClassification.filler),
"Suit - Tuxedo":(772,"unknown,LEGACY", ItemClassification.filler),
"Suit - Italian Suit":(795,"unknown,LEGACY", ItemClassification.filler),
"Suit - Italian Suit (No Glasses)":(796,"unknown,LEGACY", ItemClassification.filler),
"Suitcase - Artic Toolbox":(279,"WINTER_SPORTS", ItemClassification.filler),
"Melee - Piton":(426,"WINTER_SPORTS", ItemClassification.filler),
"Melee - Quickdraw":(428,"WINTER_SPORTS", ItemClassification.filler),
"Melee - Snowball":(434,"WINTER_SPORTS", ItemClassification.filler),
"Suit - Winter Sports Suit":(686,"WINTER_SPORTS", ItemClassification.filler),
"Suit - The Black Bruiser Suit":(179,"", ItemClassification.filler),
"Suit - The Master Freelancer Suit":(180,"", ItemClassification.filler),
"Suit - The Gauze Suit":(181,"", ItemClassification.filler),
"Pistol - \"El Matador\"":(183,"", ItemClassification.filler),
"Pistol - The Floral Baller":(184,"", ItemClassification.filler),
"Pistol - Krugermeier 2-2 Silver":(188,"", ItemClassification.filler),
"Pistol - Krugermeier 2-2 Dark":(189,"", ItemClassification.filler),
"Pistol - ICA19 Shortballer":(191,"", ItemClassification.filler),
"Pistol - HWK21 Pale Homemade Silencer":(192,"", ItemClassification.filler),
"Pistol - Striker V3":(193,"", ItemClassification.filler),
"Pistol - ICA19":(195,"", ItemClassification.useful),
"Pistol - ICA19 F/A Stealth \"Ducky\" Edition":(199,"", ItemClassification.filler),
"Assault Rifle - Shashka A33 H":(201,"", ItemClassification.filler),
"Assault Rifle - Shashka A33 Gold":(208,"", ItemClassification.filler),
"Assault Rifle - Sieger AR552 Tactical":(210,"", ItemClassification.filler),
"Assault Rifle - TAC-4 AR MKII":(211,"", ItemClassification.filler),
"Shotgun - Bartoli 12G Short H":(212,"", ItemClassification.filler),
"Shotgun - Golden Sawed-Off Bartoli 12G":(214,"", ItemClassification.filler),
"Shotgun - Enram HV Covert MKII":(215,"", ItemClassification.filler),
"Shotgun - ICA Tactical Shotgun Covert":(220,"", ItemClassification.filler),
"Shotgun - ICA Tactical White Shotgun Covert":(221,"", ItemClassification.filler),
"SMG - DAK X2 Covert Special":(223,"", ItemClassification.filler),
"SMG - TAC-SMAG MKII":(225,"", ItemClassification.filler),
"SMG - TAC-SMG Covert":(226,"", ItemClassification.filler),
"Sniper - Jaeger 7 Covert":(228,"", ItemClassification.filler),
"Sniper - Jaeger 7 MKII":(232,"", ItemClassification.filler),
"Sniper - Bartoli Woodsman Hunting Rifle":(235,"", ItemClassification.filler),
"Pistol - ICA19 Classicballer":(237,"", ItemClassification.filler),
"Pistol - Concept 5":(238,"", ItemClassification.filler),
"Pistol - Custom 5mm DTI":(239,"", ItemClassification.filler),
"Pistol - The Ducky Gun":(240,"", ItemClassification.filler),
"Pistol - Kalmer 1 - Tranquilizer":(243,"", ItemClassification.useful),
"Pistol - Kalmer 2 -Tranquilizer":(245,"", ItemClassification.filler),
"Pistol - ICA19 Goldballer":(248,"", ItemClassification.filler),
"Pistol - HWK21 MK II":(249,"", ItemClassification.filler),
"Pistol - ICA DTI Stealth":(250,"", ItemClassification.filler),
"Pistol - \"Rude Ruby\"":(252,"", ItemClassification.filler),
"Pistol - The Purple Streak ICA19 Classic Baller":(253,"", ItemClassification.filler),
"Pistol - ICA19 Silverballer MK II":(254,"", ItemClassification.filler),
"Shotgun - ICA Tactical Shotgun":(256,"", ItemClassification.filler),
"SMG - Brine-Damaged SMG":(257,"", ItemClassification.filler),
"SMG - Malitia-Issued HX-10 SMG":(258,"", ItemClassification.filler),
"SMG - ICA SMG Raptor Covert":(259,"", ItemClassification.filler),
"SMG - SMG Raptor Rude Ruby Covert":(260,"", ItemClassification.filler),
"SMG - DAK Black Covert":(261,"", ItemClassification.filler),
"Sniper - Druzhina 34":(264,"", ItemClassification.filler),
"Sniper - Druzhina 34 ICA Arctic":(265,"", ItemClassification.filler),
"Sniper - Druzhina 34 DTI":(266,"", ItemClassification.filler),
"Sniper - ICA Bartoli Woodsman Hunting Rifle Covert":(267,"", ItemClassification.filler),
"Sniper - Hackl Leviathan Sniper Rifle Covert":(268,"", ItemClassification.filler),
"Sniper - Hackl Sniper Riffle Covert \"Ducky\" Edition":(269,"", ItemClassification.filler),
"Sniper - Siger 300 Viper":(272,"", ItemClassification.filler),
"Sniper - The White Ruby Rude 300 Sniper Rifle":(274,"", ItemClassification.filler),
"Sniper - Sieger 300 Tactical":(276,"", ItemClassification.filler),
"Suitcase - ICA Briefcase":(285,"", ItemClassification.useful),
"Suitcase - Black Leather Briefcase":(286,"", ItemClassification.filler),
"Suitcase - ICA Briefcase MK III":(288,"", ItemClassification.filler),
"Suitcase - Orange Pinstripe Briefcase":(289,"", ItemClassification.filler),
"Suitcase - The Purple Streak ICA Briefcase":(290,"", ItemClassification.filler),
"Suitcase - Siger 300 Sniper Case":(292,"", ItemClassification.filler),
"Suitcase - ICA Executive Briefcase MK II":(293,"", ItemClassification.filler),
"Suitcase - Toolbox":(294,"", ItemClassification.filler),
"Suitcase - Aluminum Travel Briefcase":(295,"", ItemClassification.filler),
"Suitcase - Aluminum Travel Briefcase (H3)":(296,"", ItemClassification.filler),
"Explosive - Remove Explosive Devil Rubber Duck":(299,"", ItemClassification.filler),
"Tool - Oil Canister":(300,"", ItemClassification.filler),
"Explosive - Explosive Pen":(301,"", ItemClassification.filler),
"Explosive - Remote Explosive Classic Rubber Duck":(305,"", ItemClassification.filler),
"Explosive - Proximity Lucky Cat Figurine":(306,"", ItemClassification.filler),
"Distraction - ICA Remote Micro Audio Distraction":(307,"", ItemClassification.filler),
"Explosive - ICA Proximity Micro Explosive":(308,"", ItemClassification.filler),
"Explosive - ICA Micro Remote Explosive":(309,"", ItemClassification.filler),
"Explosive - Breaching Charge MK III":(310,"", ItemClassification.filler),
"Tool - Proximity EMP Charge":(311,"", ItemClassification.filler),
"Explosive - ICA Proximity Explosive MK II":(313,"", ItemClassification.filler),
"Tool - ICA Proximity Micro Taser":(314,"", ItemClassification.filler),
"Explosive - Breaching Charge MK II":(317,"", ItemClassification.filler),
"Tool - Remote EMP Charge":(318,"", ItemClassification.filler),
"Explosive - ICA Remote Explosive MK II":(320,"", ItemClassification.filler),
"Explosive - ICA Remote Explosive MK III":(321,"", ItemClassification.filler),
"Explosive - ICA Proximity Explosive MK III":(324,"", ItemClassification.filler),
"Explosive - Proximity CX Demo Block MK II":(325,"", ItemClassification.filler),
"Tool - ICA Proximity Taser":(326,"", ItemClassification.filler),
"Distraction - ICA Remote Audio Distraction MKII":(327,"", ItemClassification.filler),
"Distraction - ICA Remote Audio Distraction MKIII":(328,"", ItemClassification.filler),
"Tool - ICA Remote Micro Taser":(332,"", ItemClassification.filler),
"Explosive - Remote CX Demo Block MK II":(333,"", ItemClassification.filler),
"Tool - ICA Remote Taser":(334,"", ItemClassification.filler),
"Explosive - RFID Triggered Explosive":(335,"", ItemClassification.filler),
"Tool - RFID Triggered Taser":(336,"", ItemClassification.filler),
"Explosive - Proximity Explosive Rubber Duck MK II":(337,"", ItemClassification.filler),
"Explosive - Remote Explosive Rubber Duck MK II":(338,"", ItemClassification.filler),
"Explosive - Proximity Explosive Duck MK III":(340,"", ItemClassification.filler),
"Explosive - Sunset Rubber Duck":(342,"", ItemClassification.filler),
"Explosive - The Purple Streak Explosive Duck":(343,"", ItemClassification.filler),
"Explosive - Proximity Semtex Demo Block MK III":(344,"", ItemClassification.filler),
"Explosive - Remote Semetex Demo Block MK III":(345,"", ItemClassification.filler),
"Explosive - ICA Tripwire Mine":(346,"", ItemClassification.filler),
"Tool - Electronic Key Hacker":(347,"", ItemClassification.useful),
"Tool - Electronic Key Hacker MK III":(348,"", ItemClassification.filler),
"Explosive - ICA Proximity Concussion Device":(351,"", ItemClassification.filler),
"Explosive - ICA Proximity Concussion Device MK III":(352,"", ItemClassification.filler),
"Explosive - ICA Remote Concussion Device":(354,"", ItemClassification.filler),
"Explosive - Remote Concussion Rubber Duck":(357,"", ItemClassification.filler),
"Explosive - Remote Concussion Collectors Duck":(358,"COLLECTORS", ItemClassification.filler),
"Poision - ICA Pen Syringe Emetic":(361,"", ItemClassification.filler),
"Explosive - Explosive Baseball":(363,"", ItemClassification.filler),
"Explosive - Explosive Golf Ball":(365,"", ItemClassification.filler),
"Explosive - Concussion Grenade":(366,"", ItemClassification.filler),
"Explosive - Flash Grenade":(367,"", ItemClassification.filler),
"Explosive - Flash Grenade MK III":(368,"", ItemClassification.filler),
"Explosive - Fragmentation Grenade":(369,"", ItemClassification.filler),
"Explosive - Molotov Cocktail":(370,"", ItemClassification.filler),
"Explosive - ICA Impact Explosive":(371,"", ItemClassification.filler),
"Explosive - Magnesium Pouch":(372,"", ItemClassification.filler),
"Explosive - Nitroglycerin":(373,"", ItemClassification.filler),
"Explosive - Shaman Powder":(374,"", ItemClassification.filler),
"Tool - Emetic Grenade":(375,"", ItemClassification.filler),
"Tool - Emetic Gas Grenade":(376,"", ItemClassification.useful),
"Melee - Antique Carved Knife":(379,"", ItemClassification.filler),
"Melee - ICA combat axe":(382,"", ItemClassification.filler),
"Melee - Banana":(383,"", ItemClassification.filler),
"Melee - The Purple Streak Baseball Bat":(384,"", ItemClassification.filler),
"Poision - Blue Easter Egg":(386,"", ItemClassification.filler),
"Melee - Burial Dagger":(387,"", ItemClassification.filler),
"Melee - Meat Hook":(388,"", ItemClassification.filler),
"Melee - Butcher's Saw":(389,"", ItemClassification.filler),
"Melee - Walking Cane":(390,"", ItemClassification.filler),
"Melee - Fiber  Wire Classic":(393,"", ItemClassification.filler),
"Melee - Hook":(397,"", ItemClassification.filler),
"Melee - Durian":(398,"", ItemClassification.filler),
"Melee - Feather Duster":(401,"", ItemClassification.filler),
"Melee - Fish":(402,"", ItemClassification.filler),
"Melee - Fishing Line":(403,"", ItemClassification.filler),
"Melee - Hobby Knife":(405,"", ItemClassification.filler),
"Melee - Ice Axe":(406,"", ItemClassification.filler),
"Melee - The Iridescent Katana":(410,"", ItemClassification.filler),
"Melee - Kukri Knife":(412,"", ItemClassification.filler),
"Melee - Broadsword":(414,"", ItemClassification.filler),
"Melee - Mace":(415,"", ItemClassification.filler),
"Melee - Kukri Machette":(417,"", ItemClassification.filler),
"Melee - Measuring Tape":(418,"", ItemClassification.filler),
"Melee - Meaty Bone":(419,"", ItemClassification.filler),
"Melee - Claw Hammer":(420,"", ItemClassification.filler),
"Melee - Blueberry Muffin":(421,"", ItemClassification.filler),
"Melee - Pinot Noir":(424,"", ItemClassification.filler),
"Melee - Sacrificial Knife":(429,"", ItemClassification.filler),
"Melee - Ornate Scimitar":(430,"", ItemClassification.filler),
"Melee - Burj Al-Ghazali Snowglobe":(431,"", ItemClassification.filler),
"Melee - Bat Shuriken":(433,"", ItemClassification.filler),
"Poision - Emetic Syringe Mk II":(436,"", ItemClassification.filler),
"Poision - Lethal Syringe Mk II":(438,"", ItemClassification.filler),
"Poision - Lethal Syringe Mk III":(439,"", ItemClassification.filler),
"Melee - Tanto":(441,"", ItemClassification.filler),
"Melee - Unicorn Horn":(443,"", ItemClassification.filler),
"Melee - Violin":(444,"", ItemClassification.filler),
"Poision - Lethal Pills MK III":(445,"", ItemClassification.filler),
"Poision - Emetic Poison Vial  MK III":(446,"", ItemClassification.filler),
"Poision - Emetic Pills":(447,"", ItemClassification.filler),
"Poision - Lethal Pills":(448,"", ItemClassification.filler),
"Poision - Sedative Pills":(449,"", ItemClassification.filler),
"Poision - Sedative Poision Vial MK III":(451,"", ItemClassification.filler),
"Poision - Lethal Poison Vial MK III":(453,"", ItemClassification.filler),
"Tool - ICA Titanium Crowbar":(456,"", ItemClassification.filler),
"Distraction - Coin":(457,"", ItemClassification.useful),
"Distraction - Classic Coin":(458,"", ItemClassification.filler),
"Distraction - ICA Commendable Service Coin":(459,"", ItemClassification.filler),
"Distraction - ICA Commendable Performance Coin":(460,"", ItemClassification.filler),
"Distraction - Gold Coin":(463,"", ItemClassification.filler),
"Distraction - ICA Outstanding Performance Coin":(464,"", ItemClassification.filler),
"Tool - Bone Lockpick":(467,"", ItemClassification.filler),
"Tool - Classic Lockpick":(468,"", ItemClassification.filler),
"Tool - Lockpick MK II":(469,"", ItemClassification.filler),
"Tool - Lockpick MK III":(470,"", ItemClassification.filler),
"Distraction - ICA Outstanding Service Coin":(471,"", ItemClassification.filler),
"Tool - Professional Screwdriver":(472,"", ItemClassification.filler),
"Distraction - ICA Superior Performance Coin":(473,"", ItemClassification.filler),
"Distraction - Red-Tie Kiwi":(474,"", ItemClassification.filler),
"Distraction - ICA Superior Service Coin":(475,"", ItemClassification.filler),
"Tool - Handyman Wrench":(476,"", ItemClassification.filler),
"Suit - The Sniper Challange Suit":(477,"", ItemClassification.filler),
"Starting Location - Dartmoor - STARTING_LOCATION_ANCESTRAL_FERN_BEHINDMANSION_HUNTINGSUIT_B":(486,"unsued", ItemClassification.filler),
"Starting Location - Dartmoor - STARTING_LOCATION_ANCESTRAL_SMOOTHSNAKE_FRONTMANSION_SUIT":(487,"unsued", ItemClassification.filler),
"Starting Location - Dartmoor - STARTING_LOCATION_ANCESTRAL_SMOOTHSNAKE_FRONTMANSION_SUIT_B":(488,"unsued", ItemClassification.filler),
"Starting Location - STARTING_LOCATION_BELLFLOWER_LEVEL1":(498,"unsued", ItemClassification.filler),
"Starting Location - STARTING_LOCATION_BELLFLOWER_LEVEL2":(499,"unsued", ItemClassification.filler),
"Starting Location - STARTING_LOCATION_BELLFLOWER_LEVEL3":(500,"unsued", ItemClassification.filler),
"Starting Location - Santa Fortuna - STARTING_LOCATION_COLOMBIA_CALLUNA_COCAFIELD":(502,"unsued", ItemClassification.filler),
"Starting Location - Santa Fortuna - STARTING_LOCATION_COLOMBIA_OUTBREAK_CAVES":(511,"unsued", ItemClassification.filler),
"Starting Location - Santa Fortuna - STARTING_LOCATION_COLOMBIA_OUTBREAK_COCAFIELDS":(512,"unsued", ItemClassification.filler),
"Starting Location - Santa Fortuna - STARTING_LOCATION_COLOMBIA_OUTBREAK_FISHING_VILLAGE":(513,"unsued", ItemClassification.filler),
"Starting Location - Santa Fortuna - STARTING_LOCATION_COLOMBIA_OUTBREAK_VILLAGE":(514,"unsued", ItemClassification.filler),
"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_AMBROSIA":(523,"unsued", ItemClassification.filler),
"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_CORNFLOWER_LEVEL1":(528,"unsued", ItemClassification.filler),
"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_CORNFLOWER_LEVEL2":(529,"unsued", ItemClassification.filler),
"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_CORNFLOWER_LEVEL3":(530,"unsued", ItemClassification.filler),
"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_DEFAULT_CONTRACTCREATION":(532,"unsued", ItemClassification.filler),
"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_GRASSSNAKE_EVENTAREA":(535,"unsued", ItemClassification.filler),
"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_GRASSSNAKE_FORRESTEDGE":(536,"unsued", ItemClassification.filler),
"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_NIGHTPHLOX_B1_BAR":(537,"unsued", ItemClassification.filler),
"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_NIGHTPHLOX_CHILLOUT_AREA":(538,"unsued", ItemClassification.filler),
"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_NIGHTPHLOX_CLUB_ENTRANCE":(539,"unsued", ItemClassification.filler),
"Starting Location - Berlin - STARTING_LOCATION_EDGY_FOX_NIGHTPHLOX_DJ_BOOTH":(540,"unsued", ItemClassification.filler),
"Starting Location - Berlin - STARTING_LOCATION_EDGY_RADLER_CLUB_ENTRANCE":(541,"unsued", ItemClassification.filler),
"Starting Location - Berlin - STARTING_LOCATION_EDGY_TOMORROWLAND_CLUB_ENTRANCE":(542,"unsued", ItemClassification.filler),
"Starting Location - Mendoza - STARTING_LOCATION_ELEGANT_LLAMA_FRANGIPANI_PARKING":(546,"unsued", ItemClassification.filler),
"Starting Location - Mendoza - STARTING_LOCATION_ELEGANT_LLAMA_JACARANDA_DOCKS":(547,"unsued", ItemClassification.filler),
"Starting Location - Mendoza - STARTING_LOCATION_ELEGANT_NODIANA_DEFAULT_SUIT":(552,"unsued", ItemClassification.filler),
"Starting Location - Dubai - STARTING_LOCATION_GOLDEN_ANGELICA_GOLDBAR":(553,"unsued", ItemClassification.filler),
"Starting Location - Dubai - STARTING_LOCATION_GOLDEN_GIBSON_INSIDE_DEFAULT":(560,"unsued", ItemClassification.filler),
"Starting Location - New York - STARTING_LOCATION_GREEDY_RACCOON_DANDELION_GARAGE_ENTRANCE":(562,"unsued", ItemClassification.filler),
"Starting Location - Hokkaido - STARTING_LOCATION_HOKKAIDO_MAMUSHI":(570,"unsued", ItemClassification.filler),
"Starting Location - STARTING_LOCATION_HOLLYHOCK_DEFAULT":(580,"unsued", ItemClassification.filler),
"Starting Location - STARTING_LOCATION_MAGNOLIA":(581,"unsued", ItemClassification.filler),
"Starting Location - STARTING_LOCATION_MANTIS_OUTBREAK_ROOF":(582,"unsued", ItemClassification.filler),
"Starting Location - Marrakesh - STARTING_LOCATION_MARRAKESH_DARK_ROOFTOP":(583,"unsued", ItemClassification.filler),
"Starting Location - Miami - STARTING_LOCATION_MIAMI_SAMBUCA_EXPO":(603,"unsued", ItemClassification.filler),
"Starting Location - Hawkes Bay - STARTING_LOCATION_NEWZEALAND_BED":(619,"unsued", ItemClassification.filler),
"Starting Location - Hawkes Bay - STARTING_LOCATION_NEWZEALAND_HUT":(621,"unsued", ItemClassification.filler),
"Starting Location - Whittleton Creek - STARTING_LOCATION_NORTHAMERICA_SKUNK_OUTBREAK_HELICOPTER":(629,"unsued", ItemClassification.filler),
"Starting Location - STARTING_LOCATION_OPULENT_ARCTICTHYME_PIRATE":(630,"unsued", ItemClassification.filler),
"Starting Location - Paris - STARTING_LOCATION_PARIS_WATER":(645,"unsued", ItemClassification.filler),
"Starting Location - Isle of Sgail - STARTING_LOCATION_THE_ISLAND_MAGPIE_LOTUS":(668,"unsued", ItemClassification.filler),
"Starting Location - Chongqing - STARTING_LOCATION_WET_LAMBIC_DEFAULT":(675,"unsued", ItemClassification.filler),
"Melee - Fiber Wire":(683,"", ItemClassification.filler),
"Suit - Classic All-Black Suit":(689,"", ItemClassification.filler),
"Suit - The Undying Look":(694,"", ItemClassification.filler),
"Suit - Casual Undercover":(695,"", ItemClassification.filler),
"Suit - Florida Fit With Gloves":(696,"", ItemClassification.filler),
"Suit - Phantom Suit":(697,"", ItemClassification.filler),
"Suit - The Arkian Tuxedo":(698,"", ItemClassification.filler),
"Suit - The Big, Bad Wolf Suit":(703,"", ItemClassification.filler),
"Suit - The Black Streak Suit":(705,"", ItemClassification.filler),
"Suit - The Blue Streak Suit":(706,"", ItemClassification.filler),
"Suit - The Butcher":(707,"", ItemClassification.filler),
"Suit - Guerilla Wetsuit":(711,"", ItemClassification.filler),
"Suit - The Raver":(713,"", ItemClassification.filler),
"Suit - The Yellow Rabbit":(714,"", ItemClassification.filler),
"Suit - Freedom Phantom Suit":(716,"", ItemClassification.filler),
"Suit - The Green Streak Suit":(721,"", ItemClassification.filler),
"Suit - Lynch Suit":(728,"", ItemClassification.filler),
"Suit - Futo Suit":(730,"", ItemClassification.filler),
"Suit - Plague Doctor":(733,"", ItemClassification.filler),
"Suit - The Purple Streak Suit":(735,"", ItemClassification.filler),
"Suit - White Sunset Suit":(736,"", ItemClassification.filler),
"Suit - Summer Sightseeing Suit With Gloves":(740,"", ItemClassification.filler),
"Suit - Super Fan":(741,"", ItemClassification.filler),
"Suit - Terminus":(742,"", ItemClassification.filler),
"Suit - Winter Suit":(744,"", ItemClassification.filler),
"Suit - Casual Tourist With Gloves":(746,"", ItemClassification.filler),
"Suit - 47's Signature Suit":(747,"", ItemClassification.filler),
"Suit - Summer Suave Suit":(752,"", ItemClassification.filler),
"Suit - The Purple Streak Boxer Suit":(753,"", ItemClassification.filler),
"Suit - Absolution Suit":(754,"", ItemClassification.filler),
"Suit - Blood Money Suit with Gloves":(755,"", ItemClassification.filler),
"Suit - 47's Signature Suit with Gloves":(757,"", ItemClassification.filler),
"Suit - Tuxedo, Mask and Gloves":(758,"", ItemClassification.filler),
"Suit - Imperial Classic With Gloves":(763,"", ItemClassification.filler),
"Suit - The Jack-O'-Lantern Suit":(766,"", ItemClassification.filler),
"Suit - Subburban Suit With Driving Gloves":(767,"", ItemClassification.filler),
"Suit - Black Winter Suit":(773,"", ItemClassification.filler),
"Suit - Blue Flamingo Suit":(774,"", ItemClassification.filler),
"Suit - Agent 17's Signature Suit":(775,"", ItemClassification.filler),
"Suit - Classic Cut Long Coat Suit With Gloves":(776,"", ItemClassification.filler),
"Suit - The Cozy Christmas Suit":(777,"", ItemClassification.filler),
"Suit - The Lucky Ducky Suit":(778,"", ItemClassification.filler),
"Suit - Number Six With Gloves":(780,"", ItemClassification.filler),
"Suit - Ashen Suit With Gloves":(781,"", ItemClassification.filler),
"Suit - The Sandman Suit":(782,"", ItemClassification.filler),
"Suit - The Splitter Suit":(783,"", ItemClassification.filler),
"Suit - The Codename 47 Suit":(784,"", ItemClassification.filler),
"Suit - Black & White Tuxedo Set With Gloves":(785,"", ItemClassification.filler),
"Suit - The Neon Ninja Suit":(786,"", ItemClassification.filler),
"Suit - The Disruptor MMA Suit":(787,"", ItemClassification.filler),
"Suit - The Public Enemy Suit":(788,"", ItemClassification.filler),
"Suit - Neon City Suit With Gloves":(789,"", ItemClassification.filler),
"Suit - Rave On Suit":(790,"", ItemClassification.filler),
"Suit - The Ruby Rude Track Suit":(791,"", ItemClassification.filler),
"Suit - The Ephemeral Suit":(792,"", ItemClassification.filler),
"Suit - Subject 47":(793,"", ItemClassification.filler),
"Suit - The Greek Fire Suit":(799,"", ItemClassification.filler),
"Suit - Tactical Wetsuit":(804,"", ItemClassification.filler),
"Suit - Trendy Tourist Suit":(805,"", ItemClassification.filler),
"Suit - The Krampus Little Helper Suit":(828,"", ItemClassification.filler)
}

item_table["Contract Piece"] = (1000,"contract_mode",ItemClassification.progression)