from BaseClasses import Location

class HitmanLocation(Location):
    game: str = "HITMAN World of Assasination"

location_table = { #id, location entitlments (one of required), settings requirement (one of required), required items (one of)
"Itempickup - Crowbar":(1,["ica_facility","paris","sapienza","marrakesh","bangkok","colorado","hokkaido","miami","santa_fortuna","mumbai","whittleton_creek","ambrose_island","isle_of_sgail","new_york","haven_island","dubai","dartmoor","berlin","chongqing","mendoza"], ["itemsanity"], ["Level - ICA Facility", "Level - Paris", "Level - Sapienza", "Level - Marrakesh", "Level - Bangkok", "Level - Colorado", "Level - Hokkaido", "Level - Miami", "Level - Santa Fortuna", "Level - Mumbai", "Level - Whittleton Creek", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - New York", "Level - Haven Island", "Level - Dubai", "Level - Dartmoor", "Level - Berlin", "Level - Chongqing", "Level - Mendoza"]),
"Itempickup - Hammer":(2,["ica_facility","paris","sapienza","marrakesh","bangkok","colorado","hokkaido","miami","santa_fortuna","mumbai","whittleton_creek","ambrose_island","isle_of_sgail","haven_island","dubai","dartmoor","berlin","chongqing"], ["itemsanity"], ["Level - ICA Facility", "Level - Paris", "Level - Sapienza", "Level - Marrakesh", "Level - Bangkok", "Level - Colorado", "Level - Hokkaido", "Level - Miami", "Level - Santa Fortuna", "Level - Mumbai", "Level - Whittleton Creek", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - Haven Island", "Level - Dubai", "Level - Dartmoor", "Level - Berlin", "Level - Chongqing"]),
"Itempickup - Coin":(3,["ica_facility","paris","sapienza","marrakesh","bangkok","colorado","hokkaido","hawkes_bay","miami","santa_fortuna","mumbai","whittleton_creek","ambrose_island","isle_of_sgail","new_york","haven_island","dubai","dartmoor","berlin","chongqing","mendoza"], ["itemsanity"], ["Level - ICA Facility", "Level - Paris", "Level - Sapienza", "Level - Marrakesh", "Level - Bangkok", "Level - Colorado", "Level - Hokkaido", "Level - Hawkes Bay", "Level - Miami", "Level - Santa Fortuna", "Level - Mumbai", "Level - Whittleton Creek", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - New York", "Level - Haven Island", "Level - Dubai", "Level - Dartmoor", "Level - Berlin", "Level - Chongqing", "Level - Mendoza"]),
"Itempickup - Emetic Rat Poison":(4,["ica_facility","sapienza","marrakesh","bangkok","colorado","hokkaido","hawkes_bay","miami","santa_fortuna","mumbai","whittleton_creek","ambrose_island","isle_of_sgail","new_york","haven_island","dubai","dartmoor","berlin","chongqing","mendoza"], ["itemsanity"], ["Level - ICA Facility", "Level - Sapienza", "Level - Marrakesh", "Level - Bangkok", "Level - Colorado", "Level - Hokkaido", "Level - Hawkes Bay", "Level - Miami", "Level - Santa Fortuna", "Level - Mumbai", "Level - Whittleton Creek", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - New York", "Level - Haven Island", "Level - Dubai", "Level - Dartmoor", "Level - Berlin", "Level - Chongqing", "Level - Mendoza"]),
"Itempickup - Wrench":(5,["ica_facility","paris","sapienza","marrakesh","bangkok","colorado","hokkaido","hawkes_bay","miami","santa_fortuna","mumbai","whittleton_creek","ambrose_island","isle_of_sgail","new_york","haven_island","dubai","dartmoor","berlin","chongqing","mendoza"], ["itemsanity"], ["Level - ICA Facility", "Level - Paris", "Level - Sapienza", "Level - Marrakesh", "Level - Bangkok", "Level - Colorado", "Level - Hokkaido", "Level - Hawkes Bay", "Level - Miami", "Level - Santa Fortuna", "Level - Mumbai", "Level - Whittleton Creek", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - New York", "Level - Haven Island", "Level - Dubai", "Level - Dartmoor", "Level - Berlin", "Level - Chongqing", "Level - Mendoza"]),
"Itempickup - Lead Pipe":(6,["ica_facility","paris","sapienza","bangkok","colorado","hokkaido","hawkes_bay","miami","santa_fortuna","mumbai","whittleton_creek","ambrose_island","isle_of_sgail","new_york","haven_island","dartmoor","berlin","chongqing"], ["itemsanity"], ["Level - ICA Facility", "Level - Paris", "Level - Sapienza", "Level - Bangkok", "Level - Colorado", "Level - Hokkaido", "Level - Hawkes Bay", "Level - Miami", "Level - Santa Fortuna", "Level - Mumbai", "Level - Whittleton Creek", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - New York", "Level - Haven Island", "Level - Dartmoor", "Level - Berlin", "Level - Chongqing"]),
"Itempickup - Pool Ball":(7,["ica_facility","marrakesh","bangkok","santa_fortuna","new_york","dartmoor","berlin"], ["itemsanity"], ["Level - ICA Facility", "Level - Marrakesh", "Level - Bangkok", "Level - Santa Fortuna", "Level - New York", "Level - Dartmoor", "Level - Berlin"]),
"Itempickup - Brick":(8,["ica_facility","paris","sapienza","marrakesh","colorado","miami","santa_fortuna","mumbai","whittleton_creek","ambrose_island","isle_of_sgail","dartmoor","berlin","chongqing","mendoza","carpathian_mountains"], ["itemsanity"], ["Level - ICA Facility", "Level - Paris", "Level - Sapienza", "Level - Marrakesh", "Level - Colorado", "Level - Miami", "Level - Santa Fortuna", "Level - Mumbai", "Level - Whittleton Creek", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - Dartmoor", "Level - Berlin", "Level - Chongqing", "Level - Mendoza", "Level - Carpathian Mountains"]),
"Itempickup - Bust":(9,["ica_facility","paris","sapienza","hokkaido","hawkes_bay","miami","whittleton_creek","isle_of_sgail","new_york","dartmoor"], ["itemsanity"], ["Level - ICA Facility", "Level - Paris", "Level - Sapienza", "Level - Hokkaido", "Level - Hawkes Bay", "Level - Miami", "Level - Whittleton Creek", "Level - Isle of Sgail", "Level - New York", "Level - Dartmoor"]),
"Itempickup - Scissors":(10,["paris","sapienza","marrakesh","hokkaido","hawkes_bay","miami","santa_fortuna","mumbai","whittleton_creek","ambrose_island","isle_of_sgail","new_york","haven_island","dubai","dartmoor","chongqing"], ["itemsanity"], ["Level - Paris", "Level - Sapienza", "Level - Marrakesh", "Level - Hokkaido", "Level - Hawkes Bay", "Level - Miami", "Level - Santa Fortuna", "Level - Mumbai", "Level - Whittleton Creek", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - New York", "Level - Haven Island", "Level - Dubai", "Level - Dartmoor", "Level - Chongqing"]),
"Itempickup - Screwdriver":(11,["paris","sapienza","marrakesh","bangkok","colorado","hokkaido","hawkes_bay","miami","santa_fortuna","mumbai","whittleton_creek","ambrose_island","isle_of_sgail","new_york","haven_island","dubai","dartmoor","berlin","chongqing","mendoza"], ["itemsanity"], ["Level - Paris", "Level - Sapienza", "Level - Marrakesh", "Level - Bangkok", "Level - Colorado", "Level - Hokkaido", "Level - Hawkes Bay", "Level - Miami", "Level - Santa Fortuna", "Level - Mumbai", "Level - Whittleton Creek", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - New York", "Level - Haven Island", "Level - Dubai", "Level - Dartmoor", "Level - Berlin", "Level - Chongqing", "Level - Mendoza"]),
"Itempickup - Letter Opener":(12,["paris","sapienza","marrakesh","bangkok","santa_fortuna","mumbai","whittleton_creek","ambrose_island","isle_of_sgail","new_york","haven_island","dubai","dartmoor","chongqing"], ["itemsanity"], ["Level - Paris", "Level - Sapienza", "Level - Marrakesh", "Level - Bangkok", "Level - Santa Fortuna", "Level - Mumbai", "Level - Whittleton Creek", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - New York", "Level - Haven Island", "Level - Dubai", "Level - Dartmoor", "Level - Chongqing"]),
"Itempickup - Fire Axe":(13,["paris","sapienza","marrakesh","bangkok","hokkaido","miami","mumbai","whittleton_creek","isle_of_sgail","new_york","haven_island","dubai","berlin","chongqing","mendoza","carpathian_mountains"], ["itemsanity"], ["Level - Paris", "Level - Sapienza", "Level - Marrakesh", "Level - Bangkok", "Level - Hokkaido", "Level - Miami", "Level - Mumbai", "Level - Whittleton Creek", "Level - Isle of Sgail", "Level - New York", "Level - Haven Island", "Level - Dubai", "Level - Berlin", "Level - Chongqing", "Level - Mendoza", "Level - Carpathian Mountains"]),
"Itempickup - Fusil G2":(14,["paris","bangkok","colorado","whittleton_creek","isle_of_sgail","haven_island"], ["itemsanity"], ["Level - Paris", "Level - Bangkok", "Level - Colorado", "Level - Whittleton Creek", "Level - Isle of Sgail", "Level - Haven Island"]),
"Itempickup - Remote Explosive":(15,["paris","sapienza","marrakesh","santa_fortuna","whittleton_creek","haven_island","chongqing"], ["itemsanity"], ["Level - Paris", "Level - Sapienza", "Level - Marrakesh", "Level - Santa Fortuna", "Level - Whittleton Creek", "Level - Haven Island", "Level - Chongqing"]),
"Itempickup - Fire Extinguisher":(16,["paris","sapienza","marrakesh","bangkok","colorado","hokkaido","miami","santa_fortuna","mumbai","whittleton_creek","ambrose_island","isle_of_sgail","new_york","haven_island","dubai","berlin","chongqing","mendoza","carpathian_mountains"], ["itemsanity"], ["Level - Paris", "Level - Sapienza", "Level - Marrakesh", "Level - Bangkok", "Level - Colorado", "Level - Hokkaido", "Level - Miami", "Level - Santa Fortuna", "Level - Mumbai", "Level - Whittleton Creek", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - New York", "Level - Haven Island", "Level - Dubai", "Level - Berlin", "Level - Chongqing", "Level - Mendoza", "Level - Carpathian Mountains"]),
"Itempickup - Bartoli 75R":(17,["paris","sapienza","marrakesh","bangkok","colorado","miami","whittleton_creek","new_york","dubai","berlin","chongqing"], ["itemsanity"], ["Level - Paris", "Level - Sapienza", "Level - Marrakesh", "Level - Bangkok", "Level - Colorado", "Level - Miami", "Level - Whittleton Creek", "Level - New York", "Level - Dubai", "Level - Berlin", "Level - Chongqing"]),
"Itempickup - Tactical Bartoli 12G":(18,["paris","sapienza","marrakesh","bangkok","colorado","hokkaido","hawkes_bay","miami","isle_of_sgail","new_york","haven_island","berlin","chongqing"], ["itemsanity"], ["Level - Paris", "Level - Sapienza", "Level - Marrakesh", "Level - Bangkok", "Level - Colorado", "Level - Hokkaido", "Level - Hawkes Bay", "Level - Miami", "Level - Isle of Sgail", "Level - New York", "Level - Haven Island", "Level - Berlin", "Level - Chongqing"]),
"Itempickup - Kitchen Knife":(19,["paris","sapienza","marrakesh","bangkok","colorado","hokkaido","hawkes_bay","miami","santa_fortuna","mumbai","whittleton_creek","ambrose_island","isle_of_sgail","new_york","haven_island","dubai","dartmoor","berlin","chongqing","mendoza"], ["itemsanity"], ["Level - Paris", "Level - Sapienza", "Level - Marrakesh", "Level - Bangkok", "Level - Colorado", "Level - Hokkaido", "Level - Hawkes Bay", "Level - Miami", "Level - Santa Fortuna", "Level - Mumbai", "Level - Whittleton Creek", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - New York", "Level - Haven Island", "Level - Dubai", "Level - Dartmoor", "Level - Berlin", "Level - Chongqing", "Level - Mendoza"]),
"Itempickup - Propane Flask":(20,["paris","sapienza","marrakesh","bangkok","colorado","hokkaido","hawkes_bay","miami","santa_fortuna","mumbai","whittleton_creek","ambrose_island","isle_of_sgail","new_york","haven_island","dubai","dartmoor","berlin","chongqing","mendoza"], ["itemsanity"], ["Level - Paris", "Level - Sapienza", "Level - Marrakesh", "Level - Bangkok", "Level - Colorado", "Level - Hokkaido", "Level - Hawkes Bay", "Level - Miami", "Level - Santa Fortuna", "Level - Mumbai", "Level - Whittleton Creek", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - New York", "Level - Haven Island", "Level - Dubai", "Level - Dartmoor", "Level - Berlin", "Level - Chongqing", "Level - Mendoza"]),
"Itempickup - Cleaver":(21,["paris","sapienza","marrakesh","bangkok","colorado","hokkaido","hawkes_bay","miami","santa_fortuna","mumbai","ambrose_island","isle_of_sgail","haven_island","dubai","dartmoor","chongqing"], ["itemsanity"], ["Level - Paris", "Level - Sapienza", "Level - Marrakesh", "Level - Bangkok", "Level - Colorado", "Level - Hokkaido", "Level - Hawkes Bay", "Level - Miami", "Level - Santa Fortuna", "Level - Mumbai", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - Haven Island", "Level - Dubai", "Level - Dartmoor", "Level - Chongqing"]),
"Itempickup - Frying Pan":(22,["paris","hokkaido","miami","santa_fortuna","mumbai","ambrose_island","isle_of_sgail","haven_island","dubai","berlin","chongqing","mendoza"], ["itemsanity"], ["Level - Paris", "Level - Hokkaido", "Level - Miami", "Level - Santa Fortuna", "Level - Mumbai", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - Haven Island", "Level - Dubai", "Level - Berlin", "Level - Chongqing", "Level - Mendoza"]),
"Itempickup - Fire Poker":(23,["paris","sapienza","hokkaido","hawkes_bay","isle_of_sgail","dartmoor","mendoza"], ["itemsanity"], ["Level - Paris", "Level - Sapienza", "Level - Hokkaido", "Level - Hawkes Bay", "Level - Isle of Sgail", "Level - Dartmoor", "Level - Mendoza"]),
"Itempickup - Hatchet":(24,["paris","sapienza","bangkok","whittleton_creek","isle_of_sgail","haven_island","dartmoor","mendoza"], ["itemsanity"], ["Level - Paris", "Level - Sapienza", "Level - Bangkok", "Level - Whittleton Creek", "Level - Isle of Sgail", "Level - Haven Island", "Level - Dartmoor", "Level - Mendoza"]),
"Itempickup - Saber":(25,["paris","sapienza","marrakesh","mumbai","isle_of_sgail","dartmoor"], ["itemsanity"], ["Level - Paris", "Level - Sapienza", "Level - Marrakesh", "Level - Mumbai", "Level - Isle of Sgail", "Level - Dartmoor"]),
"Itempickup - Battle Axe":(26,["paris","sapienza","marrakesh","miami","whittleton_creek","isle_of_sgail","berlin"], ["itemsanity"], ["Level - Paris", "Level - Sapienza", "Level - Marrakesh", "Level - Miami", "Level - Whittleton Creek", "Level - Isle of Sgail", "Level - Berlin"]),
"Itempickup - Golf Club":(27,["paris","sapienza","bangkok","miami","whittleton_creek","new_york","haven_island","dubai","dartmoor"], ["itemsanity"], ["Level - Paris", "Level - Sapienza", "Level - Bangkok", "Level - Miami", "Level - Whittleton Creek", "Level - New York", "Level - Haven Island", "Level - Dubai", "Level - Dartmoor"]),
"Itempickup - Police Baton":(28,["paris","sapienza","bangkok","hokkaido","miami","new_york","haven_island","berlin"], ["itemsanity"], ["Level - Paris", "Level - Sapienza", "Level - Bangkok", "Level - Hokkaido", "Level - Miami", "Level - New York", "Level - Haven Island", "Level - Berlin"]),
"Itempickup - Shovel":(29,["sapienza","bangkok","colorado","hokkaido","hawkes_bay","miami","santa_fortuna","mumbai","whittleton_creek","ambrose_island","isle_of_sgail","haven_island","dubai","dartmoor","berlin","mendoza"], ["itemsanity"], ["Level - Sapienza", "Level - Bangkok", "Level - Colorado", "Level - Hokkaido", "Level - Hawkes Bay", "Level - Miami", "Level - Santa Fortuna", "Level - Mumbai", "Level - Whittleton Creek", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - Haven Island", "Level - Dubai", "Level - Dartmoor", "Level - Berlin", "Level - Mendoza"]),
"Itempickup - Circumcision Knife":(30,["sapienza","isle_of_sgail"], ["itemsanity"], ["Level - Sapienza", "Level - Isle of Sgail"]),
"Itempickup - Amputation Knife":(31,["sapienza","miami","mumbai"], ["itemsanity"], ["Level - Sapienza", "Level - Miami", "Level - Mumbai"]),
"Itempickup - Toy Tank":(32,["sapienza","marrakesh","new_york","berlin","chongqing"], ["itemsanity"], ["Level - Sapienza", "Level - Marrakesh", "Level - New York", "Level - Berlin", "Level - Chongqing"]),
"Itempickup - Expired Can of Spaghetti Sauce":(33,["sapienza","hawkes_bay","santa_fortuna","mumbai","whittleton_creek","isle_of_sgail"], ["itemsanity"], ["Level - Sapienza", "Level - Hawkes Bay", "Level - Santa Fortuna", "Level - Mumbai", "Level - Whittleton Creek", "Level - Isle of Sgail"]),
"Itempickup - Soda Can":(34,["sapienza","marrakesh","bangkok","colorado","hokkaido","hawkes_bay","miami","santa_fortuna","mumbai","whittleton_creek","ambrose_island","isle_of_sgail","new_york","haven_island","dubai","dartmoor","berlin","chongqing","mendoza","carpathian_mountains"], ["itemsanity"], ["Level - Sapienza", "Level - Marrakesh", "Level - Bangkok", "Level - Colorado", "Level - Hokkaido", "Level - Hawkes Bay", "Level - Miami", "Level - Santa Fortuna", "Level - Mumbai", "Level - Whittleton Creek", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - New York", "Level - Haven Island", "Level - Dubai", "Level - Dartmoor", "Level - Berlin", "Level - Chongqing", "Level - Mendoza", "Level - Carpathian Mountains"]),
"Itempickup - Bartoli 75S":(35,["sapienza","hawkes_bay","santa_fortuna","mumbai","isle_of_sgail","haven_island","mendoza"], ["itemsanity"], ["Level - Sapienza", "Level - Hawkes Bay", "Level - Santa Fortuna", "Level - Mumbai", "Level - Isle of Sgail", "Level - Haven Island", "Level - Mendoza"]),
"Itempickup - Virus Prototype":(36,["sapienza"], ["itemsanity"], ["Level - Sapienza"]),
"Itempickup - Combat Knife":(37,["sapienza","berlin","mendoza"], ["itemsanity"], ["Level - Sapienza", "Level - Berlin", "Level - Mendoza"]),
"Itempickup - Baseball Bat":(38,["sapienza","bangkok","colorado","hokkaido","miami","santa_fortuna","mumbai","whittleton_creek","isle_of_sgail","haven_island","berlin"], ["itemsanity"], ["Level - Sapienza", "Level - Bangkok", "Level - Colorado", "Level - Hokkaido", "Level - Miami", "Level - Santa Fortuna", "Level - Mumbai", "Level - Whittleton Creek", "Level - Isle of Sgail", "Level - Haven Island", "Level - Berlin"]),
"Itempickup - Explosive Golf Ball":(39,["sapienza","dubai"], ["itemsanity"], ["Level - Sapienza", "Level - Dubai"]),
"Itempickup - Folding Knife":(40,["sapienza","hawkes_bay","santa_fortuna","mumbai","ambrose_island","new_york","haven_island","dubai","dartmoor"], ["itemsanity"], ["Level - Sapienza", "Level - Hawkes Bay", "Level - Santa Fortuna", "Level - Mumbai", "Level - Ambrose Island", "Level - New York", "Level - Haven Island", "Level - Dubai", "Level - Dartmoor"]),
"Itempickup - Old Axe":(41,["sapienza","colorado","miami","mumbai","ambrose_island","isle_of_sgail","berlin","mendoza"], ["itemsanity"], ["Level - Sapienza", "Level - Colorado", "Level - Miami", "Level - Mumbai", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - Berlin", "Level - Mendoza"]),
"Itempickup - Radio":(42,["sapienza"], ["itemsanity"], ["Level - Sapienza"]),
"Itempickup - Bag of Gunpowder":(43,["sapienza","santa_fortuna","isle_of_sgail","mendoza"], ["itemsanity"], ["Level - Sapienza", "Level - Santa Fortuna", "Level - Isle of Sgail", "Level - Mendoza"]),
"Itempickup - Cannonball":(44,["sapienza","ambrose_island","isle_of_sgail","mendoza"], ["itemsanity"], ["Level - Sapienza", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - Mendoza"]),
"Itempickup - Bartoli 12G":(45,["sapienza","colorado","santa_fortuna","mumbai"], ["itemsanity"], ["Level - Sapienza", "Level - Colorado", "Level - Santa Fortuna", "Level - Mumbai"]),
"Itempickup - Katana":(46,["sapienza","bangkok","hokkaido","hawkes_bay","isle_of_sgail"], ["itemsanity"], ["Level - Sapienza", "Level - Bangkok", "Level - Hokkaido", "Level - Hawkes Bay", "Level - Isle of Sgail"]),
"Itempickup - Shashka A33":(47,["marrakesh","santa_fortuna","mumbai","ambrose_island"], ["itemsanity"], ["Level - Marrakesh", "Level - Santa Fortuna", "Level - Mumbai", "Level - Ambrose Island"]),
"Itempickup - Fusil G1-4":(48,["marrakesh","dubai"], ["itemsanity"], ["Level - Marrakesh", "Level - Dubai"]),
"Itempickup - Lethal Poison Pill Jar":(49,["marrakesh","bangkok","colorado","hawkes_bay","miami","santa_fortuna","mumbai","new_york","haven_island","dubai","dartmoor","chongqing","mendoza"], ["itemsanity"], ["Level - Marrakesh", "Level - Bangkok", "Level - Colorado", "Level - Hawkes Bay", "Level - Miami", "Level - Santa Fortuna", "Level - Mumbai", "Level - New York", "Level - Haven Island", "Level - Dubai", "Level - Dartmoor", "Level - Chongqing", "Level - Mendoza"]),
"Itempickup - Insecticide":(50,["bangkok","whittleton_creek","berlin"], ["itemsanity"], ["Level - Bangkok", "Level - Whittleton Creek", "Level - Berlin"]),
"Itempickup - Coconut":(51,["bangkok","miami","santa_fortuna","ambrose_island","isle_of_sgail","haven_island","dubai","berlin"], ["itemsanity"], ["Level - Bangkok", "Level - Miami", "Level - Santa Fortuna", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - Haven Island", "Level - Dubai", "Level - Berlin"]),
"Itempickup - Sapper's Axe":(52,["bangkok","isle_of_sgail","mendoza"], ["itemsanity"], ["Level - Bangkok", "Level - Isle of Sgail", "Level - Mendoza"]),
"Itempickup - Apricot":(53,["colorado","miami","santa_fortuna","ambrose_island","isle_of_sgail","new_york","dartmoor","chongqing"], ["itemsanity"], ["Level - Colorado", "Level - Miami", "Level - Santa Fortuna", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - New York", "Level - Dartmoor", "Level - Chongqing"]),
"Itempickup - Baseball":(54,["colorado","miami","santa_fortuna","whittleton_creek","haven_island","dartmoor","berlin"], ["itemsanity"], ["Level - Colorado", "Level - Miami", "Level - Santa Fortuna", "Level - Whittleton Creek", "Level - Haven Island", "Level - Dartmoor", "Level - Berlin"]),
"Itempickup - Cowboy Bust":(55,["colorado","hokkaido","santa_fortuna","isle_of_sgail","chongqing"], ["itemsanity"], ["Level - Colorado", "Level - Hokkaido", "Level - Santa Fortuna", "Level - Isle of Sgail", "Level - Chongqing"]),
"Itempickup - Explosive Watch Battery":(56,["colorado"], ["itemsanity"], ["Level - Colorado"]),
"Itempickup - Nitroglycerin":(57,["colorado","ambrose_island","isle_of_sgail"], ["itemsanity"], ["Level - Colorado", "Level - Ambrose Island", "Level - Isle of Sgail"]),
"Itempickup - Modern Lethal Syringe":(58,["colorado","miami","berlin"], ["itemsanity"], ["Level - Colorado", "Level - Miami", "Level - Berlin"]),
"Itempickup - HX-10":(59,["colorado","isle_of_sgail","haven_island","dubai"], ["itemsanity"], ["Level - Colorado", "Level - Isle of Sgail", "Level - Haven Island", "Level - Dubai"]),
"Itempickup - Branding Iron":(60,["colorado","isle_of_sgail"], ["itemsanity"], ["Level - Colorado", "Level - Isle of Sgail"]),
"Itempickup - Mannequin Arm":(61,["colorado","chongqing"], ["itemsanity"], ["Level - Colorado", "Level - Chongqing"]),
"Itempickup - HX-7":(62,["colorado","hokkaido","hawkes_bay"], ["itemsanity"], ["Level - Colorado", "Level - Hokkaido", "Level - Hawkes Bay"]),
"Itempickup - Scalpel":(63,["hokkaido","isle_of_sgail","haven_island"], ["itemsanity"], ["Level - Hokkaido", "Level - Isle of Sgail", "Level - Haven Island"]),
"Itempickup - Botulinum Toxin":(64,["hokkaido","isle_of_sgail"], ["itemsanity"], ["Level - Hokkaido", "Level - Isle of Sgail"]),
"Itempickup - Hackl 9S Covert":(65,["hawkes_bay","santa_fortuna","whittleton_creek","isle_of_sgail","haven_island","dubai","dartmoor","chongqing","mendoza"], ["itemsanity"], ["Level - Hawkes Bay", "Level - Santa Fortuna", "Level - Whittleton Creek", "Level - Isle of Sgail", "Level - Haven Island", "Level - Dubai", "Level - Dartmoor", "Level - Chongqing", "Level - Mendoza"]),
"Itempickup - Kalmer 1 - Tranquilizer":(66,["hawkes_bay","new_york"], ["itemsanity"], ["Level - Hawkes Bay", "Level - New York"]),
"Itempickup - Chloroform Flask":(67,["hawkes_bay","isle_of_sgail","new_york","chongqing"], ["itemsanity"], ["Level - Hawkes Bay", "Level - Isle of Sgail", "Level - New York", "Level - Chongqing"]),
"Itempickup - Squeaky Toy":(68,["hawkes_bay"], ["itemsanity"], ["Level - Hawkes Bay"]),
"Itempickup - Shuriken":(69,["hawkes_bay"], ["itemsanity"], ["Level - Hawkes Bay"]),
"Itempickup - Maori Paddle":(70,["hawkes_bay","haven_island","dartmoor"], ["itemsanity"], ["Level - Hawkes Bay", "Level - Haven Island", "Level - Dartmoor"]),
"Itempickup - Wristwatch Alarm":(71,["hawkes_bay","new_york"], ["itemsanity"], ["Level - Hawkes Bay", "Level - New York"]),
"Itempickup - Driftwood Log":(72,["hawkes_bay","santa_fortuna","ambrose_island","isle_of_sgail","haven_island","dartmoor","chongqing"], ["itemsanity"], ["Level - Hawkes Bay", "Level - Santa Fortuna", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - Haven Island", "Level - Dartmoor", "Level - Chongqing"]),
"Itempickup - Car Battery":(73,["hawkes_bay","santa_fortuna","mumbai","whittleton_creek","ambrose_island","isle_of_sgail","new_york","dubai","dartmoor","berlin","chongqing","mendoza"], ["itemsanity"], ["Level - Hawkes Bay", "Level - Santa Fortuna", "Level - Mumbai", "Level - Whittleton Creek", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - New York", "Level - Dubai", "Level - Dartmoor", "Level - Berlin", "Level - Chongqing", "Level - Mendoza"]),
"Itempickup - Apple":(74,["hawkes_bay","whittleton_creek","ambrose_island","isle_of_sgail","new_york","haven_island","dubai","dartmoor","chongqing","mendoza"], ["itemsanity"], ["Level - Hawkes Bay", "Level - Whittleton Creek", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - New York", "Level - Haven Island", "Level - Dubai", "Level - Dartmoor", "Level - Chongqing", "Level - Mendoza"]),
"Itempickup - Fragmentation Grenade":(75,["hawkes_bay","carpathian_mountains"], ["itemsanity"], ["Level - Hawkes Bay", "Level - Carpathian Mountains"]),
"Itempickup - Kronstadt Octane Booster":(76,["miami"], ["itemsanity"], ["Level - Miami"]),
"Itempickup - Didgeridoo":(77,["miami"], ["itemsanity"], ["Level - Miami"]),
"Itempickup - Android Arm":(78,["miami"], ["itemsanity"], ["Level - Miami"]),
"Itempickup - Bag of Sugar":(79,["miami","ambrose_island","dartmoor","berlin"], ["itemsanity"], ["Level - Miami", "Level - Ambrose Island", "Level - Dartmoor", "Level - Berlin"]),
"Itempickup - Fish":(80,["miami","mumbai","ambrose_island","isle_of_sgail","haven_island","dartmoor","mendoza"], ["itemsanity"], ["Level - Miami", "Level - Mumbai", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - Haven Island", "Level - Dartmoor", "Level - Mendoza"]),
"Itempickup - Pneumatic Wrench":(81,["miami"], ["itemsanity"], ["Level - Miami"]),
"Itempickup - Car Bomb":(82,["miami","whittleton_creek"], ["itemsanity"], ["Level - Miami", "Level - Whittleton Creek"]),
"Itempickup - Cocaine Brick":(83,["miami","santa_fortuna","isle_of_sgail","berlin","mendoza"], ["itemsanity"], ["Level - Miami", "Level - Santa Fortuna", "Level - Isle of Sgail", "Level - Berlin", "Level - Mendoza"]),
"Itempickup - Starfish":(84,["miami","ambrose_island","isle_of_sgail","haven_island"], ["itemsanity"], ["Level - Miami", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - Haven Island"]),
"Itempickup - Cannabis Joint":(85,["miami","whittleton_creek"], ["itemsanity"], ["Level - Miami", "Level - Whittleton Creek"]),
"Itempickup - The Big One":(86,["miami"], ["itemsanity"], ["Level - Miami"]),
"Itempickup - Meaty Bone":(87,["santa_fortuna","whittleton_creek","ambrose_island","isle_of_sgail","haven_island","dubai","chongqing","mendoza"], ["itemsanity"], ["Level - Santa Fortuna", "Level - Whittleton Creek", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - Haven Island", "Level - Dubai", "Level - Chongqing", "Level - Mendoza"]),
"Itempickup - DAK X2":(88,["santa_fortuna","mumbai","whittleton_creek","new_york"], ["itemsanity"], ["Level - Santa Fortuna", "Level - Mumbai", "Level - Whittleton Creek", "Level - New York"]),
"Itempickup - Poisonous Flower (Emetic)":(89,["santa_fortuna","ambrose_island","haven_island","dartmoor","mendoza"], ["itemsanity"], ["Level - Santa Fortuna", "Level - Ambrose Island", "Level - Haven Island", "Level - Dartmoor", "Level - Mendoza"]),
"Itempickup - Poisonous Flower (Lethal)":(90,["santa_fortuna"], ["itemsanity"], ["Level - Santa Fortuna"]),
"Itempickup - Lethal Poisonous Frog":(91,["santa_fortuna","whittleton_creek","ambrose_island","haven_island"], ["itemsanity"], ["Level - Santa Fortuna", "Level - Whittleton Creek", "Level - Ambrose Island", "Level - Haven Island"]),
"Itempickup - Letterbomb Parcel":(92,["santa_fortuna","new_york"], ["itemsanity"], ["Level - Santa Fortuna", "Level - New York"]),
"Itempickup - Collectors Baseball Bat":(93,["santa_fortuna"], ["itemsanity"], ["Level - Santa Fortuna"]),
"Itempickup - Machete":(94,["santa_fortuna","haven_island","mendoza"], ["itemsanity"], ["Level - Santa Fortuna", "Level - Haven Island", "Level - Mendoza"]),
"Itempickup - Claw Hammer":(95,["santa_fortuna","new_york","mendoza","carpathian_mountains"], ["itemsanity"], ["Level - Santa Fortuna", "Level - New York", "Level - Mendoza", "Level - Carpathian Mountains"]),
"Itempickup - Shashka A33 Gold":(96,["santa_fortuna","ambrose_island"], ["itemsanity"], ["Level - Santa Fortuna", "Level - Ambrose Island"]),
"Itempickup - Gold Idol":(97,["santa_fortuna","ambrose_island","isle_of_sgail","new_york","haven_island","dubai","berlin"], ["itemsanity"], ["Level - Santa Fortuna", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - New York", "Level - Haven Island", "Level - Dubai", "Level - Berlin"]),
"Itempickup - Sacrificial Knife":(98,["santa_fortuna","isle_of_sgail"], ["itemsanity"], ["Level - Santa Fortuna", "Level - Isle of Sgail"]),
"Itempickup - Barber Razor":(99,["santa_fortuna","mumbai","ambrose_island","haven_island","dartmoor","carpathian_mountains"], ["itemsanity"], ["Level - Santa Fortuna", "Level - Mumbai", "Level - Ambrose Island", "Level - Haven Island", "Level - Dartmoor", "Level - Carpathian Mountains"]),
"Itempickup - \"El Matador\"":(100,["santa_fortuna"], ["itemsanity"], ["Level - Santa Fortuna"]),
"Itempickup - Cocaine Souvenir":(101,["santa_fortuna"], ["itemsanity"], ["Level - Santa Fortuna"]),
"Itempickup - Beak Staff":(102,["mumbai","whittleton_creek"], ["itemsanity"], ["Level - Mumbai", "Level - Whittleton Creek"]),
"Itempickup - Iron":(103,["mumbai","ambrose_island","isle_of_sgail","new_york","haven_island","dubai","dartmoor","berlin","chongqing"], ["itemsanity"], ["Level - Mumbai", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - New York", "Level - Haven Island", "Level - Dubai", "Level - Dartmoor", "Level - Berlin", "Level - Chongqing"]),
"Itempickup - Chennai Cricket Ball":(104,["mumbai"], ["itemsanity"], ["Level - Mumbai"]),
"Itempickup - Lever":(105,["mumbai"], ["itemsanity"], ["Level - Mumbai"]),
"Itempickup - Colored Smoke":(106,["mumbai"], ["itemsanity"], ["Level - Mumbai"]),
"Itempickup - Khatvanga":(107,["mumbai","ambrose_island","isle_of_sgail"], ["itemsanity"], ["Level - Mumbai", "Level - Ambrose Island", "Level - Isle of Sgail"]),
"Itempickup - Measuring Tape":(108,["mumbai"], ["itemsanity"], ["Level - Mumbai"]),
"Itempickup - Druzhina 34":(109,["mumbai"], ["itemsanity"], ["Level - Mumbai"]),
"Itempickup - Rake":(110,["mumbai","whittleton_creek","dartmoor","mendoza"], ["itemsanity"], ["Level - Mumbai", "Level - Whittleton Creek", "Level - Dartmoor", "Level - Mendoza"]),
"Itempickup - DAK X2 Covert Special":(111,["whittleton_creek"], ["itemsanity"], ["Level - Whittleton Creek"]),
"Itempickup - Flash Grenade":(112,["whittleton_creek","isle_of_sgail","new_york","carpathian_mountains"], ["itemsanity"], ["Level - Whittleton Creek", "Level - Isle of Sgail", "Level - New York", "Level - Carpathian Mountains"]),
"Itempickup - Blueberry Muffin":(113,["whittleton_creek","isle_of_sgail","new_york","haven_island","dubai","berlin","chongqing","carpathian_mountains"], ["itemsanity"], ["Level - Whittleton Creek", "Level - Isle of Sgail", "Level - New York", "Level - Haven Island", "Level - Dubai", "Level - Berlin", "Level - Chongqing", "Level - Carpathian Mountains"]),
"Itempickup - Newspaper":(114,["whittleton_creek","ambrose_island","isle_of_sgail","new_york","haven_island","dartmoor","chongqing"], ["itemsanity"], ["Level - Whittleton Creek", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - New York", "Level - Haven Island", "Level - Dartmoor", "Level - Chongqing"]),
"Itempickup - Lethal Pills":(115,["whittleton_creek","berlin"], ["itemsanity"], ["Level - Whittleton Creek", "Level - Berlin"]),
"Itempickup - Emetic Pills":(116,["whittleton_creek","dubai"], ["itemsanity"], ["Level - Whittleton Creek", "Level - Dubai"]),
"Itempickup - \"Rude Ruby\"":(117,["whittleton_creek"], ["itemsanity"], ["Level - Whittleton Creek"]),
"Itempickup - Remote CX Demo Block":(118,["whittleton_creek"], ["itemsanity"], ["Level - Whittleton Creek"]),
"Itempickup - RS-15":(119,["whittleton_creek"], ["itemsanity"], ["Level - Whittleton Creek"]),
"Itempickup - TAC-4 AR Auto":(120,["whittleton_creek"], ["itemsanity"], ["Level - Whittleton Creek"]),
"Itempickup - Fusil G1-4/C":(121,["whittleton_creek"], ["itemsanity"], ["Level - Whittleton Creek"]),
"Itempickup - Paddle":(122,["whittleton_creek","ambrose_island","isle_of_sgail","haven_island"], ["itemsanity"], ["Level - Whittleton Creek", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - Haven Island"]),
"Itempickup - Package":(123,["whittleton_creek","new_york","chongqing"], ["itemsanity"], ["Level - Whittleton Creek", "Level - New York", "Level - Chongqing"]),
"Itempickup - Cigar Box":(124,["whittleton_creek","ambrose_island","isle_of_sgail","dartmoor","chongqing"], ["itemsanity"], ["Level - Whittleton Creek", "Level - Ambrose Island", "Level - Isle of Sgail", "Level - Dartmoor", "Level - Chongqing"]),
"Itempickup - Fishing Line":(125,["ambrose_island","mendoza"], ["itemsanity"], ["Level - Ambrose Island", "Level - Mendoza"]),
"Itempickup - Wooden Torch":(126,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Garden Fork":(127,["ambrose_island","dartmoor","berlin","chongqing","mendoza"], ["itemsanity"], ["Level - Ambrose Island", "Level - Dartmoor", "Level - Berlin", "Level - Chongqing", "Level - Mendoza"]),
"Itempickup - Whiskey Bottle":(128,["ambrose_island","dubai","chongqing"], ["itemsanity"], ["Level - Ambrose Island", "Level - Dubai", "Level - Chongqing"]),
"Itempickup - Spray Can":(129,["ambrose_island","berlin"], ["itemsanity"], ["Level - Ambrose Island", "Level - Berlin"]),
"Itempickup - Vodka Bottle":(130,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Soap":(131,["ambrose_island","dubai","dartmoor","chongqing","carpathian_mountains"], ["itemsanity"], ["Level - Ambrose Island", "Level - Dubai", "Level - Dartmoor", "Level - Chongqing", "Level - Carpathian Mountains"]),
"Itempickup - Banana":(132,["ambrose_island","haven_island","dubai","dartmoor","berlin","chongqing","mendoza"], ["itemsanity"], ["Level - Ambrose Island", "Level - Haven Island", "Level - Dubai", "Level - Dartmoor", "Level - Berlin", "Level - Chongqing", "Level - Mendoza"]),
"Itempickup - Durian":(133,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Meat Fork":(134,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Kukri Machete":(135,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Seashell":(136,["ambrose_island","haven_island"], ["itemsanity"], ["Level - Ambrose Island", "Level - Haven Island"]),
"Itempickup - Lethal Poison Vial":(137,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Emetic Gas Grenade":(138,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Sawed-Off Bartoli 12G":(139,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Hook":(140,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Brine-Damaged SMG":(141,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Molotov Cocktail":(142,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Makeshift Explosive":(143,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Remote CX Demo Block MK II":(144,["ambrose_island","mendoza"], ["itemsanity"], ["Level - Ambrose Island", "Level - Mendoza"]),
"Itempickup - Scrap Sword":(145,["ambrose_island","berlin","chongqing"], ["itemsanity"], ["Level - Ambrose Island", "Level - Berlin", "Level - Chongqing"]),
"Itempickup - Umbrella":(146,["ambrose_island","chongqing","mendoza"], ["itemsanity"], ["Level - Ambrose Island", "Level - Chongqing", "Level - Mendoza"]),
"Itempickup - Shears":(147,["ambrose_island","dartmoor","mendoza"], ["itemsanity"], ["Level - Ambrose Island", "Level - Dartmoor", "Level - Mendoza"]),
"Itempickup - Hobby Knife":(148,["ambrose_island","new_york","berlin","chongqing","mendoza"], ["itemsanity"], ["Level - Ambrose Island", "Level - New York", "Level - Berlin", "Level - Chongqing", "Level - Mendoza"]),
"Itempickup - Militia-Issued HX-10 SMG":(149,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Remote Breaching Charge":(150,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Doubloon":(151,["ambrose_island","haven_island"], ["itemsanity"], ["Level - Ambrose Island", "Level - Haven Island"]),
"Itempickup - Jarl's Pirate Saber":(152,["ambrose_island","haven_island","mendoza"], ["itemsanity"], ["Level - Ambrose Island", "Level - Haven Island", "Level - Mendoza"]),
"Itempickup - Mace":(153,["isle_of_sgail"], ["itemsanity"], ["Level - Isle of Sgail"]),
"Itempickup - Broadsword":(154,["isle_of_sgail","mendoza"], ["itemsanity"], ["Level - Isle of Sgail", "Level - Mendoza"]),
"Itempickup - Viking Axe":(155,["isle_of_sgail"], ["itemsanity"], ["Level - Isle of Sgail"]),
"Itempickup - HX-7 Covert":(156,["isle_of_sgail"], ["itemsanity"], ["Level - Isle of Sgail"]),
"Itempickup - Aztec Necklace":(157,["isle_of_sgail"], ["itemsanity"], ["Level - Isle of Sgail"]),
"Itempickup - Imperial Filigree Egg":(158,["isle_of_sgail","new_york","haven_island","dubai","dartmoor","mendoza","carpathian_mountains"], ["itemsanity"], ["Level - Isle of Sgail", "Level - New York", "Level - Haven Island", "Level - Dubai", "Level - Dartmoor", "Level - Mendoza", "Level - Carpathian Mountains"]),
"Itempickup - Torch":(159,["isle_of_sgail","mendoza"], ["itemsanity"], ["Level - Isle of Sgail", "Level - Mendoza"]),
"Itempickup - Hackl 9S":(160,["isle_of_sgail"], ["itemsanity"], ["Level - Isle of Sgail"]),
"Itempickup - Commemorative Token":(161,["isle_of_sgail","new_york"], ["itemsanity"], ["Level - Isle of Sgail", "Level - New York"]),
"Itempickup - Cheeseburger":(162,["isle_of_sgail","new_york","haven_island"], ["itemsanity"], ["Level - Isle of Sgail", "Level - New York", "Level - Haven Island"]),
"Itempickup - Small Goldbar":(163,["new_york"], ["itemsanity"], ["Level - New York"]),
"Itempickup - Violin":(164,["new_york","mendoza"], ["itemsanity"], ["Level - New York", "Level - Mendoza"]),
"Itempickup - Earphones":(165,["new_york","haven_island"], ["itemsanity"], ["Level - New York", "Level - Haven Island"]),
"Itempickup - Tanto":(166,["new_york","chongqing"], ["itemsanity"], ["Level - New York", "Level - Chongqing"]),
"Itempickup - Burial Dagger":(167,["new_york"], ["itemsanity"], ["Level - New York"]),
"Itempickup - Golden Sawed Off Bartoli 12G":(168,["new_york"], ["itemsanity"], ["Level - New York"]),
"Itempickup - Concussion Grenade":(169,["new_york"], ["itemsanity"], ["Level - New York"]),
"Itempickup - Wet Floor Sign":(170,["new_york","haven_island","dubai","mendoza"], ["itemsanity"], ["Level - New York", "Level - Haven Island", "Level - Dubai", "Level - Mendoza"]),
"Itempickup - Antique Carved Knife":(171,["new_york"], ["itemsanity"], ["Level - New York"]),
"Itempickup - Goldbar":(172,["new_york","dubai"], ["itemsanity"], ["Level - New York", "Level - Dubai"]),
"Itempickup - Feather Duster":(173,["new_york","haven_island","dartmoor"], ["itemsanity"], ["Level - New York", "Level - Haven Island", "Level - Dartmoor"]),
"Itempickup - Stethoscope":(174,["haven_island","chongqing"], ["itemsanity"], ["Level - Haven Island", "Level - Chongqing"]),
"Itempickup - Modern Emetic Syringe":(175,["haven_island"], ["itemsanity"], ["Level - Haven Island"]),
"Itempickup - Kettlebell":(176,["haven_island"], ["itemsanity"], ["Level - Haven Island"]),
"Itempickup - Pearl":(177,["haven_island"], ["itemsanity"], ["Level - Haven Island"]),
"Itempickup - Ornate Scimitar":(178,["dubai"], ["itemsanity"], ["Level - Dubai"]),
"Itempickup - Model of the Sceptre":(179,["dubai"], ["itemsanity"], ["Level - Dubai"]),
"Itempickup - Classic Coin":(180,["dartmoor"], ["itemsanity"], ["Level - Dartmoor"]),
"Itempickup - Walking Cane":(181,["dartmoor"], ["itemsanity"], ["Level - Dartmoor"]),
"Itempickup - Unicorn Horn":(182,["dartmoor"], ["itemsanity"], ["Level - Dartmoor"]),
"Itempickup - Bartoli Hunting Shotgun":(183,["dartmoor","berlin","mendoza"], ["itemsanity"], ["Level - Dartmoor", "Level - Berlin", "Level - Mendoza"]),
"Itempickup - Modern Sedative Syringe":(184,["berlin"], ["itemsanity"], ["Level - Berlin"]),
"Itempickup - Bartoli Woodsman Hunting Rifle":(185,["berlin","mendoza"], ["itemsanity"], ["Level - Berlin", "Level - Mendoza"]),
"Itempickup - Bird's Egg":(186,["berlin"], ["itemsanity"], ["Level - Berlin"]),
"Itempickup - Poisonous (Emetic) Mushroom":(187,["berlin"], ["itemsanity"], ["Level - Berlin"]),
"Itempickup - Concealable Knife":(188,["berlin"], ["itemsanity"], ["Level - Berlin"]),
"Itempickup - ICA Remote Audio Distraction Mk III":(189,["berlin"], ["itemsanity"], ["Level - Berlin"]),
"Itempickup - Hackl Leviathan Sniper Rifle Covert":(190,["chongqing"], ["itemsanity"], ["Level - Chongqing"]),
"Itempickup - ICA SMG Raptor Covert":(191,["chongqing"], ["itemsanity"], ["Level - Chongqing"]),
"Itempickup - Fusil X2000 Stealth":(192,["chongqing"], ["itemsanity"], ["Level - Chongqing"]),
"Itempickup - Cabernet Sauvignon":(193,["mendoza"], ["itemsanity"], ["Level - Mendoza"]),
"Itempickup - Grape Knife":(194,["mendoza"], ["itemsanity"], ["Level - Mendoza"]),
"Itempickup - Grapevine":(195,["mendoza"], ["itemsanity"], ["Level - Mendoza"]),
"Itempickup - Pinot Noir":(196,["mendoza"], ["itemsanity"], ["Level - Mendoza"]),
"Itempickup - Malbec":(197,["mendoza"], ["itemsanity"], ["Level - Mendoza"]),
"Itempickup - 1945 Grand Paladin":(198,["mendoza"], ["itemsanity"], ["Level - Mendoza"]),
"Itempickup - Sieger AR552 Tactical":(199,["mendoza"], ["itemsanity"], ["Level - Mendoza"]),
"Itempickup - Sieger 300 Tactical":(200,["mendoza"], ["itemsanity"], ["Level - Mendoza"]),
"Itempickup - Icicle":(201,["mendoza","carpathian_mountains"], ["itemsanity"], ["Level - Mendoza", "Level - Carpathian Mountains"]),
"Itempickup - Rusty Crowbar":(202,["carpathian_mountains"], ["itemsanity"], ["Level - Carpathian Mountains"]),
"Itempickup - ICA SMG White Raptor Covert":(203,["carpathian_mountains"], ["itemsanity"], ["Level - Carpathian Mountains"]),
"Itempickup - HWK21 Pale":(204,["carpathian_mountains"], ["itemsanity"], ["Level - Carpathian Mountains"]),
"Itempickup - Rusty Screwdriver":(205,["carpathian_mountains"], ["itemsanity"], ["Level - Carpathian Mountains"]),
"Itempickup - ICA Tactical Shotgun Covert":(206,["carpathian_mountains"], ["itemsanity"], ["Level - Carpathian Mountains"]),
"Itempickup - Flash Grenade Mk III":(207,["carpathian_mountains"], ["itemsanity"], ["Level - Carpathian Mountains"]),
"Itempickup - Fiber Wire":(208,["carpathian_mountains"], ["itemsanity"], ["Level - Carpathian Mountains"]),
"Itempickup - ICA19 Black Lily":(209,["carpathian_mountains"], ["itemsanity"], ["Level - Carpathian Mountains"]),

# ============ MAP COMPLETION LOCATIONS ==============
"ICA Facility Completed":(1000,["free","ica_facility"],["completed","ica_facility_completed"],["Level - ICA Facility"]),
"Paris Completed":(1001,["h1","paris"],["completed","paris_completed"],["Level - Paris"]),
"Sapienza Completed":(1002,["h1","sapienza"],["completed","sapienza_completed"],["Level - Sapienza"]),
"Marrakesh Completed":(1003,["h1","marrakesh"],["completed","marrakesh_completed"],["Level - Marrakesh"]),
"Bangkok Completed":(1004,["h1","bangkok"],["completed","bangkok_completed"],["Level - Bangkok"]),
"Colorado Completed":(1005,["h1","colorado"],["completed","colorado_completed"],["Level - Colorado"]),
"Hokkaido Completed":(1006,["h1","hokkaido"],["completed","hokkaido_completed"],["Level - Hokkaido"]),
"Hawkes Bay Completed":(1007,["h2","hawkes_bay"],["completed","hawkes_bay_completed"],["Level - Hawkes Bay"]),
"Miami Completed":(1008,["h2","miami"],["completed","miami_completed"],["Level - Miami"]),
"Santa Fortuna Completed":(1009,["h2","santa_fortuna"],["completed","santa_fortuna_completed"],["Level - Santa Fortuna"]),
"Mumbai Completed":(1010,["h2","mumbai"],["completed","mumbai_completed"],["Level - Mumbai"]),
"Whittleton Creek Completed":(1011,["h2","whittleton_creek"],["completed","whittleton_creek_completed"],["Level - Whittleton Creek"]),
"Isle of Sgail Completed":(1012,["h2","isle_of_sgail"],["completed","isle_of_sgail_completed"],["Level - Isle of Sgail"]),
"New York Completed":(1013,["h2_dlc","new_york"],["completed","new_york_completed"],["Level - New York"]),
"Haven Island Completed":(1014,["h2_dlc","haven_island"],["completed","haven_island_completed"],["Level - Haven Island"]),
"Dubai Completed":(1015,["h3","dubai"],["completed","dubai_completed"],["Level - Dubai"]),
"Dartmoor Completed":(1016,["h3","dartmoor"],["completed","dartmoor_completed"],["Level - Dartmoor"]),
"Berlin Completed":(1017,["h3","berlin"],["completed","berlin_completed"],["Level - Berlin"]),
"Chongqing Completed":(1018,["h3","chongqing"],["completed","chongqing_completed"],["Level - Chongqing"]),
"Mendoza Completed":(1019,["h3","mendoza"],["completed","mendoza_completed"],["Level - Mendoza"]),
"Carpathian Mountains Completed":(1020,["h3","carpathian_mountains"],["completed","carpathian_mountains_completed"],["Level - Carpathian Mountains"]),
"Ambrose Island Completed":(1021,["h3","ambrose_island"],["completed","ambrose_island_completed"],["Level - Ambrose Island"]),
"ICA Facility Completed - Silent Assassin":(1022,["free","ica_facility"],["sa","ica_facility_sa"],["Level - ICA Facility"]),
"Paris Completed - Silent Assassin":(1023,["h1","paris"],["sa","paris_sa"],["Level - Paris"]),
"Sapienza Completed - Silent Assassin":(1024,["h1","sapienza"],["sa","sapienza_sa"],["Level - Sapienza"]),
"Marrakesh Completed - Silent Assassin":(1025,["h1","marrakesh"],["sa","marrakesh_sa"],["Level - Marrakesh"]),
"Bangkok Completed - Silent Assassin":(1026,["h1","bangkok"],["sa","bangkok_sa"],["Level - Bangkok"]),
"Colorado Completed - Silent Assassin":(1027,["h1","colorado"],["sa","colorado_sa"],["Level - Colorado"]),
"Hokkaido Completed - Silent Assassin":(1028,["h1","hokkaido"],["sa","hokkaido_sa"],["Level - Hokkaido"]),
"Hawkes Bay Completed - Silent Assassin":(1029,["h2","hawkes_bay"],["sa","hawkes_bay_sa"],["Level - Hawkes Bay"]),
"Miami Completed - Silent Assassin":(1030,["h2","miami"],["sa","miami_sa"],["Level - Miami"]),
"Santa Fortuna Completed - Silent Assassin":(1031,["h2","santa_fortuna"],["sa","santa_fortuna_sa"],["Level - Santa Fortuna"]),
"Mumbai Completed - Silent Assassin":(1032,["h2","mumbai"],["sa","mumbai_sa"],["Level - Mumbai"]),
"Whittleton Creek Completed - Silent Assassin":(1033,["h2","whittleton_creek"],["sa","whittleton_creek_sa"],["Level - Whittleton Creek"]),
"Isle of Sgail Completed - Silent Assassin":(1034,["h2","isle_of_sgail"],["sa","isle_of_sgail_sa"],["Level - Isle of Sgail"]),
"New York Completed - Silent Assassin":(1035,["h2_dlc","new_york"],["sa","new_york_sa"],["Level - New York"]),
"Haven Island Completed - Silent Assassin":(1036,["h2_dlc","haven_island"],["sa","haven_island_sa"],["Level - Haven Island"]),
"Dubai Completed - Silent Assassin":(1037,["h3","dubai"],["sa","dubai_sa"],["Level - Dubai"]),
"Dartmoor Completed - Silent Assassin":(1038,["h3","dartmoor"],["sa","dartmoor_sa"],["Level - Dartmoor"]),
"Berlin Completed - Silent Assassin":(1039,["h3","berlin"],["sa","berlin_sa"],["Level - Berlin"]),
"Chongqing Completed - Silent Assassin":(1040,["h3","chongqing"],["sa","chongqing_sa"],["Level - Chongqing"]),
"Mendoza Completed - Silent Assassin":(1041,["h3","mendoza"],["sa","mendoza_sa"],["Level - Mendoza"]),
"Carpathian Mountains Completed - Silent Assassin":(1042,["h3","carpathian_mountains"],["sa","carpathian_mountains_sa"],["Level - Carpathian Mountains"]),
"Ambrose Island Completed - Silent Assassin":(1043,["h3","ambrose_island"],["sa","ambrose_island_sa"],["Level - Ambrose Island"]),
"ICA Facility Completed - Suit Only":(1044,["free","ica_facility"],["so","ica_facility_so"],["Level - ICA Facility"]),
"Paris Completed - Suit Only":(1045,["h1","paris"],["so","paris_so"],["Level - Paris"]),
"Sapienza Completed - Suit Only":(1046,["h1","sapienza"],["so","sapienza_so"],["Level - Sapienza"]),
"Marrakesh Completed - Suit Only":(1047,["h1","marrakesh"],["so","marrakesh_so"],["Level - Marrakesh"]),
"Bangkok Completed - Suit Only":(1048,["h1","bangkok"],["so","bangkok_so"],["Level - Bangkok"]),
"Colorado Completed - Suit Only":(1049,["h1","colorado"],["so","colorado_so"],["Level - Colorado"]),
"Hokkaido Completed - Suit Only":(1050,["h1","hokkaido"],["so","hokkaido_so"],["Level - Hokkaido"]),
"Hawkes Bay Completed - Suit Only":(1051,["h2","hawkes_bay"],["so","hawkes_bay_so"],["Level - Hawkes Bay"]),
"Miami Completed - Suit Only":(1052,["h2","miami"],["so","miami_so"],["Level - Miami"]),
"Santa Fortuna Completed - Suit Only":(1053,["h2","santa_fortuna"],["so","santa_fortuna_so"],["Level - Santa Fortuna"]),
"Mumbai Completed - Suit Only":(1054,["h2","mumbai"],["so","mumbai_so"],["Level - Mumbai"]),
"Whittleton Creek Completed - Suit Only":(1055,["h2","whittleton_creek"],["so","whittleton_creek_so"],["Level - Whittleton Creek"]),
"Isle of Sgail Completed - Suit Only":(1056,["h2","isle_of_sgail"],["so","isle_of_sgail_so"],["Level - Isle of Sgail"]),
"New York Completed - Suit Only":(1057,["h2_dlc","new_york"],["so","new_york_so"],["Level - New York"]),
"Haven Island Completed - Suit Only":(1058,["h2_dlc","haven_island"],["so","haven_island_so"],["Level - Haven Island"]),
"Dubai Completed - Suit Only":(1059,["h3","dubai"],["so","dubai_so"],["Level - Dubai"]),
"Dartmoor Completed - Suit Only":(1060,["h3","dartmoor"],["so","dartmoor_so"],["Level - Dartmoor"]),
"Berlin Completed - Suit Only":(1061,["h3","berlin"],["so","berlin_so"],["Level - Berlin"]),
"Chongqing Completed - Suit Only":(1062,["h3","chongqing"],["so","chongqing_so"],["Level - Chongqing"]),
"Mendoza Completed - Suit Only":(1063,["h3","mendoza"],["so","mendoza_so"],["Level - Mendoza"]),
"Carpathian Mountains Completed - Suit Only":(1064,["h3","carpathian_mountains"],["so","carpathian_mountains_so"],["Level - Carpathian Mountains"]),
"Ambrose Island Completed - Suit Only":(1065,["h3","ambrose_island"],["so","ambrose_island_so"],["Level - Ambrose Island"]),
"ICA Facility Completed - Silent Assassin, Suit Only":(1066,["free","ica_facility"],["saso","ica_facility_saso"],["Level - ICA Facility"]),
"Paris Completed - Silent Assassin, Suit Only":(1067,["h1","paris"],["saso","paris_saso"],["Level - Paris"]),
"Sapienza Completed - Silent Assassin, Suit Only":(1068,["h1","sapienza"],["saso","sapienza_saso"],["Level - Sapienza"]),
"Marrakesh Completed - Silent Assassin, Suit Only":(1069,["h1","marrakesh"],["saso","marrakesh_saso"],["Level - Marrakesh"]),
"Bangkok Completed - Silent Assassin, Suit Only":(1070,["h1","bangkok"],["saso","bangkok_saso"],["Level - Bangkok"]),
"Colorado Completed - Silent Assassin, Suit Only":(1071,["h1","colorado"],["saso","colorado_saso"],["Level - Colorado"]),
"Hokkaido Completed - Silent Assassin, Suit Only":(1072,["h1","hokkaido"],["saso","hokkaido_saso"],["Level - Hokkaido"]),
"Hawkes Bay Completed - Silent Assassin, Suit Only":(1073,["h2","hawkes_bay"],["saso","hawkes_bay_saso"],["Level - Hawkes Bay"]),
"Miami Completed - Silent Assassin, Suit Only":(1074,["h2","miami"],["saso","miami_saso"],["Level - Miami"]),
"Santa Fortuna Completed - Silent Assassin, Suit Only":(1075,["h2","santa_fortuna"],["saso","santa_fortuna_saso"],["Level - Santa Fortuna"]),
"Mumbai Completed - Silent Assassin, Suit Only":(1076,["h2","mumbai"],["saso","mumbai_saso"],["Level - Mumbai"]),
"Whittleton Creek Completed - Silent Assassin, Suit Only":(1077,["h2","whittleton_creek"],["saso","whittleton_creek_saso"],["Level - Whittleton Creek"]),
"Isle of Sgail Completed - Silent Assassin, Suit Only":(1078,["h2","isle_of_sgail"],["saso","isle_of_sgail_saso"],["Level - Isle of Sgail"]),
"New York Completed - Silent Assassin, Suit Only":(1079,["h2_dlc","new_york"],["saso","new_york_saso"],["Level - New York"]),
"Haven Island Completed - Silent Assassin, Suit Only":(1080,["h2_dlc","haven_island"],["saso","haven_island_saso"],["Level - Haven Island"]),
"Dubai Completed - Silent Assassin, Suit Only":(1081,["h3","dubai"],["saso","dubai_saso"],["Level - Dubai"]),
"Dartmoor Completed - Silent Assassin, Suit Only":(1082,["h3","dartmoor"],["saso","dartmoor_saso"],["Level - Dartmoor"]),
"Berlin Completed - Silent Assassin, Suit Only":(1083,["h3","berlin"],["saso","berlin_saso"],["Level - Berlin"]),
"Chongqing Completed - Silent Assassin, Suit Only":(1084,["h3","chongqing"],["saso","chongqing_saso"],["Level - Chongqing"]),
"Mendoza Completed - Silent Assassin, Suit Only":(1085,["h3","mendoza"],["saso","mendoza_saso"],["Level - Mendoza"]),
"Carpathian Mountains Completed - Silent Assassin, Suit Only":(1086,["h3","carpathian_mountains"],["saso","carpathian_mountains_saso"],["Level - Carpathian Mountains"]),
"Ambrose Island Completed - Silent Assassin, Suit Only":(1087,["h3","ambrose_island"],["saso","ambrose_island_saso"],["Level - Ambrose Island"])
}

goal_table = {
"ica_facility":"ICA Facility",
"paris":"Paris",
"sapienza":"Sapienza",
"marrakesh":"Marrakesh",
"bangkok":"Bangkok",
"colorado":"Colorado",
"hokkaido":"Hokkaido",
"hawkes_bay":"Hawkes Bay",
"miami":"Miami",
"santa_fortuna":"Santa Fortuna",
"mumbai":"Mumbai",
"whittleton_creek":"Whittleton Creek",
"isle_of_sgail":"Isle of Sgail",
"new_york":"New York",
"haven_island":"Haven Island",
"dubai":"Dubai",
"dartmoorr":"Dartmoor",
"berlin":"Berlin",
"chongqing":"Chongqing",
"mendoza":"Mendoza",
"carpathian_mountains":"Carpathian Mountains",
"ambrose_island":"Ambrose Island"
}
