from BaseClasses import Location

class HitmanLocation(Location):
    game: str = "HITMAN World of Assasination"

# TODO: itemsanity does not enable when goal level gets enabled
location_table = { #id, location entitlments (one of required), settings requirement (one of required), required items (one of)
"Itempickup - Apple":(1,["ambrose_island","chongqing","dartmoor","dubai","haven_island","hawkes_bay","isle_of_sgail","mendoza","new_york","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Chongqing", "Level - Dartmoor", "Level - Dubai", "Level - Haven Island", "Level - Hawkes Bay", "Level - Isle of Sgail", "Level - Mendoza", "Level - New York", "Level - Whittleton Creek"]),
"Itempickup - Soap":(2,["ambrose_island","carpathian_mountains","chongqing","dartmoor","dubai"], ["itemsanity"], ["Level - Ambrose Island", "Level - Carpathian Mountains", "Level - Chongqing", "Level - Dartmoor", "Level - Dubai"]),
"Itempickup - Banana":(3,["ambrose_island","berlin","chongqing","dartmoor","dubai","haven_island","mendoza"], ["itemsanity"], ["Level - Ambrose Island", "Level - Berlin", "Level - Chongqing", "Level - Dartmoor", "Level - Dubai", "Level - Haven Island", "Level - Mendoza"]),
"Itempickup - Apricot":(4,["ambrose_island","chongqing","colorado","dartmoor","isle_of_sgail","miami","new_york","santa_fortuna"], ["itemsanity"], ["Level - Ambrose Island", "Level - Chongqing", "Level - Colorado", "Level - Dartmoor", "Level - Isle of Sgail", "Level - Miami", "Level - New York", "Level - Santa Fortuna"]),
"Itempickup - Coin":(5,["ambrose_island","bangkok","berlin","chongqing","colorado","dartmoor","dubai","haven_island","hawkes_bay","hokkaido","ica_facility","isle_of_sgail","marrakesh","mendoza","miami","mumbai","new_york","paris","santa_fortuna","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Bangkok", "Level - Berlin", "Level - Chongqing", "Level - Colorado", "Level - Dartmoor", "Level - Dubai", "Level - Haven Island", "Level - Hawkes Bay", "Level - Hokkaido", "Level - ICA Facility", "Level - Isle of Sgail", "Level - Marrakesh", "Level - Mendoza", "Level - Miami", "Level - Mumbai", "Level - New York", "Level - Paris", "Level - Santa Fortuna", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Doubloon":(6,["ambrose_island","haven_island"], ["itemsanity"], ["Level - Ambrose Island", "Level - Haven Island"]),
"Itempickup - Fire Extinguisher":(7,["ambrose_island","bangkok","berlin","carpathian_mountains","chongqing","colorado","dubai","haven_island","hokkaido","isle_of_sgail","marrakesh","mendoza","miami","mumbai","new_york","paris","santa_fortuna","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Bangkok", "Level - Berlin", "Level - Carpathian Mountains", "Level - Chongqing", "Level - Colorado", "Level - Dubai", "Level - Haven Island", "Level - Hokkaido", "Level - Isle of Sgail", "Level - Marrakesh", "Level - Mendoza", "Level - Miami", "Level - Mumbai", "Level - New York", "Level - Paris", "Level - Santa Fortuna", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Propane Flask":(8,["ambrose_island","bangkok","berlin","chongqing","colorado","dartmoor","dubai","haven_island","hawkes_bay","hokkaido","isle_of_sgail","marrakesh","mendoza","miami","mumbai","new_york","paris","santa_fortuna","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Bangkok", "Level - Berlin", "Level - Chongqing", "Level - Colorado", "Level - Dartmoor", "Level - Dubai", "Level - Haven Island", "Level - Hawkes Bay", "Level - Hokkaido", "Level - Isle of Sgail", "Level - Marrakesh", "Level - Mendoza", "Level - Miami", "Level - Mumbai", "Level - New York", "Level - Paris", "Level - Santa Fortuna", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Emetic Gas Grenade":(9,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Molotov Cocktail":(10,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Makeshift Explosive":(11,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Remote CX Demo Block Mk II":(12,["ambrose_island","mendoza"], ["itemsanity"], ["Level - Ambrose Island", "Level - Mendoza"]),
"Itempickup - Remote Breaching Charge":(13,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Nitroglycerin":(14,["ambrose_island","colorado","isle_of_sgail"], ["itemsanity"], ["Level - Ambrose Island", "Level - Colorado", "Level - Isle of Sgail"]),
"Itempickup - Sawed-Off Bartoli 12G":(15,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Brine-Damaged SMG":(16,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Shashka A33":(17,["ambrose_island","marrakesh","mumbai","santa_fortuna"], ["itemsanity"], ["Level - Ambrose Island", "Level - Marrakesh", "Level - Mumbai", "Level - Santa Fortuna"]),
"Itempickup - Shashka A33 Gold":(18,["ambrose_island","santa_fortuna"], ["itemsanity"], ["Level - Ambrose Island", "Level - Santa Fortuna"]),
"Itempickup - Militia-Issued HX-10 SMG":(19,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Fishing Line":(20,["ambrose_island","mendoza"], ["itemsanity"], ["Level - Ambrose Island", "Level - Mendoza"]),
"Itempickup - Garden Fork":(21,["ambrose_island","berlin","chongqing","dartmoor","mendoza"], ["itemsanity"], ["Level - Ambrose Island", "Level - Berlin", "Level - Chongqing", "Level - Dartmoor", "Level - Mendoza"]),
"Itempickup - Starfish":(22,["ambrose_island","haven_island","isle_of_sgail","miami"], ["itemsanity"], ["Level - Ambrose Island", "Level - Haven Island", "Level - Isle of Sgail", "Level - Miami"]),
"Itempickup - Scissors":(23,["ambrose_island","chongqing","dartmoor","dubai","haven_island","hawkes_bay","hokkaido","isle_of_sgail","marrakesh","miami","mumbai","new_york","paris","santa_fortuna","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Chongqing", "Level - Dartmoor", "Level - Dubai", "Level - Haven Island", "Level - Hawkes Bay", "Level - Hokkaido", "Level - Isle of Sgail", "Level - Marrakesh", "Level - Miami", "Level - Mumbai", "Level - New York", "Level - Paris", "Level - Santa Fortuna", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Cleaver":(24,["ambrose_island","bangkok","chongqing","colorado","dartmoor","dubai","haven_island","hawkes_bay","hokkaido","isle_of_sgail","marrakesh","miami","mumbai","paris","santa_fortuna","sapienza"], ["itemsanity"], ["Level - Ambrose Island", "Level - Bangkok", "Level - Chongqing", "Level - Colorado", "Level - Dartmoor", "Level - Dubai", "Level - Haven Island", "Level - Hawkes Bay", "Level - Hokkaido", "Level - Isle of Sgail", "Level - Marrakesh", "Level - Miami", "Level - Mumbai", "Level - Paris", "Level - Santa Fortuna", "Level - Sapienza"]),
"Itempickup - Kitchen Knife":(25,["ambrose_island","bangkok","berlin","chongqing","colorado","dartmoor","dubai","haven_island","hawkes_bay","hokkaido","isle_of_sgail","marrakesh","mendoza","miami","mumbai","new_york","paris","santa_fortuna","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Bangkok", "Level - Berlin", "Level - Chongqing", "Level - Colorado", "Level - Dartmoor", "Level - Dubai", "Level - Haven Island", "Level - Hawkes Bay", "Level - Hokkaido", "Level - Isle of Sgail", "Level - Marrakesh", "Level - Mendoza", "Level - Miami", "Level - Mumbai", "Level - New York", "Level - Paris", "Level - Santa Fortuna", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Meat Fork":(26,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Letter Opener":(27,["ambrose_island","bangkok","chongqing","dartmoor","dubai","haven_island","isle_of_sgail","marrakesh","mumbai","new_york","paris","santa_fortuna","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Bangkok", "Level - Chongqing", "Level - Dartmoor", "Level - Dubai", "Level - Haven Island", "Level - Isle of Sgail", "Level - Marrakesh", "Level - Mumbai", "Level - New York", "Level - Paris", "Level - Santa Fortuna", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Kukri Machete":(28,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Seashell":(29,["ambrose_island","haven_island"], ["itemsanity"], ["Level - Ambrose Island", "Level - Haven Island"]),
"Itempickup - Screwdriver":(30,["ambrose_island","bangkok","berlin","chongqing","colorado","dartmoor","dubai","haven_island","hawkes_bay","hokkaido","isle_of_sgail","marrakesh","mendoza","miami","mumbai","new_york","paris","santa_fortuna","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Bangkok", "Level - Berlin", "Level - Chongqing", "Level - Colorado", "Level - Dartmoor", "Level - Dubai", "Level - Haven Island", "Level - Hawkes Bay", "Level - Hokkaido", "Level - Isle of Sgail", "Level - Marrakesh", "Level - Mendoza", "Level - Miami", "Level - Mumbai", "Level - New York", "Level - Paris", "Level - Santa Fortuna", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Folding Knife":(31,["ambrose_island","dartmoor","dubai","haven_island","hawkes_bay","mumbai","new_york","santa_fortuna","sapienza"], ["itemsanity"], ["Level - Ambrose Island", "Level - Dartmoor", "Level - Dubai", "Level - Haven Island", "Level - Hawkes Bay", "Level - Mumbai", "Level - New York", "Level - Santa Fortuna", "Level - Sapienza"]),
"Itempickup - Old Axe":(32,["ambrose_island","berlin","colorado","isle_of_sgail","mendoza","miami","mumbai","sapienza"], ["itemsanity"], ["Level - Ambrose Island", "Level - Berlin", "Level - Colorado", "Level - Isle of Sgail", "Level - Mendoza", "Level - Miami", "Level - Mumbai", "Level - Sapienza"]),
"Itempickup - Hook":(33,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Scrap Sword":(34,["ambrose_island","berlin","chongqing"], ["itemsanity"], ["Level - Ambrose Island", "Level - Berlin", "Level - Chongqing"]),
"Itempickup - Shears":(35,["ambrose_island","dartmoor","mendoza"], ["itemsanity"], ["Level - Ambrose Island", "Level - Dartmoor", "Level - Mendoza"]),
"Itempickup - Barber Razor":(36,["ambrose_island","carpathian_mountains","dartmoor","haven_island","mumbai","santa_fortuna"], ["itemsanity"], ["Level - Ambrose Island", "Level - Carpathian Mountains", "Level - Dartmoor", "Level - Haven Island", "Level - Mumbai", "Level - Santa Fortuna"]),
"Itempickup - Hobby Knife":(37,["ambrose_island","berlin","chongqing","mendoza","new_york"], ["itemsanity"], ["Level - Ambrose Island", "Level - Berlin", "Level - Chongqing", "Level - Mendoza", "Level - New York"]),
"Itempickup - Jarl's Pirate Saber":(38,["ambrose_island","haven_island","mendoza"], ["itemsanity"], ["Level - Ambrose Island", "Level - Haven Island", "Level - Mendoza"]),
"Itempickup - Wooden Torch":(39,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Coconut":(40,["ambrose_island","bangkok","berlin","dubai","haven_island","isle_of_sgail","miami","santa_fortuna"], ["itemsanity"], ["Level - Ambrose Island", "Level - Bangkok", "Level - Berlin", "Level - Dubai", "Level - Haven Island", "Level - Isle of Sgail", "Level - Miami", "Level - Santa Fortuna"]),
"Itempickup - Driftwood Log":(41,["ambrose_island","chongqing","dartmoor","haven_island","hawkes_bay","isle_of_sgail","santa_fortuna"], ["itemsanity"], ["Level - Ambrose Island", "Level - Chongqing", "Level - Dartmoor", "Level - Haven Island", "Level - Hawkes Bay", "Level - Isle of Sgail", "Level - Santa Fortuna"]),
"Itempickup - Lead Pipe":(42,["ambrose_island","bangkok","berlin","chongqing","colorado","dartmoor","haven_island","hawkes_bay","hokkaido","ica_facility","isle_of_sgail","miami","mumbai","new_york","paris","santa_fortuna","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Bangkok", "Level - Berlin", "Level - Chongqing", "Level - Colorado", "Level - Dartmoor", "Level - Haven Island", "Level - Hawkes Bay", "Level - Hokkaido", "Level - ICA Facility", "Level - Isle of Sgail", "Level - Miami", "Level - Mumbai", "Level - New York", "Level - Paris", "Level - Santa Fortuna", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Brick":(43,["ambrose_island","berlin","carpathian_mountains","chongqing","colorado","dartmoor","ica_facility","isle_of_sgail","marrakesh","mendoza","miami","mumbai","paris","santa_fortuna","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Berlin", "Level - Carpathian Mountains", "Level - Chongqing", "Level - Colorado", "Level - Dartmoor", "Level - ICA Facility", "Level - Isle of Sgail", "Level - Marrakesh", "Level - Mendoza", "Level - Miami", "Level - Mumbai", "Level - Paris", "Level - Santa Fortuna", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Hammer":(44,["ambrose_island","bangkok","berlin","chongqing","colorado","dartmoor","dubai","haven_island","hokkaido","ica_facility","isle_of_sgail","marrakesh","miami","mumbai","paris","santa_fortuna","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Bangkok", "Level - Berlin", "Level - Chongqing", "Level - Colorado", "Level - Dartmoor", "Level - Dubai", "Level - Haven Island", "Level - Hokkaido", "Level - ICA Facility", "Level - Isle of Sgail", "Level - Marrakesh", "Level - Miami", "Level - Mumbai", "Level - Paris", "Level - Santa Fortuna", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Crowbar":(45,["ambrose_island","bangkok","berlin","chongqing","colorado","dartmoor","dubai","haven_island","hokkaido","ica_facility","isle_of_sgail","marrakesh","mendoza","miami","mumbai","new_york","paris","santa_fortuna","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Bangkok", "Level - Berlin", "Level - Chongqing", "Level - Colorado", "Level - Dartmoor", "Level - Dubai", "Level - Haven Island", "Level - Hokkaido", "Level - ICA Facility", "Level - Isle of Sgail", "Level - Marrakesh", "Level - Mendoza", "Level - Miami", "Level - Mumbai", "Level - New York", "Level - Paris", "Level - Santa Fortuna", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Car Battery":(46,["ambrose_island","berlin","chongqing","dartmoor","dubai","hawkes_bay","isle_of_sgail","mendoza","mumbai","new_york","santa_fortuna","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Berlin", "Level - Chongqing", "Level - Dartmoor", "Level - Dubai", "Level - Hawkes Bay", "Level - Isle of Sgail", "Level - Mendoza", "Level - Mumbai", "Level - New York", "Level - Santa Fortuna", "Level - Whittleton Creek"]),
"Itempickup - Whiskey Bottle":(47,["ambrose_island","chongqing","dubai"], ["itemsanity"], ["Level - Ambrose Island", "Level - Chongqing", "Level - Dubai"]),
"Itempickup - Spray Can":(48,["ambrose_island","berlin"], ["itemsanity"], ["Level - Ambrose Island", "Level - Berlin"]),
"Itempickup - Paddle":(49,["ambrose_island","haven_island","isle_of_sgail","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Haven Island", "Level - Isle of Sgail", "Level - Whittleton Creek"]),
"Itempickup - Vodka Bottle":(50,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Soda Can":(51,["ambrose_island","bangkok","berlin","carpathian_mountains","chongqing","colorado","dartmoor","dubai","haven_island","hawkes_bay","hokkaido","isle_of_sgail","marrakesh","mendoza","miami","mumbai","new_york","santa_fortuna","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Bangkok", "Level - Berlin", "Level - Carpathian Mountains", "Level - Chongqing", "Level - Colorado", "Level - Dartmoor", "Level - Dubai", "Level - Haven Island", "Level - Hawkes Bay", "Level - Hokkaido", "Level - Isle of Sgail", "Level - Marrakesh", "Level - Mendoza", "Level - Miami", "Level - Mumbai", "Level - New York", "Level - Santa Fortuna", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Wrench":(52,["ambrose_island","bangkok","berlin","chongqing","colorado","dartmoor","dubai","haven_island","hawkes_bay","hokkaido","ica_facility","isle_of_sgail","marrakesh","mendoza","miami","mumbai","new_york","paris","santa_fortuna","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Bangkok", "Level - Berlin", "Level - Chongqing", "Level - Colorado", "Level - Dartmoor", "Level - Dubai", "Level - Haven Island", "Level - Hawkes Bay", "Level - Hokkaido", "Level - ICA Facility", "Level - Isle of Sgail", "Level - Marrakesh", "Level - Mendoza", "Level - Miami", "Level - Mumbai", "Level - New York", "Level - Paris", "Level - Santa Fortuna", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Frying Pan":(53,["ambrose_island","berlin","chongqing","dubai","haven_island","hokkaido","isle_of_sgail","mendoza","miami","mumbai","paris","santa_fortuna"], ["itemsanity"], ["Level - Ambrose Island", "Level - Berlin", "Level - Chongqing", "Level - Dubai", "Level - Haven Island", "Level - Hokkaido", "Level - Isle of Sgail", "Level - Mendoza", "Level - Miami", "Level - Mumbai", "Level - Paris", "Level - Santa Fortuna"]),
"Itempickup - Fish":(54,["ambrose_island","dartmoor","haven_island","isle_of_sgail","mendoza","miami","mumbai"], ["itemsanity"], ["Level - Ambrose Island", "Level - Dartmoor", "Level - Haven Island", "Level - Isle of Sgail", "Level - Mendoza", "Level - Miami", "Level - Mumbai"]),
"Itempickup - Bag of Sugar":(55,["ambrose_island","berlin","dartmoor","miami"], ["itemsanity"], ["Level - Ambrose Island", "Level - Berlin", "Level - Dartmoor", "Level - Miami"]),
"Itempickup - Shovel":(56,["ambrose_island","bangkok","berlin","colorado","dartmoor","dubai","haven_island","hawkes_bay","hokkaido","isle_of_sgail","mendoza","miami","mumbai","santa_fortuna","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Bangkok", "Level - Berlin", "Level - Colorado", "Level - Dartmoor", "Level - Dubai", "Level - Haven Island", "Level - Hawkes Bay", "Level - Hokkaido", "Level - Isle of Sgail", "Level - Mendoza", "Level - Miami", "Level - Mumbai", "Level - Santa Fortuna", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Durian":(57,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Cannonball":(58,["ambrose_island","isle_of_sgail","mendoza","sapienza"], ["itemsanity"], ["Level - Ambrose Island", "Level - Isle of Sgail", "Level - Mendoza", "Level - Sapienza"]),
"Itempickup - Khatvanga":(59,["ambrose_island","isle_of_sgail","mumbai"], ["itemsanity"], ["Level - Ambrose Island", "Level - Isle of Sgail", "Level - Mumbai"]),
"Itempickup - Umbrella":(60,["ambrose_island","chongqing","mendoza"], ["itemsanity"], ["Level - Ambrose Island", "Level - Chongqing", "Level - Mendoza"]),
"Itempickup - Gold Idol":(61,["ambrose_island","berlin","dubai","haven_island","isle_of_sgail","new_york","santa_fortuna"], ["itemsanity"], ["Level - Ambrose Island", "Level - Berlin", "Level - Dubai", "Level - Haven Island", "Level - Isle of Sgail", "Level - New York", "Level - Santa Fortuna"]),
"Itempickup - Newspaper":(62,["ambrose_island","chongqing","dartmoor","haven_island","isle_of_sgail","new_york","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Chongqing", "Level - Dartmoor", "Level - Haven Island", "Level - Isle of Sgail", "Level - New York", "Level - Whittleton Creek"]),
"Itempickup - Cigar Box":(63,["ambrose_island","chongqing","dartmoor","isle_of_sgail","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Chongqing", "Level - Dartmoor", "Level - Isle of Sgail", "Level - Whittleton Creek"]),
"Itempickup - Iron":(64,["ambrose_island","berlin","chongqing","dartmoor","dubai","haven_island","isle_of_sgail","mumbai","new_york"], ["itemsanity"], ["Level - Ambrose Island", "Level - Berlin", "Level - Chongqing", "Level - Dartmoor", "Level - Dubai", "Level - Haven Island", "Level - Isle of Sgail", "Level - Mumbai", "Level - New York"]),
"Itempickup - Meaty Bone":(65,["ambrose_island","chongqing","dubai","haven_island","isle_of_sgail","mendoza","santa_fortuna","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Chongqing", "Level - Dubai", "Level - Haven Island", "Level - Isle of Sgail", "Level - Mendoza", "Level - Santa Fortuna", "Level - Whittleton Creek"]),
"Itempickup - Emetic Rat Poison":(66,["ambrose_island","bangkok","berlin","chongqing","colorado","dartmoor","dubai","haven_island","hawkes_bay","hokkaido","ica_facility","isle_of_sgail","marrakesh","mendoza","miami","mumbai","new_york","santa_fortuna","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Bangkok", "Level - Berlin", "Level - Chongqing", "Level - Colorado", "Level - Dartmoor", "Level - Dubai", "Level - Haven Island", "Level - Hawkes Bay", "Level - Hokkaido", "Level - ICA Facility", "Level - Isle of Sgail", "Level - Marrakesh", "Level - Mendoza", "Level - Miami", "Level - Mumbai", "Level - New York", "Level - Santa Fortuna", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Lethal Poisonous Frog":(67,["ambrose_island","haven_island","santa_fortuna","whittleton_creek"], ["itemsanity"], ["Level - Ambrose Island", "Level - Haven Island", "Level - Santa Fortuna", "Level - Whittleton Creek"]),
"Itempickup - Poisonous Flower (Emetic)":(68,["ambrose_island","dartmoor","haven_island","mendoza","santa_fortuna"], ["itemsanity"], ["Level - Ambrose Island", "Level - Dartmoor", "Level - Haven Island", "Level - Mendoza", "Level - Santa Fortuna"]),
"Itempickup - Lethal Poison Vial":(69,["ambrose_island"], ["itemsanity"], ["Level - Ambrose Island"]),
"Itempickup - Fusil G2":(70,["bangkok","colorado","haven_island","isle_of_sgail","paris","whittleton_creek"], ["itemsanity"], ["Level - Bangkok", "Level - Colorado", "Level - Haven Island", "Level - Isle of Sgail", "Level - Paris", "Level - Whittleton Creek"]),
"Itempickup - Bartoli 75R":(71,["bangkok","berlin","chongqing","colorado","dubai","marrakesh","miami","new_york","paris","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Bangkok", "Level - Berlin", "Level - Chongqing", "Level - Colorado", "Level - Dubai", "Level - Marrakesh", "Level - Miami", "Level - New York", "Level - Paris", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Tactical Bartoli 12G":(72,["bangkok","berlin","chongqing","colorado","haven_island","hawkes_bay","hokkaido","isle_of_sgail","marrakesh","miami","new_york","paris","sapienza"], ["itemsanity"], ["Level - Bangkok", "Level - Berlin", "Level - Chongqing", "Level - Colorado", "Level - Haven Island", "Level - Hawkes Bay", "Level - Hokkaido", "Level - Isle of Sgail", "Level - Marrakesh", "Level - Miami", "Level - New York", "Level - Paris", "Level - Sapienza"]),
"Itempickup - Hatchet":(73,["bangkok","dartmoor","haven_island","isle_of_sgail","mendoza","paris","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Bangkok", "Level - Dartmoor", "Level - Haven Island", "Level - Isle of Sgail", "Level - Mendoza", "Level - Paris", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Fire Axe":(74,["bangkok","berlin","carpathian_mountains","chongqing","dubai","haven_island","hokkaido","isle_of_sgail","marrakesh","mendoza","miami","mumbai","new_york","paris","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Bangkok", "Level - Berlin", "Level - Carpathian Mountains", "Level - Chongqing", "Level - Dubai", "Level - Haven Island", "Level - Hokkaido", "Level - Isle of Sgail", "Level - Marrakesh", "Level - Mendoza", "Level - Miami", "Level - Mumbai", "Level - New York", "Level - Paris", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Katana":(75,["bangkok","hawkes_bay","hokkaido","isle_of_sgail","sapienza"], ["itemsanity"], ["Level - Bangkok", "Level - Hawkes Bay", "Level - Hokkaido", "Level - Isle of Sgail", "Level - Sapienza"]),
"Itempickup - Sapper's Axe":(76,["bangkok","isle_of_sgail","mendoza"], ["itemsanity"], ["Level - Bangkok", "Level - Isle of Sgail", "Level - Mendoza"]),
"Itempickup - Police Baton":(77,["bangkok","berlin","haven_island","hokkaido","miami","new_york","paris","sapienza"], ["itemsanity"], ["Level - Bangkok", "Level - Berlin", "Level - Haven Island", "Level - Hokkaido", "Level - Miami", "Level - New York", "Level - Paris", "Level - Sapienza"]),
"Itempickup - Pool Ball":(78,["bangkok","berlin","dartmoor","ica_facility","marrakesh","new_york","santa_fortuna"], ["itemsanity"], ["Level - Bangkok", "Level - Berlin", "Level - Dartmoor", "Level - ICA Facility", "Level - Marrakesh", "Level - New York", "Level - Santa Fortuna"]),
"Itempickup - Baseball Bat":(79,["bangkok","berlin","colorado","haven_island","hokkaido","isle_of_sgail","miami","mumbai","santa_fortuna","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Bangkok", "Level - Berlin", "Level - Colorado", "Level - Haven Island", "Level - Hokkaido", "Level - Isle of Sgail", "Level - Miami", "Level - Mumbai", "Level - Santa Fortuna", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Golf Club":(80,["bangkok","dartmoor","dubai","haven_island","miami","new_york","paris","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Bangkok", "Level - Dartmoor", "Level - Dubai", "Level - Haven Island", "Level - Miami", "Level - New York", "Level - Paris", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Insecticide":(81,["bangkok","berlin","whittleton_creek"], ["itemsanity"], ["Level - Bangkok", "Level - Berlin", "Level - Whittleton Creek"]),
"Itempickup - Lethal Poison Pill Jar":(82,["bangkok","chongqing","colorado","dartmoor","dubai","haven_island","hawkes_bay","marrakesh","mendoza","miami","mumbai","new_york","santa_fortuna"], ["itemsanity"], ["Level - Bangkok", "Level - Chongqing", "Level - Colorado", "Level - Dartmoor", "Level - Dubai", "Level - Haven Island", "Level - Hawkes Bay", "Level - Marrakesh", "Level - Mendoza", "Level - Miami", "Level - Mumbai", "Level - New York", "Level - Santa Fortuna"]),
"Itempickup - Blueberry Muffin":(83,["berlin","carpathian_mountains","chongqing","dubai","haven_island","isle_of_sgail","new_york","whittleton_creek"], ["itemsanity"], ["Level - Berlin", "Level - Carpathian Mountains", "Level - Chongqing", "Level - Dubai", "Level - Haven Island", "Level - Isle of Sgail", "Level - New York", "Level - Whittleton Creek"]),
"Itempickup - Bird's Egg":(84,["berlin"], ["itemsanity"], ["Level - Berlin"]),
"Itempickup - ICA Remote Audio Distraction Mk III":(85,["berlin"], ["itemsanity"], ["Level - Berlin"]),
"Itempickup - Bartoli Woodsman Hunting Rifle":(86,["berlin","mendoza"], ["itemsanity"], ["Level - Berlin", "Level - Mendoza"]),
"Itempickup - Bartoli Hunting Shotgun":(87,["berlin","dartmoor","mendoza"], ["itemsanity"], ["Level - Berlin", "Level - Dartmoor", "Level - Mendoza"]),
"Itempickup - Battle Axe":(88,["berlin","isle_of_sgail","marrakesh","miami","paris","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Berlin", "Level - Isle of Sgail", "Level - Marrakesh", "Level - Miami", "Level - Paris", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Combat Knife":(89,["berlin","mendoza","sapienza"], ["itemsanity"], ["Level - Berlin", "Level - Mendoza", "Level - Sapienza"]),
"Itempickup - Concealable Knife":(90,["berlin"], ["itemsanity"], ["Level - Berlin"]),
"Itempickup - Toy Tank":(91,["berlin","chongqing","marrakesh","new_york","sapienza"], ["itemsanity"], ["Level - Berlin", "Level - Chongqing", "Level - Marrakesh", "Level - New York", "Level - Sapienza"]),
"Itempickup - Cocaine Brick":(92,["berlin","isle_of_sgail","mendoza","miami","santa_fortuna"], ["itemsanity"], ["Level - Berlin", "Level - Isle of Sgail", "Level - Mendoza", "Level - Miami", "Level - Santa Fortuna"]),
"Itempickup - Baseball":(93,["berlin","colorado","dartmoor","haven_island","miami","santa_fortuna","whittleton_creek"], ["itemsanity"], ["Level - Berlin", "Level - Colorado", "Level - Dartmoor", "Level - Haven Island", "Level - Miami", "Level - Santa Fortuna", "Level - Whittleton Creek"]),
"Itempickup - Modern Sedative Syringe":(94,["berlin"], ["itemsanity"], ["Level - Berlin"]),
"Itempickup - Poisonous (Emetic) Mushroom":(95,["berlin"], ["itemsanity"], ["Level - Berlin"]),
"Itempickup - Lethal Pills":(96,["berlin","whittleton_creek"], ["itemsanity"], ["Level - Berlin", "Level - Whittleton Creek"]),
"Itempickup - Modern Lethal Syringe":(97,["berlin","colorado","miami"], ["itemsanity"], ["Level - Berlin", "Level - Colorado", "Level - Miami"]),
"Itempickup - Flash Grenade":(98,["carpathian_mountains","isle_of_sgail","new_york","whittleton_creek"], ["itemsanity"], ["Level - Carpathian Mountains", "Level - Isle of Sgail", "Level - New York", "Level - Whittleton Creek"]),
"Itempickup - Fragmentation Grenade":(99,["carpathian_mountains","hawkes_bay"], ["itemsanity"], ["Level - Carpathian Mountains", "Level - Hawkes Bay"]),
"Itempickup - Flash Grenade Mk III":(100,["carpathian_mountains"], ["itemsanity"], ["Level - Carpathian Mountains"]),
"Itempickup - ICA SMG White Raptor Covert":(101,["carpathian_mountains"], ["itemsanity"], ["Level - Carpathian Mountains"]),
"Itempickup - HWK21 Pale":(102,["carpathian_mountains"], ["itemsanity"], ["Level - Carpathian Mountains"]),
"Itempickup - ICA Tactical Shotgun Covert":(103,["carpathian_mountains"], ["itemsanity"], ["Level - Carpathian Mountains"]),
"Itempickup - ICA19 Black Lily":(104,["carpathian_mountains"], ["itemsanity"], ["Level - Carpathian Mountains"]),
"Itempickup - Icicle":(105,["carpathian_mountains","mendoza"], ["itemsanity"], ["Level - Carpathian Mountains", "Level - Mendoza"]),
"Itempickup - Rusty Screwdriver":(106,["carpathian_mountains"], ["itemsanity"], ["Level - Carpathian Mountains"]),
"Itempickup - Fiber Wire":(107,["carpathian_mountains"], ["itemsanity"], ["Level - Carpathian Mountains"]),
"Itempickup - Rusty Crowbar":(108,["carpathian_mountains"], ["itemsanity"], ["Level - Carpathian Mountains"]),
"Itempickup - Imperial Filigree Egg":(109,["carpathian_mountains","dartmoor","dubai","haven_island","isle_of_sgail","mendoza","new_york"], ["itemsanity"], ["Level - Carpathian Mountains", "Level - Dartmoor", "Level - Dubai", "Level - Haven Island", "Level - Isle of Sgail", "Level - Mendoza", "Level - New York"]),
"Itempickup - Claw Hammer":(110,["carpathian_mountains","mendoza","new_york","santa_fortuna"], ["itemsanity"], ["Level - Carpathian Mountains", "Level - Mendoza", "Level - New York", "Level - Santa Fortuna"]),
"Itempickup - Remote Explosive":(111,["chongqing","haven_island","marrakesh","paris","santa_fortuna","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Chongqing", "Level - Haven Island", "Level - Marrakesh", "Level - Paris", "Level - Santa Fortuna", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Hackl Leviathan Sniper Rifle Covert":(112,["chongqing"], ["itemsanity"], ["Level - Chongqing"]),
"Itempickup - Hackl 9S Covert":(113,["chongqing","dartmoor","dubai","haven_island","hawkes_bay","isle_of_sgail","mendoza","santa_fortuna","whittleton_creek"], ["itemsanity"], ["Level - Chongqing", "Level - Dartmoor", "Level - Dubai", "Level - Haven Island", "Level - Hawkes Bay", "Level - Isle of Sgail", "Level - Mendoza", "Level - Santa Fortuna", "Level - Whittleton Creek"]),
"Itempickup - ICA SMG Raptor Covert":(114,["chongqing"], ["itemsanity"], ["Level - Chongqing"]),
"Itempickup - Fusil X2000 Stealth":(115,["chongqing"], ["itemsanity"], ["Level - Chongqing"]),
"Itempickup - Tanto":(116,["chongqing","new_york"], ["itemsanity"], ["Level - Chongqing", "Level - New York"]),
"Itempickup - Stethoscope":(117,["chongqing","haven_island"], ["itemsanity"], ["Level - Chongqing", "Level - Haven Island"]),
"Itempickup - Mannequin Arm":(118,["chongqing","colorado"], ["itemsanity"], ["Level - Chongqing", "Level - Colorado"]),
"Itempickup - Package":(119,["chongqing","new_york","whittleton_creek"], ["itemsanity"], ["Level - Chongqing", "Level - New York", "Level - Whittleton Creek"]),
"Itempickup - Cowboy Bust":(120,["chongqing","colorado","hokkaido","isle_of_sgail","santa_fortuna"], ["itemsanity"], ["Level - Chongqing", "Level - Colorado", "Level - Hokkaido", "Level - Isle of Sgail", "Level - Santa Fortuna"]),
"Itempickup - Chloroform Flask":(121,["chongqing","hawkes_bay","isle_of_sgail","new_york"], ["itemsanity"], ["Level - Chongqing", "Level - Hawkes Bay", "Level - Isle of Sgail", "Level - New York"]),
"Itempickup - Explosive Watch Battery":(122,["colorado"], ["itemsanity"], ["Level - Colorado"]),
"Itempickup - Bartoli 12G":(123,["colorado","mumbai","santa_fortuna","sapienza"], ["itemsanity"], ["Level - Colorado", "Level - Mumbai", "Level - Santa Fortuna", "Level - Sapienza"]),
"Itempickup - HX-10":(124,["colorado","dubai","haven_island","isle_of_sgail"], ["itemsanity"], ["Level - Colorado", "Level - Dubai", "Level - Haven Island", "Level - Isle of Sgail"]),
"Itempickup - HX-7":(125,["colorado","hawkes_bay","hokkaido"], ["itemsanity"], ["Level - Colorado", "Level - Hawkes Bay", "Level - Hokkaido"]),
"Itempickup - Branding Iron":(126,["colorado","isle_of_sgail"], ["itemsanity"], ["Level - Colorado", "Level - Isle of Sgail"]),
"Itempickup - Classic Coin":(127,["dartmoor"], ["itemsanity"], ["Level - Dartmoor"]),
"Itempickup - Unicorn Horn":(128,["dartmoor"], ["itemsanity"], ["Level - Dartmoor"]),
"Itempickup - Saber":(129,["dartmoor","isle_of_sgail","marrakesh","mumbai","paris","sapienza"], ["itemsanity"], ["Level - Dartmoor", "Level - Isle of Sgail", "Level - Marrakesh", "Level - Mumbai", "Level - Paris", "Level - Sapienza"]),
"Itempickup - Rake":(130,["dartmoor","mendoza","mumbai","whittleton_creek"], ["itemsanity"], ["Level - Dartmoor", "Level - Mendoza", "Level - Mumbai", "Level - Whittleton Creek"]),
"Itempickup - Walking Cane":(131,["dartmoor"], ["itemsanity"], ["Level - Dartmoor"]),
"Itempickup - Bust":(132,["dartmoor","hawkes_bay","hokkaido","ica_facility","isle_of_sgail","miami","new_york","paris","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Dartmoor", "Level - Hawkes Bay", "Level - Hokkaido", "Level - ICA Facility", "Level - Isle of Sgail", "Level - Miami", "Level - New York", "Level - Paris", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Feather Duster":(133,["dartmoor","haven_island","new_york"], ["itemsanity"], ["Level - Dartmoor", "Level - Haven Island", "Level - New York"]),
"Itempickup - Fire Poker":(134,["dartmoor","hawkes_bay","hokkaido","isle_of_sgail","mendoza","paris","sapienza"], ["itemsanity"], ["Level - Dartmoor", "Level - Hawkes Bay", "Level - Hokkaido", "Level - Isle of Sgail", "Level - Mendoza", "Level - Paris", "Level - Sapienza"]),
"Itempickup - Maori Paddle":(135,["dartmoor","haven_island","hawkes_bay"], ["itemsanity"], ["Level - Dartmoor", "Level - Haven Island", "Level - Hawkes Bay"]),
"Itempickup - Explosive Golf Ball":(136,["dubai","sapienza"], ["itemsanity"], ["Level - Dubai", "Level - Sapienza"]),
"Itempickup - Fusil G1-4":(137,["dubai","marrakesh"], ["itemsanity"], ["Level - Dubai", "Level - Marrakesh"]),
"Itempickup - Ornate Scimitar":(138,["dubai"], ["itemsanity"], ["Level - Dubai"]),
"Itempickup - Goldbar":(139,["dubai","new_york"], ["itemsanity"], ["Level - Dubai", "Level - New York"]),
"Itempickup - Model of the Sceptre":(140,["dubai"], ["itemsanity"], ["Level - Dubai"]),
"Itempickup - Wet Floor Sign":(141,["dubai","haven_island","mendoza","new_york"], ["itemsanity"], ["Level - Dubai", "Level - Haven Island", "Level - Mendoza", "Level - New York"]),
"Itempickup - Emetic Pills":(142,["dubai","whittleton_creek"], ["itemsanity"], ["Level - Dubai", "Level - Whittleton Creek"]),
"Itempickup - Cheeseburger":(143,["haven_island","isle_of_sgail","new_york"], ["itemsanity"], ["Level - Haven Island", "Level - Isle of Sgail", "Level - New York"]),
"Itempickup - Bartoli 75S":(144,["haven_island","hawkes_bay","isle_of_sgail","mendoza","mumbai","santa_fortuna","sapienza"], ["itemsanity"], ["Level - Haven Island", "Level - Hawkes Bay", "Level - Isle of Sgail", "Level - Mendoza", "Level - Mumbai", "Level - Santa Fortuna", "Level - Sapienza"]),
"Itempickup - Earphones":(145,["haven_island","new_york"], ["itemsanity"], ["Level - Haven Island", "Level - New York"]),
"Itempickup - Scalpel":(146,["haven_island","hokkaido","isle_of_sgail"], ["itemsanity"], ["Level - Haven Island", "Level - Hokkaido", "Level - Isle of Sgail"]),
"Itempickup - Machete":(147,["haven_island","mendoza","santa_fortuna"], ["itemsanity"], ["Level - Haven Island", "Level - Mendoza", "Level - Santa Fortuna"]),
"Itempickup - Kettlebell":(148,["haven_island"], ["itemsanity"], ["Level - Haven Island"]),
"Itempickup - Pearl":(149,["haven_island"], ["itemsanity"], ["Level - Haven Island"]),
"Itempickup - Modern Emetic Syringe":(150,["haven_island"], ["itemsanity"], ["Level - Haven Island"]),
"Itempickup - Squeaky Toy":(151,["hawkes_bay"], ["itemsanity"], ["Level - Hawkes Bay"]),
"Itempickup - Wristwatch Alarm":(152,["hawkes_bay","new_york"], ["itemsanity"], ["Level - Hawkes Bay", "Level - New York"]),
"Itempickup - Kalmer 1 - Tranquilizer":(153,["hawkes_bay","new_york"], ["itemsanity"], ["Level - Hawkes Bay", "Level - New York"]),
"Itempickup - Shuriken":(154,["hawkes_bay"], ["itemsanity"], ["Level - Hawkes Bay"]),
"Itempickup - Expired Can of Spaghetti Sauce":(155,["hawkes_bay","isle_of_sgail","mumbai","santa_fortuna","sapienza","whittleton_creek"], ["itemsanity"], ["Level - Hawkes Bay", "Level - Isle of Sgail", "Level - Mumbai", "Level - Santa Fortuna", "Level - Sapienza", "Level - Whittleton Creek"]),
"Itempickup - Botulinum Toxin":(156,["hokkaido","isle_of_sgail"], ["itemsanity"], ["Level - Hokkaido", "Level - Isle of Sgail"]),
"Itempickup - Commemorative Token":(157,["isle_of_sgail","new_york"], ["itemsanity"], ["Level - Isle of Sgail", "Level - New York"]),
"Itempickup - Bag of Gunpowder":(158,["isle_of_sgail","mendoza","santa_fortuna","sapienza"], ["itemsanity"], ["Level - Isle of Sgail", "Level - Mendoza", "Level - Santa Fortuna", "Level - Sapienza"]),
"Itempickup - HX-7 Covert":(159,["isle_of_sgail"], ["itemsanity"], ["Level - Isle of Sgail"]),
"Itempickup - Hackl 9S":(160,["isle_of_sgail"], ["itemsanity"], ["Level - Isle of Sgail"]),
"Itempickup - Broadsword":(161,["isle_of_sgail","mendoza"], ["itemsanity"], ["Level - Isle of Sgail", "Level - Mendoza"]),
"Itempickup - Viking Axe":(162,["isle_of_sgail"], ["itemsanity"], ["Level - Isle of Sgail"]),
"Itempickup - Circumcision Knife":(163,["isle_of_sgail","sapienza"], ["itemsanity"], ["Level - Isle of Sgail", "Level - Sapienza"]),
"Itempickup - Aztec Necklace":(164,["isle_of_sgail"], ["itemsanity"], ["Level - Isle of Sgail"]),
"Itempickup - Sacrificial Knife":(165,["isle_of_sgail","santa_fortuna"], ["itemsanity"], ["Level - Isle of Sgail", "Level - Santa Fortuna"]),
"Itempickup - Mace":(166,["isle_of_sgail"], ["itemsanity"], ["Level - Isle of Sgail"]),
"Itempickup - Torch":(167,["isle_of_sgail","mendoza"], ["itemsanity"], ["Level - Isle of Sgail", "Level - Mendoza"]),
"Itempickup - Grapevine":(168,["mendoza"], ["itemsanity"], ["Level - Mendoza"]),
"Itempickup - Sieger AR552 Tactical":(169,["mendoza"], ["itemsanity"], ["Level - Mendoza"]),
"Itempickup - Sieger 300 Tactical":(170,["mendoza"], ["itemsanity"], ["Level - Mendoza"]),
"Itempickup - Grape Knife":(171,["mendoza"], ["itemsanity"], ["Level - Mendoza"]),
"Itempickup - Violin":(172,["mendoza","new_york"], ["itemsanity"], ["Level - Mendoza", "Level - New York"]),
"Itempickup - Cabernet Sauvignon":(173,["mendoza"], ["itemsanity"], ["Level - Mendoza"]),
"Itempickup - Pinot Noir":(174,["mendoza"], ["itemsanity"], ["Level - Mendoza"]),
"Itempickup - Malbec":(175,["mendoza"], ["itemsanity"], ["Level - Mendoza"]),
"Itempickup - 1945 Grand Paladin":(176,["mendoza"], ["itemsanity"], ["Level - Mendoza"]),
"Itempickup - The Big One":(177,["miami"], ["itemsanity"], ["Level - Miami"]),
"Itempickup - Kronstadt Octane Booster":(178,["miami"], ["itemsanity"], ["Level - Miami"]),
"Itempickup - Car Bomb":(179,["miami","whittleton_creek"], ["itemsanity"], ["Level - Miami", "Level - Whittleton Creek"]),
"Itempickup - Amputation Knife":(180,["miami","mumbai","sapienza"], ["itemsanity"], ["Level - Miami", "Level - Mumbai", "Level - Sapienza"]),
"Itempickup - Didgeridoo":(181,["miami"], ["itemsanity"], ["Level - Miami"]),
"Itempickup - Android Arm":(182,["miami"], ["itemsanity"], ["Level - Miami"]),
"Itempickup - Pneumatic Wrench":(183,["miami"], ["itemsanity"], ["Level - Miami"]),
"Itempickup - Cannabis Joint":(184,["miami","whittleton_creek"], ["itemsanity"], ["Level - Miami", "Level - Whittleton Creek"]),
"Itempickup - DAK X2":(185,["mumbai","new_york","santa_fortuna","whittleton_creek"], ["itemsanity"], ["Level - Mumbai", "Level - New York", "Level - Santa Fortuna", "Level - Whittleton Creek"]),
"Itempickup - Druzhina 34":(186,["mumbai"], ["itemsanity"], ["Level - Mumbai"]),
"Itempickup - Beak Staff":(187,["mumbai","whittleton_creek"], ["itemsanity"], ["Level - Mumbai", "Level - Whittleton Creek"]),
"Itempickup - Measuring Tape":(188,["mumbai"], ["itemsanity"], ["Level - Mumbai"]),
"Itempickup - Chennai Cricket Ball":(189,["mumbai"], ["itemsanity"], ["Level - Mumbai"]),
"Itempickup - Lever":(190,["mumbai"], ["itemsanity"], ["Level - Mumbai"]),
"Itempickup - Colored Smoke":(191,["mumbai"], ["itemsanity"], ["Level - Mumbai"]),
"Itempickup - Concussion Grenade":(192,["new_york"], ["itemsanity"], ["Level - New York"]),
"Itempickup - Letterbomb Parcel":(193,["new_york","santa_fortuna"], ["itemsanity"], ["Level - New York", "Level - Santa Fortuna"]),
"Itempickup - Golden Sawed Off Bartoli 12G":(194,["new_york"], ["itemsanity"], ["Level - New York"]),
"Itempickup - Burial Dagger":(195,["new_york"], ["itemsanity"], ["Level - New York"]),
"Itempickup - Antique Carved Knife":(196,["new_york"], ["itemsanity"], ["Level - New York"]),
"Itempickup - Small Goldbar":(197,["new_york"], ["itemsanity"], ["Level - New York"]),
"Itempickup - \"El Matador\"":(198,["santa_fortuna"], ["itemsanity"], ["Level - Santa Fortuna"]),
"Itempickup - Collectors Baseball Bat":(199,["santa_fortuna"], ["itemsanity"], ["Level - Santa Fortuna"]),
"Itempickup - Cocaine Souvenir":(200,["santa_fortuna"], ["itemsanity"], ["Level - Santa Fortuna"]),
"Itempickup - Poisonous Flower (Lethal)":(201,["santa_fortuna"], ["itemsanity"], ["Level - Santa Fortuna"]),
"Itempickup - Radio":(202,["sapienza"], ["itemsanity"], ["Level - Sapienza"]),
"Itempickup - Virus Prototype":(203,["sapienza"], ["itemsanity"], ["Level - Sapienza"]),
"Itempickup - Remote CX Demo Block":(204,["whittleton_creek"], ["itemsanity"], ["Level - Whittleton Creek"]),
"Itempickup - DAK X2 Covert Special":(205,["whittleton_creek"], ["itemsanity"], ["Level - Whittleton Creek"]),
"Itempickup - \"Rude Ruby\"":(206,["whittleton_creek"], ["itemsanity"], ["Level - Whittleton Creek"]),
"Itempickup - RS-15":(207,["whittleton_creek"], ["itemsanity"], ["Level - Whittleton Creek"]),
"Itempickup - TAC-4 AR Auto":(208,["whittleton_creek"], ["itemsanity"], ["Level - Whittleton Creek"]),
"Itempickup - Fusil G1-4/C":(209,["whittleton_creek"], ["itemsanity"], ["Level - Whittleton Creek"]),

# ============ MAP COMPLETION LOCATIONS ==============
"ICA Facility Completed":(1000,["free","ica_facility"],["completed","ica_facility_completed"],["Level - ICA Facility"]),
"Paris Completed":(1001,["h1","paris"],["completed","paris_completed"],["Level - Paris"]),
"Sapienza Completed":(1002,["h1","sapienza"],["completed","sapienza_completed"],["Level - Sapienza"]),
"Marrakesh Completed":(1003,["h1","marrakesh"],["completed","marrakesh_completed"],["Level - Marrakesh"]),
"Bangkok Completed":(1004,["h1","bangkok"],["completed","bangkok_completed"],["Level - Bangkok"]),
"Colorado Completed":(1005,["h1","colorado"],["completed","colorado_completed"],["Level - Colorado"]),
"Hokkaido Completed":(1006,["h1","hokkaido"],["completed","hokkaido_completed"],["Level - Hokkaido"]),
"Hawkes Bay Completed":(1007,["h2","hawkes_bay"],["completed","hawkes_bay_completed"],["Level - Hawkes Bay"]),
"Miami Completed":(1008,["h2","miami"],["completed","miami_completed"],["Level - Miami"]),
"Santa Fortuna Completed":(1009,["h2","santa_fortuna"],["completed","santa_fortuna_completed"],["Level - Santa Fortuna"]),
"Mumbai Completed":(1010,["h2","mumbai"],["completed","mumbai_completed"],["Level - Mumbai"]),
"Whittleton Creek Completed":(1011,["h2","whittleton_creek"],["completed","whittleton_creek_completed"],["Level - Whittleton Creek"]),
"Isle of Sgail Completed":(1012,["h2","isle_of_sgail"],["completed","isle_of_sgail_completed"],["Level - Isle of Sgail"]),
"New York Completed":(1013,["h2_dlc","new_york"],["completed","new_york_completed"],["Level - New York"]),
"Haven Island Completed":(1014,["h2_dlc","haven_island"],["completed","haven_island_completed"],["Level - Haven Island"]),
"Dubai Completed":(1015,["h3","dubai"],["completed","dubai_completed"],["Level - Dubai"]),
"Dartmoor Completed":(1016,["h3","dartmoor"],["completed","dartmoor_completed"],["Level - Dartmoor"]),
"Berlin Completed":(1017,["h3","berlin"],["completed","berlin_completed"],["Level - Berlin"]),
"Chongqing Completed":(1018,["h3","chongqing"],["completed","chongqing_completed"],["Level - Chongqing"]),
"Mendoza Completed":(1019,["h3","mendoza"],["completed","mendoza_completed"],["Level - Mendoza"]),
"Carpathian Mountains Completed":(1020,["h3","carpathian_mountains"],["completed","carpathian_mountains_completed"],["Level - Carpathian Mountains"]),
"Ambrose Island Completed":(1021,["h3","ambrose_island"],["completed","ambrose_island_completed"],["Level - Ambrose Island"]),
"ICA Facility Completed - Silent Assassin":(1022,["free","ica_facility"],["sa","ica_facility_sa"],["Level - ICA Facility"]),
"Paris Completed - Silent Assassin":(1023,["h1","paris"],["sa","paris_sa"],["Level - Paris"]),
"Sapienza Completed - Silent Assassin":(1024,["h1","sapienza"],["sa","sapienza_sa"],["Level - Sapienza"]),
"Marrakesh Completed - Silent Assassin":(1025,["h1","marrakesh"],["sa","marrakesh_sa"],["Level - Marrakesh"]),
"Bangkok Completed - Silent Assassin":(1026,["h1","bangkok"],["sa","bangkok_sa"],["Level - Bangkok"]),
"Colorado Completed - Silent Assassin":(1027,["h1","colorado"],["sa","colorado_sa"],["Level - Colorado"]),
"Hokkaido Completed - Silent Assassin":(1028,["h1","hokkaido"],["sa","hokkaido_sa"],["Level - Hokkaido"]),
"Hawkes Bay Completed - Silent Assassin":(1029,["h2","hawkes_bay"],["sa","hawkes_bay_sa"],["Level - Hawkes Bay"]),
"Miami Completed - Silent Assassin":(1030,["h2","miami"],["sa","miami_sa"],["Level - Miami"]),
"Santa Fortuna Completed - Silent Assassin":(1031,["h2","santa_fortuna"],["sa","santa_fortuna_sa"],["Level - Santa Fortuna"]),
"Mumbai Completed - Silent Assassin":(1032,["h2","mumbai"],["sa","mumbai_sa"],["Level - Mumbai"]),
"Whittleton Creek Completed - Silent Assassin":(1033,["h2","whittleton_creek"],["sa","whittleton_creek_sa"],["Level - Whittleton Creek"]),
"Isle of Sgail Completed - Silent Assassin":(1034,["h2","isle_of_sgail"],["sa","isle_of_sgail_sa"],["Level - Isle of Sgail"]),
"New York Completed - Silent Assassin":(1035,["h2_dlc","new_york"],["sa","new_york_sa"],["Level - New York"]),
"Haven Island Completed - Silent Assassin":(1036,["h2_dlc","haven_island"],["sa","haven_island_sa"],["Level - Haven Island"]),
"Dubai Completed - Silent Assassin":(1037,["h3","dubai"],["sa","dubai_sa"],["Level - Dubai"]),
"Dartmoor Completed - Silent Assassin":(1038,["h3","dartmoor"],["sa","dartmoor_sa"],["Level - Dartmoor"]),
"Berlin Completed - Silent Assassin":(1039,["h3","berlin"],["sa","berlin_sa"],["Level - Berlin"]),
"Chongqing Completed - Silent Assassin":(1040,["h3","chongqing"],["sa","chongqing_sa"],["Level - Chongqing"]),
"Mendoza Completed - Silent Assassin":(1041,["h3","mendoza"],["sa","mendoza_sa"],["Level - Mendoza"]),
"Carpathian Mountains Completed - Silent Assassin":(1042,["h3","carpathian_mountains"],["sa","carpathian_mountains_sa"],["Level - Carpathian Mountains"]),
"Ambrose Island Completed - Silent Assassin":(1043,["h3","ambrose_island"],["sa","ambrose_island_sa"],["Level - Ambrose Island"]),
"ICA Facility Completed - Suit Only":(1044,["free","ica_facility"],["so","ica_facility_so"],["Level - ICA Facility"]),
"Paris Completed - Suit Only":(1045,["h1","paris"],["so","paris_so"],["Level - Paris"]),
"Sapienza Completed - Suit Only":(1046,["h1","sapienza"],["so","sapienza_so"],["Level - Sapienza"]),
"Marrakesh Completed - Suit Only":(1047,["h1","marrakesh"],["so","marrakesh_so"],["Level - Marrakesh"]),
"Bangkok Completed - Suit Only":(1048,["h1","bangkok"],["so","bangkok_so"],["Level - Bangkok"]),
"Colorado Completed - Suit Only":(1049,["h1","colorado"],["so","colorado_so"],["Level - Colorado"]),
"Hokkaido Completed - Suit Only":(1050,["h1","hokkaido"],["so","hokkaido_so"],["Level - Hokkaido"]),
"Hawkes Bay Completed - Suit Only":(1051,["h2","hawkes_bay"],["so","hawkes_bay_so"],["Level - Hawkes Bay"]),
"Miami Completed - Suit Only":(1052,["h2","miami"],["so","miami_so"],["Level - Miami"]),
"Santa Fortuna Completed - Suit Only":(1053,["h2","santa_fortuna"],["so","santa_fortuna_so"],["Level - Santa Fortuna"]),
"Mumbai Completed - Suit Only":(1054,["h2","mumbai"],["so","mumbai_so"],["Level - Mumbai"]),
"Whittleton Creek Completed - Suit Only":(1055,["h2","whittleton_creek"],["so","whittleton_creek_so"],["Level - Whittleton Creek"]),
"Isle of Sgail Completed - Suit Only":(1056,["h2","isle_of_sgail"],["so","isle_of_sgail_so"],["Level - Isle of Sgail"]),
"New York Completed - Suit Only":(1057,["h2_dlc","new_york"],["so","new_york_so"],["Level - New York"]),
"Haven Island Completed - Suit Only":(1058,["h2_dlc","haven_island"],["so","haven_island_so"],["Level - Haven Island"]),
"Dubai Completed - Suit Only":(1059,["h3","dubai"],["so","dubai_so"],["Level - Dubai"]),
"Dartmoor Completed - Suit Only":(1060,["h3","dartmoor"],["so","dartmoor_so"],["Level - Dartmoor"]),
"Berlin Completed - Suit Only":(1061,["h3","berlin"],["so","berlin_so"],["Level - Berlin"]),
"Chongqing Completed - Suit Only":(1062,["h3","chongqing"],["so","chongqing_so"],["Level - Chongqing"]),
"Mendoza Completed - Suit Only":(1063,["h3","mendoza"],["so","mendoza_so"],["Level - Mendoza"]),
"Carpathian Mountains Completed - Suit Only":(1064,["h3","carpathian_mountains"],["so","carpathian_mountains_so"],["Level - Carpathian Mountains"]),
"Ambrose Island Completed - Suit Only":(1065,["h3","ambrose_island"],["so","ambrose_island_so"],["Level - Ambrose Island"]),
"ICA Facility Completed - Silent Assassin, Suit Only":(1066,["free","ica_facility"],["saso","ica_facility_saso"],["Level - ICA Facility"]),
"Paris Completed - Silent Assassin, Suit Only":(1067,["h1","paris"],["saso","paris_saso"],["Level - Paris"]),
"Sapienza Completed - Silent Assassin, Suit Only":(1068,["h1","sapienza"],["saso","sapienza_saso"],["Level - Sapienza"]),
"Marrakesh Completed - Silent Assassin, Suit Only":(1069,["h1","marrakesh"],["saso","marrakesh_saso"],["Level - Marrakesh"]),
"Bangkok Completed - Silent Assassin, Suit Only":(1070,["h1","bangkok"],["saso","bangkok_saso"],["Level - Bangkok"]),
"Colorado Completed - Silent Assassin, Suit Only":(1071,["h1","colorado"],["saso","colorado_saso"],["Level - Colorado"]),
"Hokkaido Completed - Silent Assassin, Suit Only":(1072,["h1","hokkaido"],["saso","hokkaido_saso"],["Level - Hokkaido"]),
"Hawkes Bay Completed - Silent Assassin, Suit Only":(1073,["h2","hawkes_bay"],["saso","hawkes_bay_saso"],["Level - Hawkes Bay"]),
"Miami Completed - Silent Assassin, Suit Only":(1074,["h2","miami"],["saso","miami_saso"],["Level - Miami"]),
"Santa Fortuna Completed - Silent Assassin, Suit Only":(1075,["h2","santa_fortuna"],["saso","santa_fortuna_saso"],["Level - Santa Fortuna"]),
"Mumbai Completed - Silent Assassin, Suit Only":(1076,["h2","mumbai"],["saso","mumbai_saso"],["Level - Mumbai"]),
"Whittleton Creek Completed - Silent Assassin, Suit Only":(1077,["h2","whittleton_creek"],["saso","whittleton_creek_saso"],["Level - Whittleton Creek"]),
"Isle of Sgail Completed - Silent Assassin, Suit Only":(1078,["h2","isle_of_sgail"],["saso","isle_of_sgail_saso"],["Level - Isle of Sgail"]),
"New York Completed - Silent Assassin, Suit Only":(1079,["h2_dlc","new_york"],["saso","new_york_saso"],["Level - New York"]),
"Haven Island Completed - Silent Assassin, Suit Only":(1080,["h2_dlc","haven_island"],["saso","haven_island_saso"],["Level - Haven Island"]),
"Dubai Completed - Silent Assassin, Suit Only":(1081,["h3","dubai"],["saso","dubai_saso"],["Level - Dubai"]),
"Dartmoor Completed - Silent Assassin, Suit Only":(1082,["h3","dartmoor"],["saso","dartmoor_saso"],["Level - Dartmoor"]),
"Berlin Completed - Silent Assassin, Suit Only":(1083,["h3","berlin"],["saso","berlin_saso"],["Level - Berlin"]),
"Chongqing Completed - Silent Assassin, Suit Only":(1084,["h3","chongqing"],["saso","chongqing_saso"],["Level - Chongqing"]),
"Mendoza Completed - Silent Assassin, Suit Only":(1085,["h3","mendoza"],["saso","mendoza_saso"],["Level - Mendoza"]),
"Carpathian Mountains Completed - Silent Assassin, Suit Only":(1086,["h3","carpathian_mountains"],["saso","carpathian_mountains_saso"],["Level - Carpathian Mountains"]),
"Ambrose Island Completed - Silent Assassin, Suit Only":(1087,["h3","ambrose_island"],["saso","ambrose_island_saso"],["Level - Ambrose Island"])
}

goal_table = {
"ica_facility":"ICA Facility",
"paris":"Paris",
"sapienza":"Sapienza",
"marrakesh":"Marrakesh",
"bangkok":"Bangkok",
"colorado":"Colorado",
"hokkaido":"Hokkaido",
"hawkes_bay":"Hawkes Bay",
"miami":"Miami",
"santa_fortuna":"Santa Fortuna",
"mumbai":"Mumbai",
"whittleton_creek":"Whittleton Creek",
"isle_of_sgail":"Isle of Sgail",
"new_york":"New York",
"haven_island":"Haven Island",
"dubai":"Dubai",
"dartmoorr":"Dartmoor",
"berlin":"Berlin",
"chongqing":"Chongqing",
"mendoza":"Mendoza",
"carpathian_mountains":"Carpathian Mountains",
"ambrose_island":"Ambrose Island"
}
